vert-x3/vertx-web

- src/main/asciidoc/groovy/index.adoc
- src/main/asciidoc/java/index.adoc
- src/main/asciidoc/js/index.adoc
- src/main/generated/io/vertx/rxjava/ext/apex/Cookie.java
- src/main/generated/io/vertx/rxjava/ext/apex/Session.java
- src/main/generated/io/vertx/rxjava/ext/apex/sstore/SessionStore.java
- src/main/generated/io/vertx/rxjava/ext/apex/templ/TemplateEngine.java
- src/main/groovy/io/vertx/groovy/ext/apex/Cookie.groovy
- src/main/groovy/io/vertx/groovy/ext/apex/Session.groovy
- src/main/java/examples/Examples.java
- src/main/java/io/vertx/ext/apex/Session.java
- src/main/java/io/vertx/ext/apex/handler/impl/AuthHandlerImpl.java
- src/main/java/io/vertx/ext/apex/handler/impl/BasicAuthHandlerImpl.java
- src/main/java/io/vertx/ext/apex/handler/impl/FormLoginHandlerImpl.java
- src/main/java/io/vertx/ext/apex/handler/impl/SessionHandlerImpl.java
- src/main/java/io/vertx/ext/apex/impl/SessionImpl.java
- src/main/java/io/vertx/ext/apex/package-info.java
- src/main/resources/vertx-apex-js/cookie.js
- src/main/resources/vertx-apex-js/session.js
- src/test/java/io/vertx/ext/apex/handler/AuthHandlerTestBase.java
- src/test/java/io/vertx/ext/apex/handler/BasicAuthHandlerTest.java
- src/test/java/io/vertx/ext/apex/handler/EventbusBridgeTest.java
- src/test/java/io/vertx/ext/apex/handler/RedirectAuthHandlerTest.java
@vietj And these are the corresponding changes in apex for the auth changes. Please review :)
> Updated for new auth service API

- src/main/java/io/vertx/ext/apex/impl/Utils.java
- src/test/java/io/vertx/ext/apex/UtilsTest.java
- src/test/java/io/vertx/ext/apex/handler/SockJSHandlerTest.java
- Perform URL decoding manually
- Remove dangerous sequences (.., //) while decoding
> Improve normalisePath

- pom.xml
- src/main/asciidoc/groovy/index.adoc
- src/main/asciidoc/java/index.adoc
- src/main/asciidoc/js/index.adoc
- src/main/generated/io/vertx/rxjava/ext/apex/Route.java
- src/main/groovy/io/vertx/groovy/ext/apex/Route.groovy
- src/main/java/examples/Examples.java
- src/main/java/io/vertx/ext/apex/Route.java
- src/main/java/io/vertx/ext/apex/handler/impl/StaticHandlerImpl.java
- src/main/java/io/vertx/ext/apex/handler/sockjs/impl/BaseTransport.java
- src/main/java/io/vertx/ext/apex/handler/sockjs/impl/HtmlFileTransport.java
- src/main/java/io/vertx/ext/apex/handler/sockjs/impl/SockJSHandlerImpl.java
- src/main/java/io/vertx/ext/apex/impl/RouteImpl.java
- src/main/java/io/vertx/ext/apex/impl/RouterImpl.java
- src/main/java/io/vertx/ext/apex/impl/SessionImpl.java
- src/main/java/io/vertx/ext/apex/package-info.java
- src/main/resources/vertx-apex-js/route.js
- src/test/java/io/vertx/ext/apex/RouterTest.java
- src/test/java/io/vertx/ext/apex/SubRouterTest.java
- src/test/java/io/vertx/ext/apex/handler/BasicAuthHandlerTest.java
- src/test/java/io/vertx/ext/apex/handler/EventbusBridgeTest.java
- src/test/java/io/vertx/ext/apex/handler/RedirectAuthHandlerTest.java
- src/test/java/io/vertx/ext/apex/handler/SockJSHandlerTest.java
- src/test/java/io/vertx/ext/apex/handler/StaticHandlerTest.java
- src/test/java/io/vertx/ext/apex/templ/TemplateTest.java
Now path and regex matches are exact by default and we allow * character to denote wildcard. Also some SockJS fixes.
@vietj please review :)
> Routing changes

- src/main/java/io/vertx/ext/apex/templ/impl/ThymeleafTemplateEngineImpl.java
There isn't a way to change the mode. You always get the default mode.
> Setting mode should use parameter rather than just setting default mode

- src/main/java/io/vertx/ext/apex/templ/HandlebarsTemplateEngine.java
- src/main/java/io/vertx/ext/apex/templ/JadeTemplateEngine.java
- src/main/java/io/vertx/ext/apex/templ/ThymeleafTemplateEngine.java
- src/main/java/io/vertx/ext/apex/templ/impl/HandlebarsTemplateEngineImpl.java
- src/main/java/io/vertx/ext/apex/templ/impl/JadeTemplateEngineImpl.java
- src/main/java/io/vertx/ext/apex/templ/impl/ThymeleafTemplateEngineImpl.java
- src/test/java/io/vertx/ext/apex/templ/HandlebarsTemplateTest.java
- src/test/java/io/vertx/ext/apex/templ/JadeTemplateTest.java
- src/test/java/io/vertx/ext/apex/templ/ThymeleafTemplateTest.java
Allow access to the internal object of a TemplateEngine so you can configure it.
> Access wrapped engine

- src/main/java/io/vertx/ext/apex/handler/impl/StaticHandlerImpl.java
- src/test/java/io/vertx/ext/apex/handler/StaticHandlerTest.java
- src/test/resources/webroot/somedir/index.html
- src/test/resources/webroot/somedir/otherpage.html
static index page should be also served all directories, not on root only
> static intex page also on subdirectories

- src/main/java/io/vertx/ext/apex/handler/impl/StaticHandlerImpl.java
- src/test/java/io/vertx/ext/apex/handler/StaticHandlerTest.java
- src/test/resources/webroot/somedir/index.html
- src/test/resources/webroot/somedir/otherpage.html
> Revert "static intex page also on subdirectories"

- src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
- src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java
Just get the body, nevertheless the method. See: #116
> Allow GET and HEADER to have bodies

- src/client/vertxbus.js
* The normal callback is still called on failure messages with an undefined result.  This was an attempt to preserve backwards compatibility with existing error handling code.
> Adding optional failure handler to EventBus.send()

- src/main/asciidoc/groovy/index.adoc
- src/main/asciidoc/java/index.adoc
- src/main/asciidoc/js/index.adoc
- src/main/asciidoc/ruby/index.adoc
- src/main/java/io/vertx/ext/web/Route.java
- src/main/java/io/vertx/ext/web/impl/BlockingHandlerDecorator.java
- src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- src/main/java/io/vertx/ext/web/package-info.java
- src/main/resources/vertx-web-js/cookie.js
- src/main/resources/vertx-web-js/route.js
- src/main/resources/vertx-web/cookie.rb
- src/main/resources/vertx-web/route.rb
- src/test/java/io/vertx/ext/web/UtilsTest.java
- src/test/java/io/vertx/ext/web/handler/BlockingHandlerTest.java
@vietj @cescoffier @pmlopes please review
> Implement unordered blocking handlers

- src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
- src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java
Added default timeout and headers for EventBusBridge awaiting reply.
Signed-off-by: Julien Lehuraux <jlehuraux@opexmedia.com>
> Fix default timeout and headers missing for EventBusBridge reply

- src/main/generated/io/vertx/rxjava/ext/web/handler/FormLoginHandler.java
- src/main/groovy/io/vertx/groovy/ext/web/handler/FormLoginHandler.groovy
- src/main/java/io/vertx/ext/web/handler/FormLoginHandler.java
- src/main/java/io/vertx/ext/web/handler/impl/BasicAuthHandlerImpl.java
- src/main/java/io/vertx/ext/web/handler/impl/FormLoginHandlerImpl.java
- src/main/resources/vertx-web-js/form_login_handler.js
- src/main/resources/vertx-web/form_login_handler.rb
- src/test/java/io/vertx/ext/web/handler/RedirectAuthHandlerTest.java
Related to https://github.com/vert-x3/vertx-examples/issues/55
We now return a default logged in ok page and also allow a logged in url to be specified if no redirect url in session.
@cescoffier @vietj @pmlopes  please review
> Allow direct login to be used on FormLoginHandler

- src/client/vertxbus.js
Updated #142 with backwards compatibility
> #142 allow passing headers without breaking existing API

- src/main/java/io/vertx/ext/web/Route.java
- src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- src/test/java/io/vertx/ext/web/RouterTest.java
Not sure if there was a future plan for this parameter but as is it doesn't get used and is a bit confusing.
> removed unused parameter

- src/main/asciidoc/groovy/index.adoc
- src/main/asciidoc/java/index.adoc
- src/main/generated/io/vertx/rxjava/ext/web/Route.java
- src/main/generated/io/vertx/rxjava/ext/web/handler/SessionHandler.java
- src/main/groovy/io/vertx/groovy/ext/web/Route.groovy
- src/main/groovy/io/vertx/groovy/ext/web/handler/SessionHandler.groovy
- src/main/java/io/vertx/ext/web/Route.java
- src/main/java/io/vertx/ext/web/handler/SessionHandler.java
- src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- src/main/resources/vertx-web-js/route.js
- src/main/resources/vertx-web-js/session_handler.js
- src/main/resources/vertx-web/route.rb
- src/main/resources/vertx-web/session_handler.rb
- src/test/java/io/vertx/ext/web/RouterTest.java
- src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java
Add support for SessionHandler to set the HTTPOnly and Secure cookie flags.
Note: I have only included the modified files and not the generated ones. If you want me to do so, let me know.
#173
> Implementation for #173 - SessionHandler HTTPOnly and Secure flag

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
See: #214 for the issue description.
> Implementation for #214: BodyHandler custom upload dir change

- vertx-web/pom.xml
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
Signed-off-by: Julien Ponge <julien.ponge@insa-lyon.fr>
> Minor simplification

- vertx-web/src/main/asciidoc/groovy/index.adoc
- vertx-web/src/main/asciidoc/js/index.adoc
- vertx-web/src/main/asciidoc/ruby/index.adoc
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
> Proper handling of escape in path parameters

- vertx-web/src/main/generated/io/vertx/rxjava/ext/web/sstore/ClusteredSessionStore.java
- vertx-web/src/main/generated/io/vertx/rxjava/ext/web/sstore/SessionStore.java
- vertx-web/src/main/groovy/io/vertx/groovy/ext/web/sstore/ClusteredSessionStore.groovy
- vertx-web/src/main/groovy/io/vertx/groovy/ext/web/sstore/SessionStore.groovy
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/sstore/ClusteredSessionStore.java
- vertx-web/src/main/java/io/vertx/ext/web/sstore/SessionStore.java
- vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/ClusteredSessionStoreImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/LocalSessionStoreImpl.java
- vertx-web/src/main/resources/vertx-web-js/clustered_session_store.js
- vertx-web/src/main/resources/vertx-web-js/session_store.js
- vertx-web/src/main/resources/vertx-web/clustered_session_store.rb
- vertx-web/src/main/resources/vertx-web/session_store.rb
- vertx-web/src/test/java/io/vertx/ext/web/handler/BasicAuthHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java
- vertx-web/src/test/java/io/vertx/ext/web/sstore/ClusteredSessionHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/sstore/LocalSessionHandlerTest.java
> Configurable and contextual session store retry timeout - fixes #224

- vertx-web/src/main/generated/io/vertx/rxjava/ext/web/RoutingContext.java
- vertx-web/src/main/groovy/io/vertx/groovy/ext/web/RoutingContext.groovy
- vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
- vertx-web/src/main/resources/vertx-web-js/routing_context.js
- vertx-web/src/main/resources/vertx-web/routing_context.rb
Implement the enhancement proposal to add getBodyAsJsonArray: https://github.com/vert-x3/vertx-web/issues/206
Just a simple task to get me familiar with the project so I can do something more serious.
> Add getBodyAsJsonArray to RoutingContext

- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
> #308 Fixed potential nullpointer in regexp parsing in RouteImpl

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java
fixes #306: do not crash on number format exception
> fixes #306: do not crash on number format exception

- vertx-web/src/main/generated/io/vertx/rxjava/ext/web/handler/BodyHandler.java
- vertx-web/src/main/groovy/io/vertx/groovy/ext/web/handler/BodyHandler.groovy
- vertx-web/src/main/java/io/vertx/ext/web/handler/BodyHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
- vertx-web/src/main/resources/vertx-web-js/body_handler.js
- vertx-web/src/main/resources/vertx-web/body_handler.rb
- vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java
Fix for https://github.com/vert-x3/vertx-web/issues/283.
> Issue 283: delete uploaded files after request handling ends

- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
fix #301 do not reparse already parsed variables
> fix #301 do not reparse already parsed variables

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BasicAuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/AuthHandlerTestBase.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/BasicAuthHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/RedirectAuthHandlerTest.java
- vertx-web/src/test/resources/login/loginusers.properties
> Fixes #330 (Problem with basic auth if password contains ':')

- vertx-web/src/main/java/io/vertx/ext/web/package-info.java
Set the correct format for the register/unregister list.
> Correct the register/unregister vertx.web java doc

- vertx-sockjs-service-proxy/src/test/resources/vertx-js/vertx-eventbus.js
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
@alex-inqwise please review if this what you expect?
> reroute should reset previous params to avoid old state

- vertx-web/src/main/asciidoc/enums.adoc
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
> Fixes #347: remove dead code

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/RedirectAuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/RedirectAuthHandlerTest.java
> Fixes #345: redirect respects params

- vertx-template-engines/vertx-web-templ-jade/pom.xml
- vertx-template-engines/vertx-web-templ-jade/src/main/generated/io/vertx/rxjava/ext/web/templ/JadeTemplateEngine.java
- vertx-template-engines/vertx-web-templ-jade/src/main/groovy/io/vertx/groovy/ext/web/templ/JadeTemplateEngine.groovy
- vertx-template-engines/vertx-web-templ-jade/src/main/java/io/vertx/ext/web/templ/impl/JadeTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-jade/src/test/filesystemtemplates/test-jade-template3.jade
- vertx-web/src/test/resources/somedir/test-jade-template2.jade
- vertx-web/src/test/resources/somedir/test-jade-template2.made
> Upgrade Jade to 1.2.1

- vertx-sockjs-service-proxy/src/test/generated/io/vertx/rxjava/serviceproxy/testmodel/TestConnection.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/rxjava/serviceproxy/testmodel/TestConnectionWithCloseFuture.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/rxjava/serviceproxy/testmodel/TestService.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/serviceproxy/testmodel/TestBaseImportsServiceVertxEBProxy.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/serviceproxy/testmodel/TestBaseImportsServiceVertxProxyHandler.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/serviceproxy/testmodel/TestConnectionVertxEBProxy.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/serviceproxy/testmodel/TestConnectionVertxProxyHandler.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/serviceproxy/testmodel/TestConnectionWithCloseFutureVertxEBProxy.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/serviceproxy/testmodel/TestConnectionWithCloseFutureVertxProxyHandler.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/serviceproxy/testmodel/TestServiceVertxEBProxy.java
- vertx-sockjs-service-proxy/src/test/generated/io/vertx/serviceproxy/testmodel/TestServiceVertxProxyHandler.java
- vertx-web/src/main/asciidoc/enums.adoc
- vertx-web/src/main/generated/io/vertx/rxjava/ext/web/RoutingContext.java
- vertx-web/src/main/generated/io/vertx/rxjava/ext/web/sstore/SessionStore.java
- vertx-web/src/main/groovy/io/vertx/groovy/ext/web/RoutingContext.groovy
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
- vertx-web/src/main/resources/vertx-web-js/routing_context.js
- vertx-web/src/main/resources/vertx-web/routing_context.rb
- vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
> Fixes #342: do not call twice error handler

- vertx-web/src/main/asciidoc/enums.adoc
- vertx-web/src/main/asciidoc/groovy/index.adoc
- vertx-web/src/main/asciidoc/java/index.adoc
- vertx-web/src/main/asciidoc/js/index.adoc
- vertx-web/src/main/asciidoc/ruby/index.adoc
- vertx-web/src/main/generated/io/vertx/rxjava/ext/web/RoutingContext.java
- vertx-web/src/main/generated/io/vertx/rxjava/ext/web/sstore/SessionStore.java
- vertx-web/src/main/groovy/io/vertx/groovy/ext/web/RoutingContext.groovy
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/package-info.java
- vertx-web/src/main/resources/vertx-web-js/routing_context.js
- vertx-web/src/main/resources/vertx-web/routing_context.rb
- vertx-web/src/test/java/io/vertx/ext/web/handler/RerouteTest.java
> Allow re-route in failure handler and avoid stackoverflow exception

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
> File-uploads dir not created unless dealing with uploads

- vertx-web/src/test/java/io/vertx/ext/web/handler/AuthHandlerTestBase.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/RerouteTest.java
- vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java
> clear file_uploads dir during tests

- vertx-web/src/main/asciidoc/groovy/index.adoc
- vertx-web/src/main/asciidoc/java/index.adoc
- vertx-web/src/main/asciidoc/js/index.adoc
- vertx-web/src/main/asciidoc/ruby/index.adoc
- vertx-web/src/main/generated/io/vertx/rxjava/ext/web/handler/TimeoutHandler.java
- vertx-web/src/main/groovy/io/vertx/groovy/ext/web/handler/TimeoutHandler.groovy
- vertx-web/src/main/java/io/vertx/ext/web/handler/TimeoutHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/TimeoutHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/package-info.java
- vertx-web/src/main/resources/vertx-web-js/timeout_handler.js
- vertx-web/src/main/resources/vertx-web/timeout_handler.rb
- vertx-web/src/test/java/io/vertx/ext/web/handler/TimeoutHandlerTest.java
Fixes #389 
This is a breaking change since the existing code is wrong.
> A server timeout should be 503 not a client timeout

- .editorconfig
- vertx-template-engines/vertx-web-templ-pebble/src/main/generated/io/vertx/rxjava/ext/web/templ/PebbleTemplateEngine.java
- vertx-template-engines/vertx-web-templ-pebble/src/main/groovy/io/vertx/groovy/ext/web/templ/PebbleTemplateEngine.groovy
- vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/PebbleTemplateEngine.java
- vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleVertxLoader.java
- vertx-template-engines/vertx-web-templ-pebble/src/main/resources/vertx-web-js/pebble_template_engine.js
- vertx-template-engines/vertx-web-templ-pebble/src/main/resources/vertx-web/pebble_template_engine.rb
- vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/parts/include.peb
- vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/parts/parent.peb
- vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-complex.peb
- vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java
> Implement a proper pebble loader so extension and include also works

- vertx-sockjs-service-proxy/src/main/asciidoc/groovy/index.ad
- vertx-sockjs-service-proxy/src/main/asciidoc/java/index.ad
- vertx-sockjs-service-proxy/src/main/asciidoc/js/index.ad
- vertx-sockjs-service-proxy/src/main/asciidoc/ruby/index.ad
- vertx-web/src/main/asciidoc/groovy/index.adoc
- vertx-web/src/main/asciidoc/java/index.adoc
- vertx-web/src/main/asciidoc/js/index.adoc
- vertx-web/src/main/asciidoc/ruby/index.adoc
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
> Fix #404 allow special regex chars in paths with params

- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/StaticDirectoryListHandlerTest.java
Relates to:
* #418 
* #419 
It is just defensive programming.
> Avoid NPE, and bad matches

- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerOptions.java
> Fix #414: Do not force HTTP, use current protocol

- vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
This change is to fix https://github.com/eclipse/vert.x/issues/1553
> Fix javadoc response for bodyEndHandler

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java
> Log JWT auth error, don't eat it up.

- vertx-web/src/client/vertx-eventbus.js
> Allow disabling ping message at runtime/startup

- vertx-web/src/main/asciidoc/groovy/index.adoc
- vertx-web/src/main/asciidoc/java/index.adoc
- vertx-web/src/main/asciidoc/js/index.adoc
- vertx-web/src/main/asciidoc/ruby/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/OAuth2AuthHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/package-info.java
- vertx-web/src/main/resources/vertx-web-js/o_auth2_auth_handler.js
- vertx-web/src/test/java/io/vertx/ext/web/handler/OAuth2AuthHandlerTest.java
> Fixes to OAuth2 and documented Azure AD support

- vertx-web/pom.xml
- vertx-web/src/main/java/io/vertx/ext/web/handler/DigestAuthHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/DigestAuthHandlerTest.java
- vertx-web/src/test/resources/.htdigest
> implement htdigest support auth handler

- vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleVertxLoader.java
- vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/parts/parent2.peb
- vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-template4.peb
- vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java
Pebble Template produce ArrayIndexOutOfBound when handles template with size more than 4096 character.
- Create test to reproduce bug
- Fix bug on PebbleVertxLoader
> Fix Bug on PebbleVertxLoader when handles big template file

- vertx-web/src/main/java/io/vertx/ext/web/handler/StaticHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
> add default content encoding setter

- vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/impl/ThymeleafTemplateEngineImpl.java
> Fix setTemplateMode

- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
- vertx-web-common/src/main/java/io/vertx/ext/web/codec/BodyCodec.java
- vertx-web-common/src/main/java/io/vertx/ext/web/codec/impl/BodyCodecImpl.java
We only had a JsonObject body codec
> Web Client: add a JsonArray body codec

- vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpResponse.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpResponseImpl.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
like existing `HttpResponse.bodyAsJsonObject()`
> HttpResponse.bodyAsJsonArray() method

- vertx-web/pom.xml
- vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/ClusteredSessionStoreImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/SessionImpl.java
> Fix de-serialization on sessions

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FaviconHandlerImpl.java
Signed-off-by: Valeri Nistor <nistor.valeri@gmail.com>
> Fix FaviconHandlerImpl java doc

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java
Added support for HttpVersion.HTTP_2 in LoggerHandlerImpl.
> HttpVersion.HTTP_2 support in LoggerHandlerImpl.

- vertx-template-engines/vertx-web-templ-freemarker/src/test/resources/freemarker_javascript_template_test.js
- vertx-web/src/test/java/io/vertx/ext/web/WebTestBase.java
- vertx-web/src/test/java/io/vertx/ext/web/templ/TemplateTest.java
Signed-off-by: alexlehm <alexlehm@gmail.com>
> fix two more tests depending on unix lineendings

- vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/impl/FreeMarkerTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/impl/HandlebarsTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-handlebars/src/test/filesystemtemplates/sub/test-handlebars-template9.hbs
- vertx-template-engines/vertx-web-templ-handlebars/src/test/filesystemtemplates/test-handlebars-template7A.hbs
- vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateTest.java
- vertx-template-engines/vertx-web-templ-jade/src/main/java/io/vertx/ext/web/templ/impl/JadeTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-mvel/src/main/java/io/vertx/ext/web/templ/impl/MVELTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/impl/ThymeleafTemplateEngineImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/TemplateHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/templ/TemplateEngine.java
- vertx-web/src/test/java/io/vertx/ext/web/templ/TemplateTest.java
- vertx-web/src/test/java/io/vertx/ext/web/templ/impl/TemplateHandlerImplTest.java
Better fix for #514 / replaces #580 .
> TemplateEngine render refactor

- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
- vertx-web/src/main/java/io/vertx/ext/web/package-info.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/RerouteTest.java
> Reroute should only take the path as per doc

- vertx-web-client/src/main/asciidoc/groovy/index.adoc
- vertx-web-client/src/main/asciidoc/java/index.adoc
- vertx-web-client/src/main/asciidoc/js/index.adoc
- vertx-web-client/src/main/asciidoc/kotlin/index.adoc
- vertx-web-client/src/main/asciidoc/ruby/index.adoc
- vertx-web-client/src/main/java/examples/WebClientExamples.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/package-info.java
> WebClient doc: show the webclient request.copy method in action

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
> Add missing extra args

- vertx-web/src/main/java/io/vertx/ext/web/package-info.java
> Fix reconnection documentation for EventBus bridge

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ValidationTest.java
- vertx-web-api-contract/src/test/resources/swaggers/validation_test.yaml
- see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types
> fix handling of specified data types and formats

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java
Extends the work done by @zella
> Fixes #766

- vertx-web-client/src/main/java/examples/RxWebClientExamples.java
- vertx-web-client/src/main/java/examples/WebClientExamples.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
> Virtual host property for a WebClient request - fixes #805

- vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
https://github.com/vert-x3/issues/issues/340
Signed-off-by: Michael Pogrebinsky <smichpog2@gmail.com>
> Add getters in HttpRequest for methd, port, host, virtualHost, uri, ssl, timeout and followRedirects

- vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
Reverts vert-x3/vertx-web#867
because it breaks the compilation
> Revert "Add getters in HttpRequest for methd, port, host, virtualHost, uri, ssl, timeout and followRedirects"

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3PathResolver.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/resources/swaggers/router_factory_test.yaml
> Fixed #871

- vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
When using cookies for sessions, if there is a error in the route, this cookies should not be invalidated.
> Fix behavior for cookies on error

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/resources/swaggers/upload_test.yaml
Fix for #860
Sets custom body handler and makes sure it’s triggered
> Fix #860 allow setting customised BodyHandler

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/impl/RequestParametersImpl.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/BaseValidationHandler.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ValidationTest.java
> Fixed #850 with null check on setters of RequestParametersImpl

- vertx-web-client/src/main/asciidoc/index.adoc
- vertx-web-client/src/main/java/examples/WebClientExamples.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/FormDataPart.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/AttributeFormDataPart.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/BodyAttributeFormDataPart.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/FileUploadFormDataPart.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
See the https://github.com/vert-x3/vertx-web/issues/862.
I'm not sure whether this is the API we want eventually, so we need to discuss about this. 
Documentation and example is not ready for now, it will be added some time later.
> Add support for Send multipart/form-data with file upload - fixes #862

- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/contract/RouterFactoryOptionsConverter.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/RequestParameter.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/RequestParameters.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/impl/RequestParameterImpl.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/impl/RequestParametersImpl.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/RequestParametersTest.java
> Implemented Json conversion for RequestParameter/RequestParameters

- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/contract/RouterFactoryOptionsConverter.java
- vertx-web-client/src/main/asciidoc/dataobjects.adoc
- vertx-web-client/src/main/generated/io/vertx/ext/web/client/WebClientOptionsConverter.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/BodyHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java
https://github.com/vert-x3/issues/issues/362
Signed-off-by: Michael Pogrebinsky <smichpog2@gmail.com>
> Allocate the body handler buffer with the body size when the content-length header is set 

- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/contract/RouterFactoryOptionsConverter.java
- vertx-web-client/src/main/generated/io/vertx/ext/web/client/WebClientOptionsConverter.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClientOptions.java
- vertx-web/src/test/java/io/vertx/ext/web/WebTestWithWebClientBase.java
> Revert "Provide property propagation for 2376"

- vertx-web/src/test/java/io/vertx/ext/web/WebTestBase.java
Remove unused java.net.MalformedURLException
> Remove unused import

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/resources/swaggers/global_security_test.yaml
> Fixed #936 bad global security handling

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
> Adds only not existing cache control header values.

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/Route.java
> Fixed route.handler and route.failureHandler docs

- vertx-web/src/main/java/io/vertx/ext/web/handler/AuthHandler.java
> Typo AuthoriSation -> AuthoriZation

- vertx-web/pom.xml
Please add licensing information to pom.xml so license-check-maven-plugin can verify licensing.
> Add licensing information to pom.xml

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/SecurityHandlersStore.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
> Allow multiple security handlers in OpenAPI3RouterFactory

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ValidationException.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/JsonTypeValidator.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ValidationTest.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/WebTestValidationBase.java
- vertx-web/src/test/java/io/vertx/ext/web/WebTestWithWebClientBase.java
> Added more verbose error reporting inside validation exception

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/OAuth2AuthHandlerTest.java
Fixes https://github.com/vert-x3/vertx-auth/issues/242
> Allow Bearer-Only mode for OAuth2

- vertx-web/src/test/java/io/vertx/ext/web/handler/OAuth2AuthHandlerTest.java
Depends on: https://github.com/vert-x3/vertx-auth/pull/243
> Verify https://github.com/vert-x3/vertx-auth/pull/243

- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
Use internal web server instead of reading specs from the web.
On Travis, sometimes the test fails because it takes too long before the latch is updated.
> Fixed intermittent test failure in failLoadSpecFromURL

- vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java
> Adds cookie path to session handler. 

- vertx-web-client/src/test/java/io/vertx/ext/web/client/InterceptorTest.java
Hi @vietj - this PR adds a test for intercepting a piped response, highlighting the feature we needed that started the (now closed) original interceptor PR which has been replaced by your interceptor branch work. cheers
> Add test for intercepting piped BodyCodec

- vertx-web-api-contract/src/main/asciidoc/dataobjects.adoc
- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/OperationRequestConverter.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/OperationRequest.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/impl/RouteToServiceProxyHandler.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/param_extraction/HandlerParamsTest.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/OpenAPI3ServiceProxiesTest.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/TestService.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/TestServiceImpl.java
- vertx-web-api-service/src/test/resources/swaggers/service_proxy_test.yaml
Implemented user serialization and created an entrypoint to inject an extra payload
> OperationRequest improvements

- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/CookieStoreImpl.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/SessionAwareWebClientTest.java
Signed-off-by: tnolli <tommaso.nolli@gmail.com>
> Fixed NPE in CookieStoreImpl

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenApi3Utils.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/BaseValidationHandler.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ValidationTest.java
- vertx-web-api-contract/src/test/resources/swaggers/validation_test.yaml
Fixes #1066 enabling additionalProperties params both in query and cookie
> Fixes #1066

- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerOptions.java
new sockjs library url, see issue #1095
> change sockjs library url

- vertx-web/src/client/vertx-eventbus.js
- vertx-web/src/main/asciidoc/index.adoc
Added a default event handler for those messages that don't have an address (#985).
> fix for #985

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ParametersUnitTest.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ValidationTest.java
- vertx-web-api-contract/src/test/resources/swaggers/shared_request_body.yaml
Fixes #861 in 3.6.x (https://github.com/vert-x3/vertx-web/issues/1099)
> Porting fix #861

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/BaseValidationHandler.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/resources/swaggers/router_factory_test.yaml
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
> Solves issue #1105

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3PathResolver.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3PathResolverTest.java
- vertx-web-api-contract/src/test/resources/swaggers/path_resolver_test.yaml
> Solves regression from 3.5 semicolon in path

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/StringTypeValidator.java
> Added more comprehensive error messages for StringTypeValidator

- vertx-web-api-contract/pom.xml
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3SchemasTest.java
- vertx-web-api-contract/src/test/resources/swaggers/schemas_test_spec.yaml
- vertx-web-api-contract/src/test/resources/swaggers/test_json/schemas_test/testLocalRelativeRef_fail.json
- vertx-web-api-contract/src/test/resources/swaggers/test_json/schemas_test/testLocalRelativeRef_ok.json
Added test for localRelativeRef (still not working inside jar)
> Updated swagger-parser to 2.0.8

- vertx-template-engines/vertx-web-templ-freemarker/src/test/java/io/vertx/ext/web/templ/FreeMarkerTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-freemarker/src/test/java/io/vertx/ext/web/templ/FreeMarkerTemplateTest.java
- vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateTest.java
- vertx-template-engines/vertx-web-templ-jade/src/test/java/io/vertx/ext/web/templ/JadeTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-jade/src/test/java/io/vertx/ext/web/templ/JadeTemplateTest.java
- vertx-template-engines/vertx-web-templ-mvel/src/test/java/io/vertx/ext/web/templ/MVELTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-mvel/src/test/java/io/vertx/ext/web/templ/MVELTemplateTest.java
- vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java
- vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/thymeleaf/impl/ThymeleafTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-thymeleaf/src/test/java/io/vertx/ext/web/templ/ThymeleafTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-thymeleaf/src/test/java/io/vertx/ext/web/templ/ThymeleafTemplateTest.java
- vertx-web-common/src/main/java/io/vertx/ext/web/common/WebEnvironment.java
- vertx-web-common/src/main/java/io/vertx/ext/web/common/template/CachingTemplateEngine.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/ErrorHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/StaticHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/package-info.java
- vertx-web/src/main/java/io/vertx/ext/web/templ/CachingTemplateEngine.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/ErrorHandlerTest.java
This PR replaces https://github.com/vert-x3/vertx-web/pull/840 which went wrong during a rebase...
> Replacing old branch as rebase went wrong

- vertx-web-api-contract/src/main/asciidoc/dataobjects.adoc
- vertx-web-api-contract/src/main/asciidoc/index.adoc
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/resources/swaggers/router_factory_test.yaml
Fixing issue #1167 . Now it correctly writes 405/501 depending on if user has configured or not handlers for the same path 
> Not implemented no more mounted when method is not allowed

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
Signed-off-by: torq <victorqrsilva@gmail.com>
> Fixes #1160

- vertx-web/src/main/asciidoc/index.adoc
> Documentation for the Rocker template engine

- vertx-web-api-contract/pom.xml
Swagger-parser 2.0.8 -> 2.0.11
Json schema validator 0.1.23 -> 1.0.4
Dep tree diff:
```
13c13
< [INFO] +- com.networknt:json-schema-validator:jar:0.1.23:compile
---
> [INFO] +- com.networknt:json-schema-validator:jar:1.0.4:compile
17,23c17,23
< [INFO] +- io.swagger.parser.v3:swagger-parser:jar:2.0.8:compile
< [INFO] |  +- io.swagger.parser.v3:swagger-parser-v2-converter:jar:2.0.8:compile
< [INFO] |  |  +- io.swagger:swagger-parser:jar:1.0.41:compile
< [INFO] |  |  |  \- io.swagger:swagger-core:jar:1.5.21:compile
< [INFO] |  |  |     \- io.swagger:swagger-models:jar:1.5.21:compile
< [INFO] |  |  |        \- io.swagger:swagger-annotations:jar:1.5.21:compile
< [INFO] |  |  +- io.swagger:swagger-compat-spec-parser:jar:1.0.41:compile
---
> [INFO] +- …
```
> Updated swagger-parser & json-schema-validator

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/impl/RouteToEBServiceHandler.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/BinaryTestService.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/BinaryTestServiceImpl.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/OpenAPI3ServiceProxiesTest.java
- vertx-web-api-service/src/test/resources/swaggers/service_proxy_test.yaml
> Fixed binary data in web api service

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ValidationException.java
> ValidationException now overrides getMessage

- vertx-web/src/main/asciidoc/index.adoc
> Added documentation for JWT auth

- vertx-web-graphql/src/main/asciidoc/dataobjects.adoc
- vertx-web-graphql/src/main/asciidoc/index.adoc
- vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptionsConverter.java
- vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphiQLOptionsConverter.java
- vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandler.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptions.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphiQLOptions.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
- vertx-web-graphql/src/main/resources/io/vertx/ext/web/handler/graphql/graphiql.html
> Expose GraphiQL for development

- vertx-web-client/src/main/asciidoc/index.adoc
> Add warning to documentation about not reusing WebClient instance

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BaseTransport.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CORSHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSCORSTest.java
Relaxed allowCredentials() in CORSHandler
Fixes #1170
> Solved conflicts between SockJS and CORS handlers

- vertx-web/src/client/vertx-eventbus.js
Related to https://travis-ci.org/vert-x3/vertx-sockjs-service-proxy/jobs/499299770
> Fix wrong handling of error messages vertx-eventbus.js

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
Fixes https://github.com/vert-x3/vertx-web/issues/1203
> CSRFHandler now safely calls Mac.doFinal

- vertx-web/src/main/java/io/vertx/ext/web/ParsedHeaderValues.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/ParsableHeaderValuesContainer.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
> Fixed getAcceptableContentType()

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
> Fixes issue #1123

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CustomAuthHandlerTest.java
> Now AuthHandlerImpl correctly manages HttpStatusException

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/ArrayTypeValidator.java
- vertx-web-api-service/src/main/java/io/vertx/ext/web/api/generator/impl/model/WebApiProxyModel.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
Small fixes to correct warnings reported by the Eclipse IDE on potential NullPointerException
> vertx-web 3.7 - fix potentials null pointer exception

- vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
add a method named putHeaders in HttpRequest can add headers in batches
fix https://github.com/vert-x3/vertx-web/issues/1114
> fix:issues/1114

- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
> Removed unnecessary encoding of query params in web client

- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/HTTPRequestValidationTest.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/WebTestValidationBase.java
> Moved file-uploads directory to target

- vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Replaces https://github.com/vert-x3/vertx-web/pull/1029
> Lazy decoding of query parameters in RoutingContext

- vertx-web/src/main/asciidoc/index.adoc
> Document development mode

- vertx-web/src/main/java/io/vertx/ext/web/Route.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
> Added getHttpMethods to Route interface

- vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
> Updated doc of RoutingContext#queryParam

- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/OperationRequestConverter.java
- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/OperationResponseConverter.java
- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/contract/RouterFactoryOptionsConverter.java
- vertx-web-api-service/src/main/java/io/vertx/ext/web/api/generator/impl/WebApiProxyHandlerGen.java
- vertx-web-client/src/main/generated/io/vertx/ext/web/client/WebClientOptionsConverter.java
- vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptionsConverter.java
- vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphiQLOptionsConverter.java
> Regenerated all converters

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/io/vertx/ext/web/handler/LoggerHandler.java
> Improved documentation for LoggerHandler

- vertx-web-client/src/main/asciidoc/index.adoc
> Added docs for #1198

- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java
> Adds REGISTERED hook to event bus sockjs bridge

- vertx-template-engines/vertx-web-templ-freemarker/pom.xml
- vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/FreeMarkerTemplateEngine.java
- vertx-template-engines/vertx-web-templ-handlebars/pom.xml
- vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/HandlebarsTemplateEngine.java
- vertx-template-engines/vertx-web-templ-jade/pom.xml
- vertx-template-engines/vertx-web-templ-jade/src/main/java/io/vertx/ext/web/templ/JadeTemplateEngine.java
- vertx-template-engines/vertx-web-templ-mvel/pom.xml
- vertx-template-engines/vertx-web-templ-mvel/src/main/java/io/vertx/ext/web/templ/MVELTemplateEngine.java
- vertx-template-engines/vertx-web-templ-pebble/pom.xml
- vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/PebbleTemplateEngine.java
- vertx-template-engines/vertx-web-templ-rocker/pom.xml
- vertx-template-engines/vertx-web-templ-rocker/src/main/java/io/vertx/ext/web/templ/RockerTemplateEngine.java
- vertx-template-engines/vertx-web-templ-thymeleaf/pom.xml
- vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/ThymeleafTemplateEngine.java
> Remove deprecated template engine API

- vertx-template-engines/vertx-web-templ-thymeleaf/pom.xml
This solves the stack conflicts
> Updated thymeleaf version to 3.0.11.RELASE

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
Addressed documentation issue for `Route#order` https://github.com/vert-x3/vertx-web/issues/824
> Route order fix

- vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClient.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
> Implemented support for custom HTTP methods in Web Client

- vertx-web-client/src/test/java/io/vertx/ext/web/client/jackson/WineAndCheese.java
if you redefine the equals() method, it is strongly recommended that you also redefine the hashCode() method.
> WineAndCheese: add hashCode() after equals()

- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLQuery.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GetRequestsTest.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GraphQLRequest.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/PostRequestsTest.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/impl/GraphQLInputDeserializerTest.java
> GraphQL handler operationName support missing

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/DigestAuthHandlerTest.java
> digestauth: fix nonces cleanup

- .travis.yml
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloTestsServer.java
- vertx-web-graphql/tests/.gitignore
- vertx-web-graphql/tests/apollo/.babelrc
- vertx-web-graphql/tests/apollo/apollo.test.js
- vertx-web-graphql/tests/apollo/package-lock.json
- vertx-web-graphql/tests/apollo/package.json
> Jest tests for Apollo http and batch-http links

- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/PostRequestsTest.java
Suggested fix for https://github.com/vert-x3/vertx-web/issues/1348
> Add support for content type that contains charset

- vertx-template-engines/pom.xml
- vertx-template-engines/vertx-web-templ-httl/pom.xml
- vertx-template-engines/vertx-web-templ-httl/src/main/java/io/vertx/ext/web/templ/httl/HTTLTemplateEngine.java
- vertx-template-engines/vertx-web-templ-httl/src/main/java/io/vertx/ext/web/templ/httl/impl/HTTLTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-httl/src/main/java/io/vertx/ext/web/templ/httl/package-info.java
- vertx-template-engines/vertx-web-templ-httl/src/test/java/io/vertx/ext/web/templ/HTTLTemplateEngineTest.java
- vertx-template-engines/vertx-web-templ-httl/src/test/resources/somedir/test-httl-template1.httl
- vertx-template-engines/vertx-web-templ-httl/src/test/resources/somedir/test-httl-template1.mvl
- vertx-web/src/main/asciidoc/index.adoc
> Adds support fot HTTL template engine

- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/MultipartFormUpload.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/MultipartFormUploadTest.java
> MultipartFormUpload NPE when stream is paused and encoder returns last chunk

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
> Add missing remove from store

- vertx-web-graphql/src/main/asciidoc/dataobjects.adoc
- vertx-web-graphql/src/main/asciidoc/index.adoc
- vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptionsConverter.java
- vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptions.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/UploadScalar.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloTestsServer.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/MultipartRequestTest.java
- vertx-web-graphql/src/test/resources/batchUpload.txt
- vertx-web-graphql/src/test/resources/emptyQuery.graphqls
- vertx-web-graphql/src/test/resources/multipleUpload.txt
- vertx-web-graphql/src/test/resources/singleUpload.txt
- vertx-web-graphql/src/test/resources/upload.graphqls
- vertx-web-graphql/tests/apollo/apollo.test.js
- vertx-web-graphql/tests/apollo/package-lock.json
- vertx-web-graphql/tests/apollo/package.json
Checking if it is multipart document extracting the data from multipart form field, parsing it and assigning the multipart files to the correct graphql variables.
> [GraphQL] Changes to support inline upload File

- vertx-web/pom.xml
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/JsonCodec.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSession.java
- vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextDatabindTest.java
- vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java
- vertx-web/src/test/java/io/vertx/ext/web/it/RoutingContextDatabindTest.java
This prevents to write code that depends on the specific codec
> Put Jackson databind in Vert.x Web test scope

- vertx-web/src/main/java/io/vertx/ext/web/handler/AuthHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/AuthorizationHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthorizationHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/MultiAuthorizationHandlerTest.java
fixed #1467 
@pmlopes could you please review ?
> fixed #1467 - Update AuthHandler to account for the new AuthorizationProvider

- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphiQLHandlerImpl.java
- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/io/vertx/ext/web/Route.java
- vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/TemplateHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/WebAuthnHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
- vertx-web/src/test/java/io/vertx/ext/web/SubRouterTest.java
- vertx-web/src/test/java/io/vertx/ext/web/templ/handlebars/impl/TemplateHandlerImplTest.java
1. `RoutingContext#normalisedPath` => `normalizedPath`;
2. `Route#useNormalisedPath` => `useNormalizedPath`.
> Normalised => Normalized

- pom.xml
- vertx-web-session-stores/pom.xml
- vertx-web-session-stores/vertx-web-sstore-redis/pom.xml
- vertx-web-session-stores/vertx-web-sstore-redis/src/main/java/io/vertx/ext/web/sstore/redis/RedisSessionStore.java
- vertx-web-session-stores/vertx-web-sstore-redis/src/main/java/io/vertx/ext/web/sstore/redis/impl/RedisSessionStoreImpl.java
- vertx-web-session-stores/vertx-web-sstore-redis/src/main/resources/META-INF/services/io.vertx.ext.web.sstore.SessionStore
- vertx-web-session-stores/vertx-web-sstore-redis/src/test/java/io/vertx/ext/web/sstore/redis/RedisSessionStoreTest.java
Implement #890 based on 4.0 snapshot
Signed-off-by: Rémy Noël <>
> Add redis session store

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java
> return 400 when there are decode exceptions

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenApi3Utils.java
- vertx-web-api-contract/src/test/resources/swaggers/validation_test.yaml
> Fixed #1486

- vertx-web-api-service/src/main/java/io/vertx/ext/web/api/generator/impl/WebApiProxyHandlerGen.java
- vertx-web-api-service/src/main/java/io/vertx/ext/web/api/generator/impl/model/WebApiProxyMethodInfo.java
- vertx-web-api-service/src/main/java/io/vertx/ext/web/api/generator/impl/model/WebApiProxyModel.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/generator/WebApiProxyTest.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/generator/models/ValidWebApiProxyFuture.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/param_extraction/HandlerParamsTest.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/param_extraction/ParamsTestService.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/param_extraction/ParamsTestServiceImpl.java
Depends on https://github.com/vert-x3/vertx-service-proxy/pull/109
> Support Future in vertx-web-api-service

- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
> SameSite policy for session handler

- vertx-web-api-service/src/main/java/io/vertx/ext/web/api/service/generator/WebApiProxyHandlerGen.java
- vertx-web-api-service/src/main/java/io/vertx/ext/web/api/service/generator/model/WebApiProxyModel.java
> Changes for https://github.com/vert-x3/vertx-codegen/issues/288

- pom.xml
- vertx-web-api-service/pom.xml
- vertx-web-api-service/src/main/java/io/vertx/ext/web/api/service/generator/WebApiProxyHandlerGen.java
- vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/RouteToEBServiceHandlerTest.java
- vertx-web-validation/pom.xml
- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/ValidationHandlerImpl.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/RequestParametersTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/ValidationHandlerPredicatesIntegrationTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/ValidationHandlerProcessorsIntegrationTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/FormBodyProcessorImplTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/JsonBodyProcessorImplTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/ParameterProcessorIntegrationTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/ParameterProcessorUnitTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/TextPlainBodyProcessorTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/testutils/TestRequest.java
> Enabled web-validation and web-api-service

- vertx-web-api-contract/pom.xml
> Backport #1540 to 3.9

- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSHandlerImpl.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloWSHandlerTest.java
- vertx-web-graphql/src/test/resources/counter.graphqls
> Cancel GraphQL subscriptions when connection is closed abruptly

- vertx-web/src/main/asciidoc/dataobjects.adoc
- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/generated/io/vertx/ext/web/handler/sockjs/SockJSBridgeOptionsConverter.java
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSBridgeOptions.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerTest.java
Fixes #1499
Avoid duplication across modules and ensures consistent behavior across bridges.
> Fixes #1499: Avoid duplicate code and consistent behavior

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/resources/swaggers/operation_without_operationId.yaml
Motivation:
Contribution in order to fix the issue #1580
> Fix for issue #1580

- vertx-web-validation/src/main/asciidoc/index.adoc
- vertx-web-validation/src/main/java/examples/WebValidationExamples.java
Looks like this thing breaks the lang integration
> Web validation examples class name

- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/RequestPredicateResult.java
- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/RequestPredicateResultImpl.java
> Switched RequestPredicateResult to @VertxGen

- vertx-web/src/main/java/io/vertx/ext/web/impl/HttpServerRequestWrapper.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/ServerWebSocketWrapper.java
- vertx-web/src/test/java/io/vertx/ext/web/ForwardedTest.java
Fixes #1585
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>
> Parsed forward headers are not passed down to ServerWebSocket

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3PathResolver.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenApi3Utils.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/resources/swaggers/scenario_with_array_parameter.yaml
Motivation:
A fix for the issue #1591
> Fix for #1591

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3PathResolver.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenApi3Utils.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
- vertx-web-api-contract/src/test/resources/swaggers/scenario_with_array_parameter.yaml
Backport #1591 to 3.9
(cherry picked from commit 14ee1d4683aae6f40446406be24b5076c06df1c3)
> Fix for #1591 (#1592)

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/AuthenticationHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/ChainAuthHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BasicAuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ChainAuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/ChainAuthHandlerAndTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/ChainAuthMixHandlerTest.java
This pull request adds support to perform all and any operations to a chain auth as needed for openapi.
> initial draft at any/all

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSProtocolTest.java
Fixes #1576
Adds a flush operation to the handler.
> Adds a flush operation to the session handler

- vertx-web-openapi/src/main/resources/META-INF/MANIFEST.MF
> Manifest for web openapi

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CookielessSessionHandlerTestBase.java
Fixes #1554
Implements cookieless support for session handler
> Implement cookieless sessions

- vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java
- vertx-web/src/test/java/io/vertx/ext/web/sstore/ClusteredSessionHandlerTest.java
This follows-up on the introduction of a flushing method on the SessionStore object.
Thanks to this new method, it is possible to remove some Thread#sleep calls that lead to intermittent failures on CI (especially with clustered session implementations).
> More reliable session tests with session flushing

- vertx-web-api-service/src/main/generated/io/vertx/ext/web/api/service/ServiceRequestConverter.java
- vertx-web-api-service/src/main/generated/io/vertx/ext/web/api/service/ServiceResponseConverter.java
- vertx-web-openapi/pom.xml
- vertx-web-openapi/src/main/asciidoc/dataobjects.adoc
- vertx-web-openapi/src/main/asciidoc/index.adoc
- vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/OpenAPILoaderOptionsConverter.java
- vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/RouterFactoryOptionsConverter.java
> Fixed docs of vertx-web-openapi

- vertx-web/src/main/java/io/vertx/ext/web/impl/ServerWebSocketWrapper.java
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>
> ServerWebSocketWrapper should return wrapper instead of delegate.

- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSConnectionHandler.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloWSHandlerTest.java
> ApolloWSHandler: support messages sent in multiple frames

- vertx-web-api-service/src/main/generated/io/vertx/ext/web/api/service/ServiceRequestConverter.java
- vertx-web-api-service/src/main/generated/io/vertx/ext/web/api/service/ServiceResponseConverter.java
- vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/OpenAPILoaderOptionsConverter.java
- vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/RouterFactoryOptionsConverter.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/AuthenticationHandlersStore.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterFactorySecurityTest.java
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/AuthenticationHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/JWTAuthHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BasicAuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ChainAuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FormLoginHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/HTTPAuthorizationHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/HttpStatusException.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/MethodOverrideHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/RedirectAuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/ChainAuthMixHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CustomAuthHandlerTest.java
Motivation:
Follow up from type authentication
> Added typed authn

- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterFactoryIntegrationTest.java
Motivation:
A fix for the issue #1642 .
> fix for issue #1642

- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Motivation:
Fixes: #1647 into `3.9` branch
This is the cherry-pick from master PR: https://github.com/vert-x3/vertx-web/pull/1651 to `3.9` branch.
Conformance:
> [Branch: 3.9] [Issue-1647] Content-Type-based Routing not working properly

- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3MultipleFilesValidationTest.java
- vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ValidationTest.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GraphQLTestBase.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/CorsHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/BridgeEvent.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BaseTransport.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextInternal.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CORSHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSCORSTest.java
- vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java
> Fix for discussion

- vertx-web-api-contract/src/main/asciidoc/index.adoc
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/OperationRequest.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/OperationResponse.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/RequestParameter.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/RequestParameters.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/HTTPOperationRequestValidationHandler.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactory.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryException.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RequestValidationHandler.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/package-info.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ContainerDeserializer.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ContainerSerializationStyle.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/CustomValidator.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/HTTPRequestValidationHandler.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ParameterLocation.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ParameterType.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ParameterTypeValidator.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ParameterValidationRule.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/SpecFeatureNotSupportedException.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ValidationException.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ValidationHandler.java
> Marked all public interfaces of vertx-web-api-contract as deprecated

- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3Utils.java
> Updated hardcoded OpenAPI 3 Json Schema

- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterFactory.java
> Futurized RouterFactory.create

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthorizationHandlerImpl.java
Rename method `getAuhorizationContext` to `getAuthorizationContext`
> Fix private method typo - getAuhorizationContext

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ErrorHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
- vertx-web/src/test/java/io/vertx/ext/web/SubRouterTest.java
> Fixes #1685

- vertx-web-openapi/src/main/asciidoc/dataobjects.adoc
- vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/RouterFactoryOptionsConverter.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterFactoryOptions.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/Route.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/HttpServerRequestWrapper.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
fixes #1431
Companion PRs:
* required: https://github.com/eclipse-vertx/vert.x/pull/3532
* https://github.com/vert-x3/vertx-micrometer-metrics/pull/111
* https://github.com/vert-x3/vertx-dropwizard-metrics/pull/101
> Add names for routes, report names to HttpServerRequest upon match (#1431)

- vertx-template-engines/vertx-web-templ-jade/pom.xml
- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/HttpServerRequestWrapper.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/RerouteTest.java
A different attempt to solve #1687
> Wrap params

- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3Utils.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterFactoryApiServiceIntegrationTest.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterFactoryIntegrationTest.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/impl/OpenAPI3UtilsTest.java
- vertx-web-openapi/src/test/resources/specs/petstore.yaml
> Fixed multipart problem with both normal and upload fields

- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/OperationRequestConverter.java
- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/OperationResponseConverter.java
- vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/contract/RouterFactoryOptionsConverter.java
- vertx-web-api-service/src/main/generated/io/vertx/ext/web/api/service/ServiceRequestConverter.java
- vertx-web-api-service/src/main/generated/io/vertx/ext/web/api/service/ServiceResponseConverter.java
- vertx-web-client/src/main/generated/io/vertx/ext/web/client/WebClientOptionsConverter.java
- vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/ApolloWSOptionsConverter.java
- vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptionsConverter.java
- vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphiQLHandlerOptionsConverter.java
- vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/OpenAPILoaderOptionsConverter.java
- vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/RouterFactoryOptionsConverter.java
- vertx-web/src/main/generated/io/vertx/ext/web/Http2PushMappingConverter.java
- vertx-web/src/main/generated/io/vertx/ext/web/handler/sockjs/SockJSBridgeOptionsConverter.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/OAuth2AuthHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/OAuth2AuthHandlerTest.java
Motivation:
https://groups.google.com/g/vertx/c/alyyrKSYFIk
> Implement OAuth2/OIDC PKCE

- vertx-web-openapi/src/main/java/examples/OpenAPI3Examples.java
> Futurized openapi samples

- vertx-web-api-contract/pom.xml
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.java
> Bump web api contract deps

- vertx-web-api-contract/pom.xml
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.java
See #1708
(cherry picked from commit 4f8a5283e9dfe7c0240927fa73576d88a2322d17)
> Backport #1708

- vertx-web/src/main/java/io/vertx/ext/web/handler/AuthenticationHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FormLoginHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/RedirectAuthHandlerTest.java
Motivation:
Fixes #1497 
Conformance:
This PR extends `FormLoginHandlerImpl` to `AuthenticationHandlerImpl` to be able to use the facilities to process the failures.
> [ISSUE-1497] A FormLoginHandler that allows custom failures like AuthenticationHandlerImpl

- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/ErrorHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/FaviconHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ErrorHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FaviconHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/UserHolder.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
- vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/SharedDataSessionImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/ErrorHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/FaviconHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSWriteHandlerTestServer.java
- vertx-web/src/test/java/io/vertx/ext/web/templ/TemplateTest.java
Motivation:
To ensure that File Access is consistent, all read operations are happening using vertx filesystem.
> Always read resources with FS

- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
- vertx-web/src/test/java/io/vertx/ext/web/SubRouterTest.java
> Fix issue with sub routers and /

- vertx-web-openapi/src/main/asciidoc/dataobjects.adoc
- vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/RouterFactoryOptionsConverter.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterFactoryOptions.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/ContractEndpointHandler.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3RouterFactoryImpl.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterFactoryIntegrationTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/testutils/TestRequest.java
> Implement the openapi endpoint

- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
> Fix RequestOptions processing in WebClientBase

- vertx-template-engines/pom.xml
- vertx-template-engines/vertx-web-templ-rythm/pom.xml
- vertx-template-engines/vertx-web-templ-rythm/src/main/java/io.vertx.ext.web.templ.rythm/RythmTemplateEngine.java
- vertx-template-engines/vertx-web-templ-rythm/src/main/java/io.vertx.ext.web.templ.rythm/impl/RythmTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-rythm/src/main/java/io.vertx.ext.web.templ.rythm/package-info.java
- vertx-template-engines/vertx-web-templ-rythm/src/test/filesystemtemplates/test-rythm-template.html
- vertx-template-engines/vertx-web-templ-rythm/src/test/java/io.vertx.ext.web.templ/RythmTemplateTest.java
- vertx-template-engines/vertx-web-templ-rythm/src/test/resources/somedir/test-rythm-template2.html
Add rythm engine, what functionality can I also add? @pmlopes
> add rythm template engine #967

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BasicAuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/BasicAuthHandlerTest.java
#1753 
Motivation:
change validation of incorrect basic auth to respond with 400 malformed request
Conformance:
Signed-off-by: lucas persson <luben93@gmail.com>
> change validation of incorrect basic auth to respond with 400 malformed request

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/Route.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Motivation:
This PR is getting #1287 up to date with the current 4.0.0 API
It allows to write concise and user readable handlers that can chain futures (if needed) without the error handling boilerplate.
> Follow up on #1287

- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextInternal.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
- vertx-web/src/test/java/io/vertx/ext/web/SubRouterTest.java
Motivation:
We need this bug fix in v3.9.x
As suggested by @pmlopes [here](https://github.com/vert-x3/vertx-web/issues/1501#issuecomment-717981073), we back ported the fix
Conformance:
> Backport #1501

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/CSPHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSPHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CSPHandlerTest.java
Motivation:
One extra layer of security for web applications.
> Enable CSP support, backport from Yoke

- vertx-web/src/main/asciidoc/index.adoc
Doc still refers to it as Future
> BridgeEvent is now a Promise

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenApi3Utils.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/JsonTypeValidator.java
- vertx-web-api-contract/src/test/resources/swaggers/schemas_test_spec.yaml
> Fix example keyword error

- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenApi3Utils.java
- vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/JsonTypeValidator.java
- vertx-web-api-contract/src/test/resources/swaggers/schemas_test_spec.yaml
> [3.9] Backport 1769

- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/body/JsonBodyProcessorImpl.java
- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/body/TextPlainBodyProcessorImpl.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/JsonBodyProcessorImplTest.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/TextPlainBodyProcessorTest.java
> Null check on body in text and json body processor

- .github/workflows/ci.yml
- vertx-template-engines/vertx-web-templ-freemarker/src/test/java/io/vertx/ext/web/templ/FreeMarkerTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-freemarker/src/test/java/io/vertx/ext/web/templ/FreeMarkerTemplateTest.java
- vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateTest.java
- vertx-template-engines/vertx-web-templ-httl/src/test/java/io/vertx/ext/web/templ/HTTLTemplateEngineTest.java
- vertx-template-engines/vertx-web-templ-jade/src/test/java/io/vertx/ext/web/templ/JadeTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-jade/src/test/java/io/vertx/ext/web/templ/JadeTemplateTest.java
- vertx-template-engines/vertx-web-templ-mvel/src/test/java/io/vertx/ext/web/templ/MVELTemplateTest.java
- vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java
- vertx-template-engines/vertx-web-templ-rocker/src/test/java/io/vertx/ext/web/templ/RockerTemplateEngineTest.java
- vertx-template-engines/vertx-web-templ-rythm/src/test/java/io.vertx.ext.web.templ/RythmTemplateTest.java
- vertx-template-engines/vertx-web-templ-thymeleaf/src/test/java/io/vertx/ext/web/templ/ThymeleafTemplateNoCacheTest.java
- vertx-template-engines/vertx-web-templ-thymeleaf/src/test/java/io/vertx/ext/web/templ/ThymeleafTemplateTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderImpl.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/OpenAPIHolderTest.java
- vertx-web-session-stores/vertx-web-sstore-redis/pom.xml
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
- vertx-web/src/test/java/io/vertx/ext/web/WebTestBase.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/AuthHandlerTestBase.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/RerouteTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSProtocolTest.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSSessionTest.java
- vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java
CI on windows, a couple of issues are opened related to running tests on windows
- https://github.com/vert-x3/vertx-web/issues/1794
- https://github.com/vert-x3/vertx-web/issues/1793
> CI on windows

- vertx-web-graphql/pom.xml
- vertx-web-graphql/src/test/resources/emptyQuery.graphqls
> Upgrade to GraphQL-Java 16

- .github/workflows/ci.yml
- vertx-web-graphql/stop-apollo-tests-server.sh
- vertx-web/show-sockjs-write-handler-tests-server-logs.sh
- vertx-web/start-sockjs-write-handler-tests-server.sh
- vertx-web/stop-sockjs-write-handler-tests-server.sh
> CI: Updates to SockJS and Apollo integration tests

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java
> Ensure that pause and resume are only called if the request isn't ended

- vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/RouterBuilderOptionsConverter.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/ErrorType.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouteNamingStrategy.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterBuilderException.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterBuilderOptions.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/ContractEndpointHandler.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/package-info.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderIntegrationTest.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderSecurityTest.java
- vertx-web-session-stores/vertx-web-sstore-cookie/src/main/java/io/vertx/ext/web/sstore/cookie/package-info.java
- vertx-web-session-stores/vertx-web-sstore-redis/src/main/java/io/vertx/ext/web/sstore/redis/package-info.java
Motivation:
Ensure that generated APIs are correct.
> codegen related issues

- vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
> Fix #1825: fix the if-*-match parser

- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderImpl.java
> NullPointerException in OpenAPIHolderImpl with relative path

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
Motivation:
Depends on: https://github.com/vert-x3/vertx-auth/issues/450
> We need to pass the scopes to the OBO token requests

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/sstore/ClusteredSessionHandlerTest.java
Fixes #1830
Also, updated AuthenticationHandlerImpl: we can't resume if a websocket upgrade is expected.
> SessionHandler: pause request before async lookup

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/StaticDirectoryListHandlerTest.java
> Very old issue fixed

- vertx-web-openapi/pom.xml
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3RouterBuilderImpl.java
- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3Utils.java
> vertx-web-api-service now it's optional for vertx-web-openapi

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterExtendedParamTest.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Motivation:
Address https://github.com/quarkusio/quarkus/issues/15185
> Allow dash in path variables

- .github/workflows/ci.yml
Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:
> Enable ubuntu 20.04

- vertx-web/src/test/java/io/vertx/ext/web/MetricsTest.java
Motivation:
Verify that the `routed()` and named routes work
> Added a bare minimal metrics test

- vertx-web/src/main/java/io/vertx/ext/web/handler/LoggerFormatter.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/LoggerHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/LoggerHandlerTest.java
fixes #1892
Signed-off-by: thced <schrimp@gmail.com>
> feat: Add LoggerFormatter to LoggerHandler

- vertx-web-session-stores/vertx-web-sstore-redis/src/main/java/io/vertx/ext/web/sstore/redis/RedisSessionStore.java
- vertx-web-session-stores/vertx-web-sstore-redis/src/main/java/io/vertx/ext/web/sstore/redis/impl/RedisSessionStoreImpl.java
Fixes #1898
It misses a no-arg constructor
> Redis Session Store creation fails with service loader

- vertx-web/src/main/java/io/vertx/ext/web/handler/APIKeyHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/APIKeyHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/APIKeyHandlerTest.java
Motivation:
Implement APIKey support as preparation to complete security support on OpenAPI
> Fixes #1906: Implement APIKey handler

- vertx-web-graphql/pom.xml
Motivation:
Updating to the last graphql-java version which has fixed some bugs and improved performance
> updated to the newest graphQL version 16.2

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java
Motivation:
When expiring session cookies, the cookie attributes must be preserved.
Fixes #1890
> Add cookie attributes also when expiring

- vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3Utils.java
- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderIntegrationTest.java
- vertx-web-openapi/src/test/resources/specs/multipart.yaml
Fix https://github.com/vert-x3/vertx-web/issues/1887
> Fix regex for multipart encoding

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
Motivation:
Fix #1986 
Depends on https://github.com/vert-x3/vertx-bridge-common/pull/7
> Clean up bridge state on socket exception

- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/ValueParserInferenceUtils.java
> Fix NPE #1975

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthorizationHandlerImpl.java
Motivation:
Fixes #1983 
Adding pause/resume actions to authz handler.
> Add missing pause/resume to authz handler

- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSSocket.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSession.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java
> Event bus bridge fix

- vertx-web-graphql/pom.xml
Update to the latest GraphQL version 17.1
> Update to the latest GraphQL version 17.1

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthorizationHandlerImpl.java
AuthorizationHandler needs to check the requests state in case a BodyHandler comes first (same as AuthenticationHandler does)
Signed-off-by: Markus Spika <markus.spika@gmail.com>
Motivation:
bugfix for issue: https://github.com/vert-x3/vertx-web/issues/2030
Conformance:
> bugfix: conditional pause/resume request in AuthorizationHandler for HTTP2. fixes #2030

- vertx-web-graphql/pom.xml
Update to the latest GraphQL version 17.2 (bugfix release) 
More Informations here: https://github.com/graphql-java/graphql-java/releases/tag/v17.2
> Update to the latest GraphQL version 17.2 (bugfix release)

- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientSessionOauth2Test.java
Great job so far, thank you for the effort. I have mentioned this couple of times, there is one more thing that should be covered before this is valid. If token gets invalidated by provider our handler will be unaware of this and will get status 401 with no way of recovery and will continue to get this until token expires and mechanism for expiration obtains new one. This is left to user to cover but the whole idea of this feature was to remove all logic of token maintenance by user.
Here is the test that should be passed in order to fix this.
> Added test with loggedOut token for WebClientOAuth2

- vertx-web/pom.xml
- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/AllowForwardHeaders.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/OtpAuthHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/HotpAuthHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/TotpAuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/OtpHandlerTest.java
> Initial import of the MFA/OTP handler

- .github/workflows/ci.yml
- vertx-web-graphql/src/main/asciidoc/index.adoc
- vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/ws/GraphQLWSOptionsConverter.java
- vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ExecutionInputBuilderWithContext.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ExecutionInputConfig.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSConnectionHandler.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ErrorUtil.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/ConnectionHandler.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/ConnectionInitEventImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/GraphQLWSHandlerImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/MessageImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ws/ConnectionInitEvent.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ws/GraphQLWSHandler.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ws/GraphQLWSOptions.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ws/Message.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ws/MessageType.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GraphQLWSTestsServer.java
- vertx-web-graphql/src/test/resources/hello.graphqls
- vertx-web-graphql/start-graphql-ws-tests-server.sh
- vertx-web-graphql/stop-graphql-ws-tests-server.sh
- vertx-web-graphql/tests/graphql-ws/.babelrc
- vertx-web-graphql/tests/graphql-ws/graphql-ws.test.js
- vertx-web-graphql/tests/graphql-ws/package-lock.json
- vertx-web-graphql/tests/graphql-ws/package.json
> GraphQLWS protocol support

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/AuthXRequestedWithTest.java
Motivation:
I want to fix issue #2084
> Fix #2084: "WWW-Authenticate" header in response even if "X-Requested-With: XMLHttpRequest" in request

- vertx-web/src/main/java/io/vertx/ext/web/Route.java
- vertx-web/src/main/java/io/vertx/ext/web/Router.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/BlockingHandlerDecorator.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RouterState.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextInternal.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
> Feature. Route add metadata used for saved extra data

- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
Motivation:
support IPv6 host matches.
> support IPv6 host matches.

- vertx-web/src/main/java/io/vertx/ext/web/handler/CorsHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CORSHandlerTest.java
Motivation:
based on https://github.com/netty/netty/pull/12070
requires: https://github.com/eclipse-vertx/vert.x/pull/4265
waiting for netty 4.1.74
> Add CORS Private Network feature

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/sstore/LocalSessionHandlerTest.java
> Fix #2123: Handle all cases when flushing the session with a callback

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
> Backporting #2123

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/sstore/LocalSessionHandlerTest.java
Improve the expectations based on community feedback
> Update PR based on discussion

- vertx-web-graphql/src/main/asciidoc/index.adoc
Motivation:
Fix a broken link in the docs.
> Fixed broken link

- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSession.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSSessionTest.java
> Skip sending an answer if the pending-writes queue is empty.

- vertx-web-graphql/pom.xml
> Upgrade to GraphQL-Java 18.0

- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
> Fixes #2196: Always set the SSL flag if the users so specified

- vertx-web-graphql/pom.xml
> Upgrade to GraphQL-Java 18.2

- vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderIntegrationTest.java
- vertx-web-openapi/src/test/resources/specs/validation_test.yaml
- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/ValueParserInferenceUtils.java
> fix: allow ExplodedArrayValueParameterParser to handle JsonObejcts

- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
- vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Fixes #2293 
Can you review this @pmlopes ?
> Added Allow header to 405 response

- vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSRawTransportTest.java
Motivation:
Small behavior change needs to be propagated to the test suite
> Update test to match the new format of the exception

- vertx-web-graphql/src/main/asciidoc/index.adoc
- vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/TriConsumer.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/dataloader/VertxBatchLoader.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/dataloader/VertxMappedBatchLoader.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/instrumentation/VertxFutureAdapter.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/instrumentation/impl/ToCompletionStageImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/schema/VertxDataFetcher.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/VertxFutureInstrumentationTest.java
> Data fetchers and data loader changes

- vertx-web-graphql/src/main/asciidoc/index.adoc
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSConnectionInitEvent.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSHandler.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSMessage.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSMessageType.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSOptions.java
> Deprecate ApolloWS handler

- .github/workflows/ci.yml
- vertx-web-graphql/tests/apollo/apollo.test.js
- vertx-web-graphql/tests/apollo/package.json
- vertx-web-graphql/tests/graphql-ws/graphql-ws.test.js
- vertx-web-graphql/tests/graphql-ws/package.json
> GraphQL JS integration tests updates

- vertx-web-graphql/src/main/asciidoc/index.adoc
- vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLBatch.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLQuery.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/ConnectionHandler.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloTestsServer.java
- vertx-web-graphql/tests/apollo/apollo.test.js
> Apollo persisted queries

- vertx-web-graphql/pom.xml
- vertx-web-graphql/src/main/asciidoc/index.adoc
- vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/instrumentation/JsonObjectAdapter.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/schema/VertxPropertyDataFetcher.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GetRequestsTest.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/JsonResultsTest.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/PostRequestsTest.java
> Upgrade to GraphQL-Java 20 and JsonObjectAdapter

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
Fixes https://github.com/vert-x3/vertx-web/issues/2336
> Fix NullPointerException (#2336)

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSPHandlerImpl.java
Pull-request for issue: https://github.com/vert-x3/vertx-web/issues/2359
> Add report-to support in CSPHandlerImpl, issue 2359

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthorizationHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/MultiAuthorizationHandlerTest.java
Motivation:
authz internals are now immutable and a CoW structure, that required a small update to the internal code.
> Update web to latest auth

- vertx-web-graphql/pom.xml
See https://github.com/graphql-java/graphql-java/releases/tag/v20.1
> Upgrade to GraphQL-Java 20.1

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/MultiTenantHandlerImpl.java
> Ensure that multi tenant handler calls the on order on sub handlers

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
> Fixes #2291: Adding the flush notifications where missing

- vertx-web/src/main/java/io/vertx/ext/web/impl/ParsableMIMEValue.java
Motivation:
Fix #2388: Missing lazy header decoding trigger
> Fix #2388: Add missing ensureHeaderProcessed()

- vertx-web-openapi-router/src/main/java/io/vertx/ext/web/openapi/router/impl/AuthenticationHandlers.java
- vertx-web-openapi-router/src/main/java/io/vertx/ext/web/openapi/router/impl/RouterBuilderImpl.java
- vertx-web-openapi-router/src/test/java/io/vertx/router/test/base/RouterBuilderTestBase.java
Motivation:
We made some changes in vertx-openapi which need to be adopted.
> feat(openapi-router): adopt to latest vertx-openapi version and small fixes

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java
Motivation:
Fix #1935 Always log even on error
> Fix #1935: use the right handler

- vertx-web/src/main/java/io/vertx/ext/web/handler/APIKeyHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/APIKeyHandlerImpl.java
> implement ApiKeyHandler token extractor

- vertx-web-graphql/pom.xml
https://github.com/graphql-java/graphql-java/releases/tag/v20.3
> build(deps): bump com.graphql-java:graphql-java from 20.2 to 20.3

- vertx-web/pom.xml
- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/healthchecks/HealthCheckHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/healthchecks/impl/HealthCheckHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/healthchecks/impl/JsonCredentials.java
- vertx-web/src/test/java/io/vertx/ext/web/healthchecks/AuthenticationTest.java
- vertx-web/src/test/java/io/vertx/ext/web/healthchecks/HealthCheckTest.java
- vertx-web/src/test/java/io/vertx/ext/web/healthchecks/HealthCheckTestBase.java
- vertx-web/src/test/java/io/vertx/ext/web/healthchecks/HealthCheckWithSubRouterMountSlashTest.java
- vertx-web/src/test/java/io/vertx/ext/web/healthchecks/HealthCheckWithSubRouterTest.java
- vertx-web/src/test/java/io/vertx/ext/web/healthchecks/HealthCheckWithSubRouterWithoutRouteTest.java
See https://github.com/vert-x3/issues/issues/632
> Implement the health check handler in Vert.x Web

- vertx-web-graphql/pom.xml
https://github.com/graphql-java/graphql-java/releases/tag/v20.4
> Upgrade to GraphQL-Java 20.4

- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/SlowClusterEventbusBridgeTest.java
See #2423
Otherwise, if the user unregisters immediately after registration, and the cluster registration is slow, there might be orphan registration.
> EventBusBridge must save registration locally before completion

- vertx-web-graphql/pom.xml
Release notes https://github.com/graphql-java/graphql-java/releases/tag/v21.0
> build(deps): bump com.graphql-java:graphql-java from 20.4 to 21.0

- vertx-web-graphql/pom.xml
https://github.com/graphql-java/graphql-java/releases/tag/v20.6
> Upgrade to GraphQL 20.6

- vertx-web-graphql/pom.xml
https://github.com/graphql-java/graphql-java/releases/tag/v21.1
> Upgrade to GraphQL 21.1

- vertx-web-graphql/pom.xml
https://github.com/graphql-java/graphql-java/releases/tag/v21.3
> Upgrade to Vert.x Web GraphQL 21.3

- vertx-web-graphql/pom.xml
https://github.com/graphql-java/graphql-java/releases/tag/v20.7
> Upgrade to Vert.x Web GraphQL 20.7

- vertx-web-client/src/main/java/io/vertx/ext/web/client/OAuth2WebClient.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/Oauth2WebClientAware.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientSessionOauth2Test.java
> Expose method to get User associated with current OAuth2WebClient

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/BodyHandler.java
> BodyHandler: document setDeleteUploadedFilesOnEnd

- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/io/vertx/ext/web/handler/BodyHandler.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java
> Set BodyHandler default limit to 10 megabytes

- vertx-template-engines/vertx-web-templ-mvel/src/main/java/io/vertx/ext/web/templ/mvel/impl/MVELTemplateEngineImpl.java
- vertx-template-engines/vertx-web-templ-mvel/src/test/java/io/vertx/ext/web/templ/MVELTemplateTest.java
> Fix MVELTemplateEngineImpl file resolution on Windows

- vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphiQLHandler.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphiQLHandlerBuilder.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphiQLHandlerBuilderImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/GraphQLWSHandlerBuilderImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ws/GraphQLWSHandler.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ws/GraphQLWSHandlerBuilder.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GraphQLWSTestsServer.java
> Builders for GraphQL handlers

- vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandler.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandlerBuilder.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerBuilderImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
- vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/LocaleTest.java
Follows-up on #2531
GraphQLHandlerBuilder was missing
> Builder for GraphQLHandler

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextInternal.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java
Fixes #2557 
Backport of #2558 with simplification
> Protect CSRFHandler from reroute invocations

- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSHandlerImpl.java
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/GraphQLWSHandlerImpl.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java
- vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
- vertx-web/src/test/java/io/vertx/ext/web/ForwardedTest.java
Follows-up on https://github.com/eclipse-vertx/vert.x/pull/5098
> Use canUpgradeToWebsocket method of Vert.x core

- vertx-template-engines/vertx-web-templ-pug/pom.xml
Align with Vert.x Lang Kotlin version
> Dependency convergence for org.jetbrains:annotations

- vertx-web/src/main/asciidoc/index.adoc
See #2218 
Follows-up on https://github.com/vert-x3/vertx-web/commit/f1e0597b623aef22804da11f76cec68c3c5e2496
> Fix template engine docs

- vertx-web/src/main/asciidoc/index.adoc
> Update template engines doc

- vertx-web-graphql/pom.xml
Release notes https://github.com/graphql-java/graphql-java/releases/tag/v21.5
> build(deps): bump com.graphql-java:graphql-java from 21.4 to 21.5

- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/cache/CacheControl.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/impl/cache/CacheControlTest.java
Cherry-picks the commits from #2592 for the NPE fix and test
> Cherry-picked #2592 for 4.x

- vertx-web-openapi-router/src/test/java/io/vertx/ext/web/openapi/router/impl/RouterBuilderImplTest.java
- vertx-web-openapi-router/src/test/java/io/vertx/router/test/e2e/RootPathTest.java
- vertx-web-openapi-router/src/test/resources/e2e/root.json
Related to https://github.com/eclipse-vertx/vertx-openapi/issues/20
> feat(openapi-router): ensure that path "/" works in OpenAPI spec

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
Motivation:
See https://github.com/vert-x3/vertx-web/pull/2623
> fix typo in error message regarding the oauth2 pkce length

- vertx-web-proxy/src/main/asciidoc/index.adoc
- vertx-web-proxy/src/main/java/examples/WebProxyExamples.java
- vertx-web-proxy/src/main/java/io/vertx/ext/web/proxy/handler/impl/ProxyHandlerImpl.java
- vertx-web-proxy/src/test/java/io/vertx/ext/web/proxy/handler/ProxyHandlerTest.java
See #2614
Added documentation and make ProxyHandler fail fast if the BodyHandler has been seen.
> BodyHandler should not be added before the ProxyHandler

- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ChainAuthHandlerImpl.java
- vertx-web/src/test/java/io/vertx/ext/web/handler/ChainAuthMixHandlerTest.java
See #2641
ChainAuthHandlerImpl maintains, for instances of type "any", an index indicating which handler in the list succeeded to authenticate the user.
This index is used in the postAuthentication method to determine which handler int he list should have its postAuthentication method invoked.
When "any" ChainAuthHandlers were nested, the index computed in the top level ChainAuthHandler was used to choose the handlers in the list of nested ChainAuthHandler.
This caused either the wrong handler to be peeked or IndexOutOfBoundsException to be thrown.
With this change, the value put in the RoutingContext is specific to a ChainAuthHandler instance.
> Fix for nested ChainAuthHandlers of type "any"

- vertx-web-graphql/pom.xml
Release notes: https://github.com/graphql-java/graphql-java/releases/tag/v22.3
> Upgrade graphql-java from 22.2 to 22.3

- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
This is a follow-up of https://github.com/eclipse-vertx/vert.x/pull/5307 to use the enhanced internal API provided in the mentioned PR.
> Uses optimized internal method to save HostAndPort allocation

- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/CookieStoreImpl.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/MultipartFormUpload.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/cache/CacheControl.java
- vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/cache/CacheKey.java
- vertx-web-client/src/main/java/module-info.java
- vertx-web-client/src/main/resources/META-INF/MANIFEST.MF
- vertx-web-client/src/test/java/io/vertx/ext/web/client/it/WebClientDatabindTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/CachingWebClientTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/HandlerExceptionTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/HttpContextTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/InterceptorTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/JsonStreamTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/MultipartFormUploadTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/SessionAwareWebClientTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/SharedWebClientTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/UriTemplateTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/WebClientOptionsTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/WebClientSessionOauth2Test.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/WebClientSessionTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/WebClientTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/WebClientTestBase.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/cache/CacheControlTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/cache/VaryTest.java
- vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/jackson/WineAndCheese.java
- vertx-web-client/src/test/java/module-info.java
- vertx-web-common/src/main/java/module-info.java
- vertx-web-common/src/main/resources/META-INF/MANIFEST.MF
- vertx-web-common
- vertx-web-client
> Partial JPMS support

- vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java
Motivation:
See test run for https://github.com/vert-x3/vertx-web/pull/2667.
This test succeeds when the handling of the GET request to `/csrf/first` is started before the POST request for `/csrf/second`. Without the change proposed in this PR, however, it may happen that the handling of the POST request starts before the handling of the GET request.
The test may succeed without the proposed change due to the order in which the statements are executed, but the order of the statements does not guarantee the order in which the requests are handled.
> Fix flaky test by ensuring overlap of GET and POST

- vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
> Informational message when rejecting a malformed request

- vertx-web/pom.xml
- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/WebAuthn4JHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/WebAuthn4JHandlerImpl.java
- vertx-web/src/main/java/module-info.java
- vertx-web/src/test/java/io/vertx/ext/web/tests/handler/WebAuthn4JHandlerTest.java
- vertx-web/src/test/java/module-info.java
Requires https://github.com/eclipse-vertx/vertx-auth/pull/692 and https://github.com/vert-x3/vertx-dependencies/pull/197
> Added support for vertx-auth-webauthn4j

- vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
> Update RoutingContext#normalizedPath Javadoc to match implementation

- vertx-web-graphql/pom.xml
- vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/instrumentation/JsonObjectAdapter.java
https://github.com/graphql-java/graphql-java/releases/tag/v23.0
> Upgrade to GraphQL Java 23

- vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
This is the porting of https://github.com/vert-x3/vertx-web/pull/2526
> Enable using String::equals fast-path intrinsics for exact matches

- vertx-web-validation/src/main/asciidoc/index.adoc
- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/BadRequestException.java
- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/ParameterProcessorException.java
- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/parameter/ParameterProcessor.java
- vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/parameter/ParameterProcessorImpl.java
- vertx-web-validation/src/test/java/io/vertx/ext/web/validation/tests/impl/ParameterProcessorUnitTest.java
Resolves #2639 
This tries to implement requested feature without breaking the current API.
If this satisfies the requirements from feature and API side I will add tests to verify the functionality
> Added custom parsing and validation exception message

- vertx-web/src/main/java/examples/WebExamples.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/CorsHandler.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
Signed-off-by: Paulo Lopes <pmlopes@users.noreply.github.com>
Motivation:
Backporting the breaking change #2719
> Backporting #2719

- vertx-web-graphql/pom.xml
https://github.com/graphql-java/graphql-java/releases/tag/v23.1
> Upgrade to GraphQL-Java 23.1

- pom.xml
- vertx-web-session-stores/pom.xml
- vertx-web-session-stores/vertx-web-sstore-caffeine/pom.xml
- vertx-web-session-stores/vertx-web-sstore-caffeine/src/main/java/io/vertx/ext/web/sstore/caffeine/CaffeineSessionStore.java
- vertx-web-session-stores/vertx-web-sstore-caffeine/src/main/java/io/vertx/ext/web/sstore/caffeine/impl/CaffeineSessionStoreImpl.java
- vertx-web-session-stores/vertx-web-sstore-caffeine/src/main/java/io/vertx/ext/web/sstore/caffeine/package-info.java
- vertx-web-session-stores/vertx-web-sstore-caffeine/src/main/java/module-info.java
- vertx-web-session-stores/vertx-web-sstore-caffeine/src/main/resources/META-INF/services/io.vertx.ext.web.sstore.SessionStore
- vertx-web-session-stores/vertx-web-sstore-caffeine/src/test/java/io/vertx/ext/web/sstore/caffeine/tests/CaffeineSessionHandlerTest.java
- vertx-web-session-stores/vertx-web-sstore-caffeine/src/test/java/io/vertx/ext/web/sstore/caffeine/tests/CaffeineSessionStoreTest.java
- vertx-web-session-stores/vertx-web-sstore-caffeine/src/test/java/module-info.java
- vertx-web/src/main/asciidoc/index.adoc
- vertx-web/src/main/java/io/vertx/ext/web/sstore/LocalSessionStore.java
- vertx-web/src/main/java/module-info.java
> Add Caffeine implementation for SessionStore

- vertx-web-session-stores/vertx-web-sstore-cookie/src/main/java/io/vertx/ext/web/sstore/cookie/CookieSessionStore.java
- vertx-web-session-stores/vertx-web-sstore-cookie/src/main/java/io/vertx/ext/web/sstore/cookie/impl/CookieSession.java
- vertx-web-session-stores/vertx-web-sstore-cookie/src/main/java/io/vertx/ext/web/sstore/cookie/impl/CookieSessionStoreImpl.java
- vertx-web-session-stores/vertx-web-sstore-cookie/src/test/java/io/vertx/ext/web/sstore/cookie/tests/CookieSessionCreateTest.java
- vertx-web-session-stores/vertx-web-sstore-cookie/src/test/java/io/vertx/ext/web/sstore/cookie/tests/CookieSessionHandlerTest.java
Motivation:
Backporting #2746 to 5.0
> Ensuring that cookie sessions are reusable across nodes

- vertx-web-openapi-router/src/main/java/io/vertx/ext/web/openapi/router/impl/AuthenticationHandlers.java
- vertx-web-openapi-router/src/test/java/io/vertx/router/test/e2e/RouterBuilderSecurityTest.java
> fix: Add check of empty chain auth handler

- .github/dependabot.yml
See https://github.com/vert-x3/vertx-web/issues/2764
> Configure Dependabot Updates for `vertx-web-graphql`

- vertx-web-session-stores/vertx-web-sstore-cookie/src/main/java/io/vertx/ext/web/sstore/cookie/impl/CookieSession.java
Fixing the decryption of the cookie payload.
Motivation:
The test CookieSessionHandlerTest#testDestroySession was failing, this should fix it
Conformance:
You should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
> fix: Test was failing with javax.crypto.ShortBufferException: Output buffer invalid

- vertx-web/src/main/java/io/vertx/ext/web/impl/Origin.java
- vertx-web/src/test/java/io/vertx/ext/web/tests/handler/CORSHandlerTest.java
- vertx-web/src/test/java/io/vertx/ext/web/tests/impl/OriginTests.java
Port of https://github.com/vert-x3/vertx-web/pull/2804, see https://github.com/vert-x3/vertx-web/issues/2800
> CORS: support moz-extension

- vertx-web-session-stores/vertx-web-sstore-cookie/src/test/java/io/vertx/ext/web/sstore/cookie/tests/CookieSessionHandlerTest.java
- vertx-web-session-stores/vertx-web-sstore-cookie/src/test/java/module-info.java
- vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
> CookieSessionStore requiring two authentications to persist user
