vert-x3/vertx-web

src/main/java/io/vertx/ext/apex/impl/RouteImpl.java
src/test/java/io/vertx/ext/apex/RouterTest.java

Check Content-Type is not null before trying to match it with the accepted content types
Fixes #53

Avoid exception in ctMatches when no Content-Type sent

---

src/main/asciidoc/groovy/index.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/js/index.adoc
src/main/java/examples/Examples.java

Example:
mainRouter.route("/static") -> mainRouter.route("/static/")
The documentation doesn't reflect what's in the vertx-example repo code.

Add /* when routes really need to match the whole path.

---

src/main/asciidoc/groovy/index.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/js/index.adoc
src/main/java/io/vertx/ext/apex/package-info.java

Replaced misleading typo: "is not accessible" by "is now accessible".

Fix typo on Sub-routers chapter

---

src/main/java/io/vertx/ext/apex/impl/RouteImpl.java
src/test/java/io/vertx/ext/apex/RouterTest.java

The path matcher was matching too much on paths that contain an asterisk after the trailing
slash.

Issue73: bugfix in RouteImpl  & unit test in RouteTest . 

---

src/main/java/io/vertx/ext/apex/handler/impl/StaticHandlerImpl.java
src/test/java/io/vertx/ext/apex/handler/StaticHandlerTest.java
src/test/resources/webroot/somedir/index.html
src/test/resources/webroot/somedir/otherpage.html

Once again with test and caching. 
Index pages can now be served on sub directories regardless path format (with ending slash or without). Root index page handing is unchanged.
Had to extract the async file props handler lambda to a factory method to be able to call it recursively (once) for the index page, since a directory must be identified as such first

static handling of index pages for subdirectories

---

vertx-web/src/main/java/io/vertx/ext/web/handler/StaticHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java

Just add a way to pass a classloader to the static handler.
If set the FileResolver is invoked in a TCCL switch to be able to resolve the file from this custom classloader. This is mainly for OSGi and for application using custom classloaders.

Allow the static handler to use a custom class loader to load resources

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java

The last attempt forgot two places (using the file system directly).
This PR is needed for the Eclipse Equinox support

Improve the TCCL Switch in the StaticHandlerImpl

---

vertx-web/src/main/asciidoc/groovy/index.adoc
vertx-web/src/main/asciidoc/java/index.adoc
vertx-web/src/main/asciidoc/js/index.adoc
vertx-web/src/main/asciidoc/ruby/index.adoc
vertx-web/src/main/java/io/vertx/ext/web/package-info.java

The compile scope call lacked string delimiters.
I also added a surrounding dependencies section for clarity.

Gradle dependency documentation fix

---

vertx-web/src/main/java/io/vertx/ext/web/handler/StaticHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java

By default the old original behavior is preserved no access to root is allowed unless the flag is enabled.

Fixes #204

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java

Headers set in the DeliveryOptions of a message are now send  over the EventbusBridge to the eventbus javascript client. The other way (headers from javascript client to eventbus) already exists.
Perhaps the code in the EventbusBridgeImpl which copies the headers MultiMap into the Json envelope could go into the Json code of vertx-core (in a more general way).

EventbusBridge sends headers in messages to eventbus js client

---

vertx-web/src/main/java/io/vertx/ext/web/handler/BodyHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java

Currently there is no way to avoid the creation of the default uploads directory ```file-uploads``` in the CWD which is created when invoking ```new BodyHandlerImpl()```.  Adding another constructor would solve this issue. 
Another option i can think of is using a static System property similiar to the way this is currently being implemented in ```FileResolver``` via ```vertx.cacheDirBase```.
Signed-off-by: Johannes Schüth <j.schueth@gentics.com>

Add BodyHandler constructor which allows custom upload directory

---

vertx-web/src/main/asciidoc/java/index.adoc

Based on my own test and the example here https://github.com/vert-x3/vertx-examples/blob/master/web-examples/src/main/java/io/vertx/example/web/vertxbus/amd/webroot/index.html#L30 it seems that the callback function needs two arguments.

Missing argument in callback method example

---

vertx-web/src/main/asciidoc/groovy/index.adoc
vertx-web/src/main/asciidoc/java/index.adoc
vertx-web/src/main/asciidoc/js/index.adoc
vertx-web/src/main/asciidoc/ruby/index.adoc
vertx-web/src/main/java/io/vertx/ext/web/package-info.java

Small documentation fix. The vertx-eventbus.js example was not executable.

Documentation fix for vertx-eventbus.js example

---

vertx-web/src/main/java/io/vertx/ext/web/impl/HttpServerRequestWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java

As suggested by Arnaud Esteve https://github.com/vert-x3/vertx-web/pull/281#issuecomment-166308585
I wanted to avoid adding a mocking dependency but if we could do that we could simplify this and further tests greatly.
The pull request also includes the isSSL implementation in HttpServerRequestWrapper as HttpServerRequest has changed in vert.x core.

Tests for getBodyAsJson and getBodyAsJsonArray

---

vertx-template-engines/vertx-web-templ-handlebars/pom.xml
vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/impl/HandlebarsTemplateEngineImpl.java

See "Bump handlebars to 2.2.3": https://github.com/vert-x3/vertx-web/issues/220 for more info
Bumping the version and providing stub implementation for new methods in Loader interface.

Bump handlebars to 4.0.4

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java

Now that bytesWritten() is available on HttpServerResponse, use that instead of content-length header to get size of response.
Signed-off-by: Dave Sinclair <stampy88@yahoo.com>

Content Length change

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java

This avoids issues where we use the properties in the cache entry, but not the data.  This can result in the content being truncated because the content used is actually longer than the entry says it is.

Null out cache entry when we decide not to use it.

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

By replacing the set with a list we can track the index of the variable on the path and allow the usage of characters that are not allowed on regex named groups such as:
* underscore
* dash

Fixes #293: Allow usage of underscore and dash in path variables

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java

fixes #299: Root paths check using Files.listRoots() instead of /

fixes #299: Root paths check using Files.listRoots() instead of /

---

vertx-web/src/main/asciidoc/groovy/index.adoc
vertx-web/src/main/asciidoc/java/index.adoc
vertx-web/src/main/asciidoc/js/index.adoc
vertx-web/src/main/asciidoc/ruby/index.adoc
vertx-web/src/main/java/io/vertx/ext/web/package-info.java

For maven artefacts, the type matches the file name extension in the repository. For the referenced JavaScript resource the extension is `js` and should be named in the docs accordingly. 
Link to maven repo: http://central.maven.org/maven2/io/vertx/vertx-web/3.2.1/

adding missing dependency type javascript for maven artefacts

---

vertx-web/src/client/vertx-eventbus.js

Fixes: vert-x3/vertx-bus-bower#6
Even though we pass the event for cases when fall back modes are used it is not guaranteed that the event is of type: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent but a wrap provided by sockJS

Fix: vert-x3/vertx-bus-bower#6

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java

Fixes #300
errors were not being marked properly and being delivered as messages

Fixes #300: errors were not being marked properly

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/BasicAuthHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java

Fixes #322 
Several things here:
* Session handler will only issue saves iif the response status is 2xx or 3xx
* Calling end handlers is called in a reverse order of registry. This is the correct way since it works as a stack, initially we add handlers and we clean up running backwards. e.g.: cookie handler -> session handler, and the we clean up by first calling the session handler and then the cookie handler.
* Fixed the basic auth test which stated that on a auth error 401 you would receive a valid session cookie. That is invalid behavior.

Fixes #322: do not store sessions and issue cookies on error

---

vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java

Fixes #305 
When asking the set status code (when no set operation has been performed yet) it returns -1 (undefined).

Fix documentation

---

vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

A very basic implementation for now, let me know what you guys think about it.
It's aimed at being backwards compatible, meaning path parameters are still available as request parameters, but if you want to fetch actual routing parameters, you'll fetch them from the routing context, which makes sense since it's a matter of vertx-web, not vertx-core.
Please review and let me know if something's wrong, thanks.
(bound to : #304 )

add path params in a separate map + a simple test

---

vertx-web/src/main/asciidoc/enums.adoc
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java

Fixes #335 
Since this was a race condition, making a test to reproduce the issue was hard. The current test might seem a bit too much but it is what i can use on my laptop to reproduce the issue 100% of the times. It could be that on other machines it will not be 100%...
The problem was that a counter was being incremented and decremented every time a file was being offered from the upload body. This can be seem like a stack, say that you have 1000 files in the upload.
The counter would be going like:
```
cnt++
cnt++
cnt++
```
but with small bodies at the end of the single upload the counter gets decremented:
```
cnt--
```
We were checking if the cnt was 0 and assume we were complete, however, we could reach a point where cnt was 0 but the parsing was not finished (this bug).
The …

Fixes #335: race condition when parsing multiple file uploads

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java

1. Check message address in internal handler
This is useful when the BridgeEvent handler wants to hide the address in `send/publish/register/unregister`. E.g. the internal address has a internal parameter in websession, then the address should be translated to `<new-address-with-session-param>`
2. Set web session accessed in ping handler
This makes the websession not timeout even the transport is Websocket, other transport in SockJS is not a problem, since the ping will always trigger a HTTP call and makes the session accessed

Improve in EventBusBridgeImpl

---

vertx-template-engines/vertx-web-templ-freemarker/pom.xml
vertx-template-engines/vertx-web-templ-handlebars/pom.xml
vertx-template-engines/vertx-web-templ-jade/pom.xml
vertx-template-engines/vertx-web-templ-mvel/pom.xml
vertx-template-engines/vertx-web-templ-pebble/pom.xml
vertx-template-engines/vertx-web-templ-thymeleaf/pom.xml
vertx-web/pom.xml

This follows a discussion on the mailing list: https://groups.google.com/forum/#!topic/vertx/836vf0QWbGk
I'm trying to convert the Vertx modules to valid OSGi bundles. The bnd Maven plugin is a recently released plugin that solves many of the problems that plagues the Felix Bundle Plugin (although their goal is similar). 
In the bnd Maven plugin the bundle configuration is stored in a bnd.bnd file. Together with this PR I have another PR for the RX-ified API. 
I created an example workspace that uses these bundles: https://github.com/paulbakker/vertx-osgi-v2

OSGi-ified the JAR

---

vertx-web/pom.xml
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/test/java/io/vertx/ext/web/RoutingContextNullCurrentRouteTest.java

Fix #401 
the current route cannot be set to null after the handler as been complete because due to the nature of async programming it does not mean that the handler is complete.

Fix #401: do not reset the current route until handling is complete

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

This is only a small fix to prevent parsing the path twice using `URLDecoder.decode`. This is introduced by #363 , and I don't think decoding twice is intended.

Percent sign is decoded twice

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/JsonPTransport.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
vertx-web/src/test/java/io/vertx/ext/web/UtilsTest.java

only process percent encoded values on path as per RFC3986

---

vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/SessionImpl.java
vertx-web/src/test/java/io/vertx/ext/web/sstore/ClusteredSessionHandlerTest.java

In a clustered environment, the lastAccessed property of the session is not being serialized. The session times out even if the user touches the session.

Serialization of the lastAccessed session property

---

vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/package-info.java

Added a note and an example to the docs for `blockingHandler` to explain how it can be used with multipart form data.

Updated docs for blockingHandler

---

vertx-web/src/main/java/io/vertx/ext/web/handler/StaticHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java

I couldn't find out if it's possible to get the server options within `StaticHandler`.
So currently, the `Vary` header is send when the request contains an `Accept-Encoding`-header, assuming that when someone uses `StaticHandler`, compression is most likely also wanted.

Add Vary header when using caching and compression

---

vertx-web/src/main/java/examples/WebExamples.java

.*foo will not match "/foo/bar" but the "/bar/foo".

change "/foo/bar" to "/bar/foo"

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java

RFC7233 (and all earlier) state that it's ok to specify an end offset larger than the actual file size so that the client can request to limit the amount of data transferred without knowing the exact content length in advance. Quoting:
> A client can limit the number of bytes requested without knowing the
size of the selected representation.  If the last-byte-pos value is
absent, or if the value is greater than or equal to the current
length of the representation data, the byte range is interpreted as
the remainder of the representation (i.e., the server replaces the
value of last-byte-pos with a value that is one less than the current
length of the selected representation).
https://tools.ietf.org/html/rfc7233#section-2.1
Updated implementation and unit tests to match this.

StaticHandlerImpl: Fix handling of range end offset

---

vertx-sockjs-service-proxy/src/test/kotlin/io/vertx/kotlin/serviceproxy/testmodel/TestDataObject.kt
vertx-web/src/main/java/io/vertx/ext/web/Session.java
vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BasicAuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FormLoginHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/UserHolder.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/UserSessionHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/package-info.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/SessionStore.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/ClusteredSessionStoreImpl.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/LocalSessionStoreImpl.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/PRNG.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/SessionImpl.java
vertx-web/src/main/resources/vertx-web-js/session.js
vertx-web/src/main/resources/vertx-web-js/session_handler.js
vertx-web/src/main/resources/vertx-web/session_handler.rb
vertx-web/src/test/java/io/vertx/ext/web/handler/BasicAuthHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/RedirectAuthHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java

Fixes #399 #400 #403 
When dealing with sessions when a user upgrades its security level it is recommended that a session id is also regenerated. The reason is to avoid session fixing. Also there are requirements that state what a minimal session id length should be for security concerns.
This PR implements these requirements.
A follow up will be to perform regeneration on the current auth handlers

Session management following OWASP recommendations

---

vertx-template-engines/vertx-web-templ-mvel/src/main/java/io/vertx/ext/web/templ/impl/MVELTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-mvel/src/test/filesystemtemplates/include-test1.txt
vertx-template-engines/vertx-web-templ-mvel/src/test/filesystemtemplates/subfolder/include-test2.txt
vertx-template-engines/vertx-web-templ-mvel/src/test/filesystemtemplates/test-mvel-template4.templ
vertx-template-engines/vertx-web-templ-mvel/src/test/java/io/vertx/ext/web/templ/MVELTemplateTest.java

The instance of template compiler should know the filesystem location of files to resolve the correct path. Instead of:
`
TemplateRuntime.execute(template, variables)
`
we should use:
`
(String) new TemplateRuntime(template.getTemplate(), null, template.getRoot(), directoryName)
.execute(new StringAppender(), variables, new ImmutableDefaultFactory())
`
where directoryName is the root folder of the file to compile:
`
String directoryName = Paths.get(templateFileName).getParent().toAbsolutePath().toString();
`
I added also a Test:
`
@Test
public void testTemplateHandlerWithInclude() throws Exception {
TemplateEngine engine = MVELTemplateEngine.create();
testTemplateHandler(engine, "src/test/filesystemtemplates", "test-mvel-template4.templ", "Hello badger and fox\nRequest path is …

resolution of #420

---

vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/HandlebarsTemplateEngine.java
vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/impl/HandlebarsTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/impl/JsonArrayValueResolver.java
vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/impl/JsonObjectValueResolver.java
vertx-template-engines/vertx-web-templ-handlebars/src/test/filesystemtemplates/test-handlebars-template4.hbs
vertx-template-engines/vertx-web-templ-handlebars/src/test/filesystemtemplates/test-handlebars-template5.hbs
vertx-template-engines/vertx-web-templ-handlebars/src/test/filesystemtemplates/test-handlebars-template6.hbs
vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateTest.java

It is currently not possible to resolve properties of Vert.x JsonObjects (io.vertx.core.json) using the `HandlebarsTemplateEngine`. This makes it impossible to resolve properties if JsonObjects have been added to the template context.
Handlebars is able to resolve regular collections (e.g. Maps) but JsonObject#getMap() is only returning the inner map and it is not transforming the whole io.vertx.core.json.JsonObject.
It is fortunately possible to add custom resolvers to the Handlebars context. I wrote a custom JsonObject resolver which allows resolving of Vert.x JsonObject properties within Handlebars Templates.

Enhance handlebars template context handling

---

vertx-template-engines/vertx-web-templ-freemarker/pom.xml
vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/impl/FreeMarkerTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/impl/JsonArrayAdapter.java
vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/impl/JsonObjectAdapter.java
vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/impl/VertxWebObjectWrapper.java
vertx-template-engines/vertx-web-templ-freemarker/src/test/groovy/FreeMarkerGroovyTemplateTest.groovy
vertx-template-engines/vertx-web-templ-freemarker/src/test/java/io/vertx/ext/web/templ/FreeMarkerJavascriptTemplateTest.java
vertx-template-engines/vertx-web-templ-freemarker/src/test/resources/freemarker_javascript_template_test.js
vertx-template-engines/vertx-web-templ-freemarker/src/test/resources/somedir/altlang.ftl

This is useful for alternate languages (Groovy, Javascript, Ruby) in particular since when lists/maps are added to the routing context, they are converted to JsonArray/JsonObject.
Then it feels unnatural for the user, because the expectation is that you can simply iterate other these objects but you can't.
Tests for Groovy and JS have been added to reflect the new behavior.

Integrate FreeMarker engine with Vertx Json classes properly

---

vertx-web-client/src/main/asciidoc/groovy/index.adoc
vertx-web-client/src/main/asciidoc/kotlin/index.adoc
vertx-web/src/main/asciidoc/groovy/index.adoc
vertx-web/src/main/asciidoc/java/index.adoc
vertx-web/src/main/asciidoc/js/index.adoc
vertx-web/src/main/asciidoc/kotlin/index.adoc
vertx-web/src/main/asciidoc/ruby/index.adoc
vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/handler/ResponseContentTypeHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ResponseContentTypeHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/package-info.java
vertx-web/src/main/resources/vertx-web-js/response_content_type_handler.js
vertx-web/src/main/resources/vertx-web/response_content_type_handler.rb
vertx-web/src/test/java/io/vertx/ext/web/handler/ResponseContentTypeHandlerTest.java

Currently when you say that a route produces content of some type, the response header is not set automatically.
With this change, the most acceptable type would be set (but the user can still disable the future at the route level).

Auto set content type from most acceptable match

---

vertx-web/src/main/java/io/vertx/ext/web/impl/HeaderParser.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

See:
Accept header: https://tools.ietf.org/html/rfc7231#section-5.3.2
Comma separated values: https://tools.ietf.org/html/rfc7230#section-7
Whitespace: https://tools.ietf.org/html/rfc7230#section-3.2.3

Ignore whitespace around comma separated header values

---

vertx-web/src/main/asciidoc/groovy/index.adoc
vertx-web/src/main/asciidoc/java/index.adoc
vertx-web/src/main/asciidoc/js/index.adoc
vertx-web/src/main/asciidoc/kotlin/index.adoc
vertx-web/src/main/asciidoc/ruby/index.adoc
vertx-web/src/main/java/examples/WebExamples.java

To avoid confusion, use #post method in the documentation to bind the form login handler.

Doc fix: FormLoginHandler expects POST requests

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClientOptions.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientOptionsTest.java

this method is necessary for properly `WebClientOptions` serialization
see vert-x3/vertx-consul-client/issues/19

WebClientOptions.toJson() method

---

vertx-template-engines/vertx-web-templ-pebble/pom.xml
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/PebbleTemplateEngine.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleVertxLoader.java
vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-template5.peb
vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java
vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/extension/TestExtension.java
vertx-web/src/main/asciidoc/java/index.adoc
vertx-web/src/main/java/io/vertx/ext/web/package-info.java

When someone is [extending Pebble](http://www.mitchellbosecke.com/pebble/documentation/guide/extending-pebble) by using own Filters or Functions, he has to be able to pass-in a custom PebbleEngine. I added a new constructor and create-method for this. To be able to access the PebbleVertxLoader, I had to increase the visibility of that class to public. Alternatively I though about adding a PebbleEngine.Builder instance instead and force the Loader to VertxLoader in the PebbleTemplateEngineImpl-constructor, but this would prevent the rare usecase when someone actually needs to provide it's own loader.
I also bumped the version of the pebble-dependency to 2.3.0.

Allow usage of custom PebbleEngine

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/BridgeEventType.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
vertx-web/src/main/java/io/vertx/ext/web/package-info.java

Adds a bridge event that fires after the lastPing timestamp is updated.
Fixes #280.

Enhancement: Added BridgeEventType#SOCKET_PING

---

vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java

The handler might never get called.

Do not use bodyEndHandlers for resource cleanup

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Fixes #434. This will cause already broken applications to break in a more obvious manner, which I think is a good thing.

Throw IllegalStateException instead of just warning when setting Route handlers more than once

---

vertx-web/src/test/java/io/vertx/ext/web/WebTestBase.java

This fixes most template engine tests failing on Windows if git autocrlf is enabled (default). Directly comparing the buffer strings broke the test, so I opted to normalize the buffer (adapted from Netty's LineBasedFrameDecoder) instead. I don't forsee any issues with this change, as different styles of line endings are irrelevant in tests anyways.

Normalize line endings for comparing responses in tests

---

vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/impl/FreeMarkerTemplateLoader.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleVertxLoader.java
vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java

Also add an optional charset argument to Utils#readFileToString, defaulting to the original UTF-8.
All of the other template engine loaders (Handlebars, Jade, MVEL, Thymeleaf) use this method, so it makes sense to convert the remaining 2 for consistency reasons.

Make FreeMarker and Pebble template loaders use Utils#readFileToString

---

vertx-web/src/main/java/io/vertx/ext/web/handler/CSRFHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java

I ended up doing both suggestions. Let me know what you think.
Also, I'm by no means a vert.x expert, so I'd like your confirmation that what the new `forbidden` method does is correct.

Fix issue #593: Allow custom CSRF 403 response body

---

vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/impl/FreeMarkerTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-freemarker/src/test/java/io/vertx/ext/web/templ/FreeMarkerTemplateTest.java
vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/impl/HandlebarsTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateTest.java
vertx-template-engines/vertx-web-templ-jade/src/main/java/io/vertx/ext/web/templ/impl/JadeTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-jade/src/test/java/io/vertx/ext/web/templ/JadeTemplateTest.java
vertx-template-engines/vertx-web-templ-mvel/src/main/java/io/vertx/ext/web/templ/impl/MVELTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-mvel/src/test/java/io/vertx/ext/web/templ/MVELTemplateTest.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java
vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/impl/ThymeleafTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-thymeleaf/src/test/java/io/vertx/ext/web/templ/ThymeleafTemplateTest.java
vertx-web/src/main/generated/io/vertx/rxjava/ext/web/templ/TemplateEngine.java
vertx-web/src/main/groovy/io/vertx/groovy/ext/web/templ/TemplateEngine.groovy
vertx-web/src/main/java/io/vertx/ext/web/templ/TemplateEngine.java
vertx-web/src/main/java/io/vertx/ext/web/templ/impl/CachingTemplateEngine.java
vertx-web/src/main/resources/vertx-web-js/template_engine.js
vertx-web/src/main/resources/vertx-web/template_engine.rb

Attempts to resolve #417 .
My approach is to detect a system property (`-Dvertx.web.disableTemplCaching=true`) to disable template caching via the CLI. This plays well during development. I avoided putting in `setCachingEnabled(boolean)` on the TemplateEngines as I couldn't think of a use case when we would want to toggle template caching throughout the lifetime of the server. However, if that is desired, then the basic logic is pretty much there to implement that.
Similar to how the Thymeleaf library implements internal caching of templates, the Jade and Pebble libraries perform internal caching. I left the Jade and Pebble TemplateEngine implementations as derived classes of CachingTemplateEngine to avoid breaking backward compatibility, but in the future, these can look more like the …

Disable template caching for development

---

vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/impl/HandlebarsTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-handlebars/src/test/filesystemtemplates/test-handlebars-template7.hbs
vertx-template-engines/vertx-web-templ-handlebars/src/test/filesystemtemplates/test-handlebars-template8.hbs
vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateTest.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/TemplateHandlerImpl.java

Passes templateDirectory in TemplateHandlerImpl to the Handlebars Loader implementation, allowing for inheritance that matches the official handlebars.java behavior ([which was a bit of a pain to research](https://github.com/jknack/handlebars.java/blob/83e8400da8dfc1820ec1f4523f51505e85abc0c1/handlebars/src/main/java/com/github/jknack/handlebars/io/AbstractTemplateLoader.java#L60)). 
The path prefix is only for the root template directory like the official implementation, NOT the directory for the currently rendered template. Additionally, this supports a specific nested directory edge case (e.g. templates/templates/templates/main.hbs) that will break with the startsWith check proposed earlier. However, this change will break existing templates that specify the whole path (which are very …

Fix inheritance for HandlebarsTemplateEngine

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

Fix losing query parameters for SSL requests (issue #563)

---

vertx-web/src/main/java/io/vertx/ext/web/package-info.java

The documentation of `Serving static resources` is misleading, If the static handler is configured as `router.route("/static/*").handler(StaticHandler.create())` it will serve the static content from `webroot` directory, instead of `webroot/static` as stated in the docs.
please refer to the ![screenshot](https://cloud.githubusercontent.com/assets/5792205/25609978/014537d4-2f54-11e7-97fc-c378c50f4d88.png)
related issue on `vertx-web`  [here](https://github.com/vert-x3/vertx-web/issues/419)
and the actual code which remove the `prefix` for static resources [here](https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java#L361)

update docs for StaticHandler

---

vertx-web/src/main/asciidoc/js/index.adoc
vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/package-info.java

was: 
router.route("/eventbus").handler...
changed to:
router.route("/eventbus/*").handler...

typo on multiple lines fixed

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/BridgeEvent.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BridgeEventImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java

BridgeEvent#rawMessage() should be removed since 3.3
```java
/**
* Use {@link #getRawMessage()} instead, will be removed in 3.3
*/
@Deprecated
@CacheReturn
JsonObject rawMessage();
```

Removes deprecated BridgeEvent#rawMessage()

---

vertx-web/src/main/asciidoc/groovy/index.adoc
vertx-web/src/main/asciidoc/java/index.adoc
vertx-web/src/main/asciidoc/js/index.adoc
vertx-web/src/main/asciidoc/ruby/index.adoc
vertx-web/src/main/java/io/vertx/ext/web/package-info.java

The documentation of Serving template resources is misleading, If the template handler is configured as router.route("/dynamic/*").handler(TemplateHandler.create(HandlebarsTemplateEngine.create())) it will serve the dynamic content from templates directory, instead of templates/dynamic as stated in the docs.
and following are related issues:
https://github.com/vert-x3/vertx-web-site/issues/192
https://github.com/vert-x3/vertx-web/issues/419
https://github.com/vert-x3/vertx-web/pull/618
Signed-off-by: Chengen Zhao <chengen.zhao@mail.mcgill.ca>

Update docs for TemplateHandler

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/HandlerExceptionTest.java

Run the web client handler on the vert.x context
The test checks that:
* the handler is called on the event loop
* the exception thrown by the handlers are reported to the global exception handler

Run the web client handler on the vert.x context

---

vertx-web/src/main/java/io/vertx/ext/web/impl/ParsableMIMEValue.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Fixes #639 
Last step before looking at the parameters should be to check if user accepts anything

produces() ignores Accept: */* when charset is present

---

vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

To allow users to avoid conflicts between path parameters and query parameters, I created a query parameters getter.
Unfortunately i can't return from `queryParams()` a `Map<String, List<String>>` because of this: https://github.com/vert-x3/vertx-codegen/blob/master/src/main/java/io/vertx/codegen/ClassModel.java#L424
So:
* `queryParams()`returns a `Map<String, String>.` If one query parameter is an array It will return as a comma separated list
* `queryParam(name)` returns a `List<String>`, containing the query parameter value/values
I also wrote a small unit test to test this getter

Added query parameters getter inside RoutingContext

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Following this [google groups post](https://groups.google.com/forum/?fromgroups=#!topic/vertx-dev/jBCuyzb8Yls), I implemented the multiple handlers support:
```java
router.get("/path").handler(routingContext -> {
routingContext.put("response", "handler1");
routingContext.next();
}).handler(routingContext -> {
routingContext.put("response", routingContext.get("response") + "handler2");
routingContext.next();
}).handler(routingContext -> {
HttpServerResponse response = routingContext.response();
response.setChunked(true);
response.end(routingContext.get("response") + "handler3");
});
```
There is only one downside. In the code above, you will use the same Route object, while in the code below you create 3 different Route objects:
```java
router.get("/path").handler(routingContext -> { …
```

Added multiple handlers support inside route object

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java
vertx-web/src/test/java/io/vertx/ext/web/handler/SockJSSessionTest.java

SockJS currently listens to data which maps to WebSocket frames. Frames
are a low-level WebSocket transport mechanism which will quite
frequently map to fragmented WebSocket messages.
The following screenshot shows what a fragmented message looks like on the wire. Notice that the `FIN` flag is not set (see https://tools.ietf.org/html/rfc6455#section-5.2 for reference).
Luckily, vertx-core already supports a `textMessageHandler` which does the heavy lifting of stitching together fragmented frames into messages.
Fixes https://github.com/eclipse/vert.x/issues/1751

Support fragmented WS messages

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/XhrTransport.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSAsyncHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSProtocolTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSSessionTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSTestBase.java

SockJS XHR transport tries to register a body handler
(rc.request().bodyHandler(buff -> {})). This doesn't work when using an async
handler before the SockJS handler.
Fixes #654

Async handler before SockJS handler breaks XhrTransport

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ResponseContentTypeHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ResponseTimeHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/ResponseContentTypeHandlerTest.java

Fixes #669
Use RoutingContext.addHeadersEndHandler instead of HttpServerResponse.headersEndHandler
Also, updated ResponseTimeHandler to use:
- System#nanoTime as a matter of accuracy
- an optimized CharSequence header name instead of String

ResponseContentTypeHandler does not work well with other handlers

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java

This does not introduce any breaking change, all the tests are still valid and untouched. The need for this change if for the cases where you want to have a handler **after** the static handler, say a catch all.
These kind of handlers are required for many SPA frameworks which use url paths to perform internal navigation.

use ctx.next instead of fail 404

---

vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-template-i18n.peb
vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java
vertx-template-engines/vertx-web-templ-pebble/src/test/resources/messages_de_DE.properties
vertx-template-engines/vertx-web-templ-pebble/src/test/resources/messages_en_US.properties

Forward user's preferred locale to `PebbleTemplateEngine` so one can use [Pebble's i18n function](http://www.mitchellbosecke.com/pebble/documentation/function/i18n) for localization by setting the `Accept-Language` header.

Support i18n for vertx-web-templ-pebble

---

vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/impl/PebbleTemplateEngineImpl.java

The [Pebble documentation](http://www.mitchellbosecke.com/pebble/documentation/guide/basic-usage) states that when you evaluate a template, you can assign values to variables (e.g. `{{ foo }}`) by providing a context object.
The context object referred to in the documentation is "just a map of variables", however the context object passed here is a RoutingContext meaning that in order to access the value for key `foo`, you'd have to do `{{ context.get("foo") }}` instead of the documented `{{ foo }}`.
A simple fix for this would be to add the items defined in `context.data()` to `variables` so that they can be properly evaluated.
See [#698](https://github.com/vert-x3/vertx-web/issues/698)

Make PebbleTemplateEngine properly evaluate variables

---

vertx-web/src/main/java/io/vertx/ext/web/sstore/SessionStore.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/ClusteredSessionStoreImpl.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/LocalSessionStoreImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/BasicAuthHandlerTest.java

The current AsyncResult<Boolean> is confusing, and the result doesn't provide any information that's not present in succeeded()/failed().
Fixes #388. This may cause an API breakage if applications use result() (which they shouldn't be doing), as mentioned in the linked issue. The cluster implementation result always returns false while the local implementation result always returns true, and developers should be using succeeded()/failed() instead.

Make SessionStore put, clear, delete take in AsyncResult<Void> instead

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/HeaderParser.java
vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java

The first part of the content-type header should be case insensitive.
This is already correctly implemented in the Http(2)ServerRequestImpl.
We detected this problem when upstepping from vertx 3.2 where the behavior of vertx was correct.

Content-type should be case insensitive.

---

vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
vertx-web-api-contract/src/test/resources/swaggers/testOrderSpec.yaml
vertx-web-api-contract/src/test/resources/swaggers/test_order_spec.yaml

By feeding operations to router in the same order as they appear in the spec, allows correct override from specific / wildcard paths.
Given this sample routes:
GET /product/special
GET /product/{id}
If they are not added in this specific order to router, /product/special will never be called.
(sorry, had to reopen as another PR, original was #754)

Keeping operation order as they appear in the spec

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerTest.java

Fixes #742
Websocket upgrades are a special case: Netty does not emit a LastHttpContent event so the request endHandler is never invoked.

BodyHandlerImpl does not call RoutingContext#next for WebSocket upgrade requests

---

vertx-template-engines/vertx-web-templ-jade/src/main/java/io/vertx/ext/web/templ/impl/JadeTemplateEngineImpl.java

Source from pebble engine:
```
final Map<String, Object> variables = new HashMap<>(1);
variables.put("context", context);
// Pass defined variables in context to engine
variables.putAll(context.data());
```
Seems that variables.putAll(context.data()) was missed in Jade engine

Unify template engines

---

vertx-web-client/src/test/java/io/vertx/ext/web/client/Rx2Test.java

Testcases were supposed to provide reproducible code of an issue submitted here: #772. 
Rx java 2 version was added based on `RxTest.java` + error handling scenario to both rx1 & rx2 variants. Maybe those could be useful for spotting any potential regression.

WebClient Rx error handling testcases

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSSocket.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSocketBase.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerTest.java

As explained here #809 and here #804

Fixed SockJS closure with correct close status code

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java

See eclipse/vert.x#2080 for the benefits

RountingContext#getBodyAsJsonXXX create unnecessary intermediate String

---

vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/Router.java
vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/test/java/io/vertx/ext/web/RoutingContextNullCurrentRouteTest.java
vertx-web/src/test/java/io/vertx/ext/web/WebTestBase.java
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSTestBase.java
vertx-web/src/test/java/io/vertx/ext/web/sstore/ClusteredSessionHandlerTest.java

Currently to use a router on a http server, one must use a method reference. Why not just have the router extend the `Handler<HttpServerRequest>` interface though?

Avoid having method references which makes the usage cleaner IMHO

---

vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java

#865 Allow handlers for all routes to be added in order to the router before any other routes are added.
Signed-off-by: Paul Seddon <paul.seddon@gmail.com>

Fix #865 Add global handlers to be added to router before swagger routes.

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/HttpStatusException.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CustomAuthHandlerTest.java

On failure to verify credentials using an AuthProvider, the
AuthHandlerImpl's handle() method now includes the cause for the failure
in the HttpStatusException it passes to processException().

Include root cause in HttpStatusException.

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

This issue requires bad behavioured clients to make HTTP requests that do not follow the HTTP RFC

Fixes #908

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

This is essentially caused by calling the user-supplied RoutingContext handler in the synchronization block of RouteImpl, in addition to two conditions that can happen.
1. A handler may decided to release the synchronization lock on previous RouteImpl instances by scheduling an event, and regain the synchronization lock on the current RouteImpl only.
2. When a handler calls fail directly or indirectly because of exception in the handler, the scanning of failure handlers will go back to the first RouteImpl in RouterImpl, which requires gaining the synchronization lock of previous RouteImpl instances.
Imagine we have two threads and two RouteImpl instances, Route1 and Route2, in RouterImpl:
Thread 1: Lock Route1, Lock Route2, Release Route1 and Route2 due to scheduling an event, Lock Route2 …

Fix a potential deadlock case in failure handling

---

vertx-web/src/main/java/io/vertx/ext/web/impl/ParsableHeaderValue.java
vertx-web/src/test/java/io/vertx/ext/web/impl/ParsableHeaderValueTest.java

Fixes #926. According to RFC 2045 article 5.1, "Matching of media type and subtype is ALWAYS case-insensitive". This pull request replaces equals to equalsIgnoreCase, in the content type comparison.

Header values comparation case insensitive

---

vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/contract/RouterFactoryOptionsConverter.java
vertx-web-client/src/main/generated/io/vertx/ext/web/client/WebClientOptionsConverter.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClientOptions.java
vertx-web/src/test/java/io/vertx/ext/web/WebTestWithWebClientBase.java

Hi,
as reference please look at https://github.com/eclipse/vert.x/pull/2479
as suggested by @vietj this pull-request enables to set setIdleTimeoutUnit.
Cheers !

Provide property propagation for 2376

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BaseTransport.java
vertx-web/src/test/sockjs-protocol/sockjs-protocol-0.3.3.py

Fixes #649
Does not override CORS headers if headers have been set by for example the CORS handler. It also respects the requirement that user credentials are not allowed for wildcard origin

Do not override CORS for SockJS

---

vertx-web/src/main/java/io/vertx/ext/web/handler/FormLoginHandler.java

It should say it retrieve the return url from the session, not from the form attribute

Typo: in FormLoginHandler, the DEFAULT_RETURN_URL_PARAM comment is wrong

---

vertx-template-engines/pom.xml

Rocker 24.0 added support for Java 9: https://github.com/fizzed/rocker/pull/82
6360352319764bc60264b881eae5d0d34b62f2f9 upgraded the Rocker dependency to version 24.0, so we can remove the separate Java 8 profile

Enable Rocker templating for Java 9

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpResponse.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpResponseImpl.java

Javadoc: HttpResponse bodyAs methods return null if body codec is not "Buffer"

---

vertx-template-engines/vertx-web-templ-pebble/pom.xml
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/PebbleTemplateEngine.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/JsonArrayAttributeResolver.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/JsonObjectAttributeResolver.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/VertxAttributeResolverExtension.java
vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-template6.peb
vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-template7.peb
vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-template8.peb
vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java

This change adds the resolving logic for JsonObject and JsonArray to pebble which I have already added to handlebars.

Update pebble and add vert.x json object/array resolving support

---

vertx-web-api-contract/src/main/asciidoc/index.adoc
vertx-web-api-contract/src/main/java/examples/OpenAPI3Examples.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactory.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/impl/BaseRouterFactory.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java

* addHandler(HttpMethod, String, Handler)
* addFailureHandler(HttpMethod, String, Handler)
* setValidationFailureHandler(Handler) (Replaced by RouterFactoryOptions)
* enableValidationFailureHandler(boolean) (Replaced by RouterFactoryOptions)
* mountOperationsWithoutHandlers(boolean) (Replaced by RouterFactoryOptions)

Removed deprecated methods from vertx-web-api-contract

---

vertx-web-api-contract/pom.xml
vertx-web-api-contract/src/test/resources/swaggers/schemas_test_spec.yaml

Note now that relative refs are solved from openapi spec directory as it should, not from current directory of jar/project

Updated swagger-parser to 2.0.5

---

vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ParameterType.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/RegularExpressions.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/HTTPRequestValidationTest.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/WebTestValidationBase.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/impl/StringTypeValidatorTest.java

Add validation on uuid for Web APi Contract
I know that format is an open value but UUID is a classical and standard format.
Today for public API which want to use a UUID in format, can't. We need to add hack by using pattern field but not compliant with everybody.
Another thing today for clients of API which add format uuid in their request: not only it's not supported but we can't pass validation stage (due to an exception).
Please consider this PR.
In parallel fix issue  #1003 pending the new version of the validation.
Documentations:
[OAS](https://swagger.io/specification/#dataTypes) 
[Data Types specification](https://swagger.io/docs/specification/data-models/data-types/)

[Web Api Contract] Add UUID validation parameter

---

vertx-web-api-contract/src/main/asciidoc/dataobjects.adoc
vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/contract/RouterFactoryOptionsConverter.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java

Similar to #1000, the idea is to expose configuration (and thus also extension properties) to the routing context, so that it can be used in the code

Expose openAPI model to routing context

---

vertx-web-api-contract/src/main/asciidoc/index.adoc
vertx-web-api-contract/src/main/java/examples/OpenAPI3Examples.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java

Added the possibility of reading a private OpenAPI specification.
Closes #1068

Allow authorization values when reading a remote openapi spec

---

vertx-web-api-contract/src/main/asciidoc/dataobjects.adoc
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactory.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/impl/BaseRouterFactory.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ParametersUnitTest.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3SchemasTest.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/OpenAPI3ServiceProxiesTest.java

Moved from `RouterFactoryOptions` to `RouterFactory`:
- `setValidationFailureHandler(Handler<RoutingContext> validationFailureHandler)`
- `setNotImplementedFailureHandler(Handler<RoutingContext> notImplementedFailureHandler)`
- `setBodyHandler(BodyHandler bodyHandler)`
- `addGlobalHandler(Handler<RoutingContext> globalHandler)`
- `setExtraOperationContextPayloadMapper(Function<RoutingContext, JsonObject> extraOperationContextPayloadMapper)`

Moved some handlers configurations (back) to RouterFactory

---

vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

fix: take into account new AsyncFile.setReadLength in WebClientTest

---

vertx-web-client/src/main/asciidoc/index.adoc
vertx-web-client/src/main/java/examples/WebClientExamples.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

Added to interface and implementation with tests:
- `HttpRequest.basicAuthentication(String id, String password)` to configure the request with basic access authentication.
- `HttpRequest.bearerTokenAuthentication(String bearerToken)` to configure the request with bearer token authentication.

Basic access and bearer token authentication mechanisms

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSession.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSAsyncHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSSessionContextTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSSessionTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSStreamTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSTestBase.java

Fixes #1135
InboundBuffer expects writes to happen on the creating context.
So it should be captured and use to queue buffers instead of the transport context.
Also, fixed an issue with listener which can be null.

Subsequent SockJS xhr/xhr_send causes IllegalStateException

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

#1168 
Change the delimiter in the basicAuthentication method from a hyphen to a colon.

Update basicAuthentication method so that it matches protocol standards

---

vertx-web-api-contract/src/main/asciidoc/dataobjects.adoc
vertx-web-api-contract/src/main/asciidoc/index.adoc
vertx-web-api-contract/src/main/java/examples/OpenAPI3Examples.java
vertx-web-api-contract/src/main/java/examples/ValidationExamples.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactory.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/BaseValidationHandler.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java

I've deprecated methods inside `RouterFactory` to manage failures. Now users should use new `Router.errorHandler()` method.
Also reworked the documentation to explain validation error handling and other options of router factory
@pmlopes Do you think it's fine to change the default option of mount validation error handler? It's a breaking change but if I don't change it users must explicitly set false this option to use new router method https://github.com/vert-x3/vertx-web/compare/api_contract_error_handlers?expand=1#diff-a17269788004fa9cad18b88e36172080R26

API Contract error handlers adapted to new Router error handling

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java

Currently if the uri inside the authorization header does not match the request uri the auth succeed. I think this is wrong, please review my patch

digest auth: uri in authorization header must match request uri

---

vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/impl/RequestParameterImpl.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ParameterTypeValidator.java
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/EnumTypeValidator.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ValidationTest.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/impl/EnumTypeValidatorTest.java
vertx-web-api-contract/src/test/resources/swaggers/validation_test.yaml

EnumTypeValidator correctly accepts different types for allowedValues other than List<String>

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java

nonce count is an hex number so parse as such.
Fix auth failure if nonce count contains hex letters

digest auth: parse nonce count as hex

---

vertx-template-engines/vertx-web-templ-pebble/pom.xml
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleVertxAttributeResolver.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleVertxExtension.java
vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-template3.peb
vertx-template-engines/vertx-web-templ-pebble/src/test/resources/somedir/test-pebble-template2.beb
vertx-template-engines/vertx-web-templ-pebble/src/test/resources/somedir/test-pebble-template2.peb

This way JsonObject and JsonArray can be accessed used dot notation in templates.
This is an incompatible change, see the changes for the test cases. To make it backward compatible we need to change the order in `getAttributeResolver`, this could result in  small performance penality.
I updated pebble to 3.0.9 too.

pebble: add extension to resolve JsonArray and JsonObject

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

When a request is closed while it is being processed, the router should
not try to write a 500 Internal Server error, as this will trigger a new
failure.

fix: router handle failure of closed responses

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FormLoginHandlerImpl.java

The form login handler checks if the request is set to expect multipart.
If this property of the request is set to false, an exception is thrown.
Previously, the exception's description message suggested adding a
BodyHandler. The new message suggests setting expect multipart to true.

Changed exception message (#1274)

---

vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
vertx-web/src/test/java/io/vertx/ext/web/WebTestBase.java

Manage route match failures using appropriates status code 400, 404, 405, 406 & 415
Fixes #456, #1301, #1295
Replaces #458 & #1298, Partially replaces #606
@pmlopes We want to target for 3.8 or 4?

Correct status code when route matching fails

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

In PR #1305 I don't correctly handle various match failure status codes with multiple routes. This should fix it

Fix for Route#matches status codes

---

vertx-web/src/main/java/io/vertx/ext/web/handler/DigestAuthHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/DigestAuthHandlerTest.java

Stores the nonces in a local shared data map. This allows scaling over a single verticle.
Needs to go as 4.0 because it breaks the factory method.

Fixes: #1212

---

vertx-web/src/main/java/io/vertx/ext/web/handler/CSRFHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java

this way csrf errors can be handled specifically in 403 error handlers

CSRFHandler: thrown a custom exception

---

vertx-web/src/main/java/io/vertx/ext/web/handler/JWTAuthHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java

Deprecate the skip param on JWT as it goes against the security of the application and interferes with the router work.

Fixes #767

---

vertx-web/src/main/java/io/vertx/ext/web/Route.java
vertx-web/src/main/java/io/vertx/ext/web/Router.java
vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/SubRouterTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSProtocolTest.java

This is an alternative to: #1376 
The differences are subtle, while the previous approach was merging routers, this approach is more conservative. It still keeps routers independent and fixes mounting on parameterized paths.
For example:
```java
root.mountSubRouter("/prefix/:var", subRouter)
```
Will work as well as adding routes to `subRouter` later on. However there are a few caveats:
~~1. the whole path is not verified at build time root: `/:id` + `/child/:id` will be allowed and cause problems at runtime (this wouldn't happen with the previous approach)~~
2. pure regex paths will not work: `/.*` + `/:id` can't be handled (worked with the previous approach)
3. the matching method now requires a few extra steps to keep the location of the end of the root router
4. the `mountPoint` is …

Sub router and mount fix for parameterized paths

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java

@cescoffier @vietj this PR might address https://github.com/quarkusio/quarkus/issues/4173
Currently we do a synchronized on all TCCL switch and tuning updates, however the lock happens at the methods that might invoke these operations.
This PR isolates the locks. It only locks on TCCL switch if there's a classloader involved. It only locks on tuning if tuning is active.
It might fix the issue, but I haven't tested the quarkus issue.

Avoid synchronized

---

vertx-web/src/main/java/io/vertx/ext/web/handler/StaticHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java

As OSGi support is dropped from 4.0 the static handler factory with class loaders and constant switch of class loader in that situation is dropped. To serve classpath resources, the advised alternative is to add the resources of the application class path at startup.

Cleanup classloaders

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterState.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java

This PR will remove all locking from the hotpath by introducing a copy on write state for routes and routers.
All mutations are now more expensive (with synchronized blocks) however these should happen mostly all at startup and almost never at runtime.
At runtime the state is locked so all acesses do not need synchronized blocks or locking.

Removed all locks from the hotpath

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CookieHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java

In master date parsing was already using the new time API which is thread safe.
Fixes #1429

Backport new date header parsing from master

---

vertx-web-api-contract/pom.xml
vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3MultipleFilesValidationTest.java
vertx-web-api-contract/src/test/resources/swaggers/multi-files-oas3/references.oas3.yaml
vertx-web-api-contract/src/test/resources/swaggers/multi-files-oas3/validation_test.yaml

* move Swagger-parser to version 2.0.14 #1363
* Added tests that ensure the proper handling of OAS3 with multiple files
Only after the release of swagger-parser v3.12 it is possible to deal
with #ref in parameters.
* Fixed NullPointerException thrown while running the added tests.
The exception is being caused by if (parameter.getExplode());
Also I've reduced the method's Cognitive Complexity suggested by
SonarQube;
(cherry picked from commit ce534335c223c6f84fa54be9e7602ed4fd4f3405)

move Swagger-parser to version 2.0.14 (Backport for 3.8)

---

vertx-web/src/main/java/io/vertx/ext/web/Router.java
vertx-web/src/main/java/io/vertx/ext/web/impl/ForwardedParser.java
vertx-web/src/main/java/io/vertx/ext/web/impl/HttpServerRequestWrapper.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/ForwardedTest.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Signed-off-by: zenios <dimitris.zenios@gmail.com>
This PR adds support for the following "forward" type headers
- Forwarded host,
- Forwarded proto
- Forwarded for
- X-Forwarded-Ssl
- X-Forwarded-Proto
- X-Forwarded-Host
- X-Forwarded-Port
- X-Forwarded-For
parsing can be enabled / disabled (Disabled by default) through a fluent function on Router 
While implementing that, i found out that RoutingContextImplBase which is extended from RoutingContextWrapper and RoutingContextImpl was creating a new instance of HttpServerRequestWrapper on its constructor but RoutingContextWrapper does not need it. So i refactored that part also

Support for "forwarded"-type headers

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ErrorHandlerImpl.java

Check if the route has matched an acceptable content type, when guessing a suitable error mime type.

Use route acceptableContentType as error mime type

---

vertx-web-common/src/main/java/io/vertx/ext/web/codec/impl/BodyCodecImpl.java

BodyCodec converts json buffer to string before decoding value to specified type.

BodyCodec: avoid unneccesary json/string conversion

---

vertx-web-client/pom.xml
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientDatabindTest.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTestBase.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/it/WebClientDatabindTest.java

Put databind dependent tests in separate execution

WebClient: moved jackson-databind from compile to test scope

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java

The currentRoute object can be null.
Previously `getCurrentRoute()` then returned a null, after 17860ef4 it triggers an NPE.

Fix NPE on RoutingContext#getCurrentRoute()

---

vertx-web/pom.xml
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java

run test under non UTF-8 as default charset , will reproduce the problem
ie: `mvn test -Dtest=StaticHandlerTest#testContentHeadersSet -Dfile.encoding=GBK`
==>
```
Starting test: StaticHandlerTest#testContentHeadersSet
org.junit.ComparisonFailure: expected:<text/html;charset=[UTF-8]> but was:<text/html;charset=[GBK]>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:354)
at io.vertx.ext.web.handler.StaticHandlerTest.lambda$testContentHeadersSet$1(StaticHandlerTest.java:147)
```
Or should we add ` <surefireArgLine>-Dfile.encoding=UTF-8</surefireArgLine>` on vertx-parent pom.xml ? 
And where is the vertx-parent git repo?

fix default charset issue at `StaticHandlerTest#testContentHeadersSet`

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FormLoginHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/RedirectAuthHandlerTest.java

This PR fixes #1490 where a wrong HTTP status code is returned for failed authentications handled by `FormLoginHandlerImpl`

fix wrong http status for failed form authentication

---

vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java
vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java

This commit adds a new SessionHandler option : lazySession. With this option set, the session is still (re)created in the SessionHandler.handle(...) but not always stored in the sessionStore.
The RoutingContext is now responsible to track whether the session has been accessed. In that case the new accessedSession() method must return true.
Thanks to this new RoutingContext.accessedSession() method, the SessionHandler is able to know whether the session has been accessed and to decide whether it has to store it.
Motivation:
The goal of this PR is to have a mean to stop vert.x SessionHandler to always create a session Cookie.
In some cases, application built with Vert.x doesn't know in advance if they will use the session, and if not, may not want to be treated like a stateful application …

Add a Lazy Session option for the SessionHandler

---

vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/handler/OAuth2AuthHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/OAuth2AuthHandlerTest.java

currently adding required oauth2 scopes requires the user to fiddle with untyped json config. This pull request will make the api self documenting and type safe.

Add a type safe extra parameter for scopes

---

vertx-web-api-contract/pom.xml

Fixes #1528 & Fixes #1538
Dep tree:
```
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ vertx-web-api-contract ---
[INFO] io.vertx:vertx-web-api-contract:jar:4.0.0-SNAPSHOT
[INFO] +- io.vertx:vertx-web:jar:4.0.0-SNAPSHOT:compile
[INFO] |  +- io.vertx:vertx-web-common:jar:4.0.0-SNAPSHOT:compile
[INFO] |  +- io.vertx:vertx-auth-common:jar:4.0.0-SNAPSHOT:compile
[INFO] |  \- io.vertx:vertx-bridge-common:jar:4.0.0-SNAPSHOT:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.2:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.10.2:compile
[INFO] +- com.networknt:json-schema-validator:jar:1.0.31:compile
[INFO] |  \- org.apache.commons:commons-lang3:jar:3.5:compile …
```

Updated json-schema-validator

---

vertx-web/src/main/java/io/vertx/ext/web/AllowForwardHeaders.java
vertx-web/src/main/java/io/vertx/ext/web/Router.java
vertx-web/src/main/java/io/vertx/ext/web/impl/ForwardedParser.java
vertx-web/src/main/java/io/vertx/ext/web/impl/HttpServerRequestWrapper.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterState.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/test/java/io/vertx/ext/web/ForwardedTest.java

Motivation:
Current forward parsing is not strict and may allow users with bad intentions to bypass bad configured proxy servers.
This is a breaking change as it requires the user to specifically state what kind of parsing should be applied.
Fixes #1519

Make forward header parsing strict

---

vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSHandlerImpl.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GraphQLRequest.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GraphQLTestBase.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/LocaleTest.java
vertx-web-graphql/src/test/resources/locale.graphqls

Fixes #1529
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>
1.I am not sure if it would be better to use io.vertx.ext.web.LanguageHeader inside factory instead of Locale.
2.I could not create test for the websocket implementation since i could not find a way to pass headers (Accept-Language) to httpClient.webSocket

Locale provider for graphql execution

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/test/java/io/vertx/ext/web/VirtualHostTest.java

Motivation:
Fixes #1565 
When mounting a sub router on the ROOT do not throw IllegalStateException

Fix illegalstate when sub router is mounter on root

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CORSHandlerTest.java

Uses `context.fail` instead of `setStatusCode` to allow cors issues being handled by an error handler.
The status message has been changed to the default message for the 403 `Forbidden`
resolves https://github.com/vert-x3/vertx-web/issues/1555

handles invalid cors status with an error handler optionally

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java

rfc2617 section 3.2.2
"""
digest-uri
The URI from Request-URI of the Request-Line; duplicated here
because proxies are allowed to change the Request-Line in transit.
"""
so don't check digest-uri against request uri

digest auth: fix auth behind a reverse proxy

---

vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java
vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java

Backport of #1541.
The goal of this commit is to have a mean to stop vert.x SessionHandler to always create a session Cookie.
In some cases, application built with Vert.x doesn't know in advance if they will use the session, and if not, may not want to be treated like a stateful application by network components (ie Load Balancers).
This commit follows the discussion accessible here : https://groups.google.com/d/msg/vertx/hoQEgU2d_FY/uUu2jdd7AQAJ
This commit adds a new SessionHandler option : lazySession. With this option set, the session is still (re)created in the SessionHandler.handle(...) but not always stored in the sessionStore.
The RoutingContext is now responsible to track whether the session has been accessed. In that case the new accessedSession() method must return true.
Thanks …

backport of #1541 - Add a Lazy Session option for the SessionHandler

---

vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Motivation:
Adds `addEndHandler`, `addExceptionHandler` and `addCloseHandler`
methods to the `RoutingContext` to allow you to create multiple
handlers for the `endHandler`, `exceptionHandler` and
`closeHandler` properties of the `HttpServerResponse`. Handlers
added using the `addEndHandler` will always be called whether
the request fails with an exception or completes normally. It
can therefore be used to perform cleanup on the request.
Signed-off-by: Graeme McRobert <mcrobert@uk.ibm.com>
Conformance:
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidel …

Provide a safe end handler for use to cleanup at request termination

---

vertx-web/src/main/java/io/vertx/ext/web/Router.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java

The return of the mount should be a `Route` this way we can still perform the default route management tasks like `remove` of the router like we do for any other kind of route.

Fixes #1514

---

vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/thymeleaf/impl/ThymeleafTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-thymeleaf/src/test/java/io/vertx/ext/web/templ/ThymeleafTemplateTest.java
vertx-template-engines/vertx-web-templ-thymeleaf/src/test/resources/somedir/test-thymeleaf-fragmented.html

Motivation:
Fixes https://github.com/vert-x3/vertx-web/issues/161
See the discussion there. In short, Vert.x doesn't have servlet context that Thymeleaf depends on. Without this change, it throws exceptions when rendering `@{/path}` in template.
Conformance:

Set default LinkBuilder

---

.travis.yml
vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/NoopBodyProcessorGenerator.java
vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3ValidationHandlerGenerator.java
vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterFactoryIntegrationTest.java
vertx-web-openapi/src/test/resources/specs/validation_test.yaml
vertx-web-validation/src/main/java/io/vertx/ext/web/validation/RequestParameter.java
vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/RequestParameterImpl.java
vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/RequestParametersImpl.java
vertx-web-validation/src/test/java/io/vertx/ext/web/validation/RequestParametersTest.java

Fix #1643
Now for content types where validation is not supported, the router factory will generate a noop processor that just encapsulates the body inside `RequestParameter` as `Buffer`

Noop Body Processor

---

vertx-web-openapi/pom.xml
vertx-web-validation/pom.xml

Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:

Invalid use of project.version for vertx-json-schema

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Motivation:
Fixes: #1647 
Conformance:
HTTP method should be considered as the umbrella for other matching elements after matching the path, like consumes, produces, etc. If it is not a `405` nor `404`, the `matchFailure` should not be updated.

[Issue-1647] Content-Type-based Routing not working properly

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java

This gives a significant performance boost
in situations where it is not needed
Motivation:
Quarkus does not really use the consumes/produces features of the Router, and this object is very expensive to create. A simple plaintext pipelining based benchmark (similar to the techempower one) I saw performance increase from 1.2m req/sec to 1.7m. 
I have submitted this for the 3.9 branch, let me know if you want a new PR for master.

Lazly allocate the ParsedHeaders structure

---

vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterFactory.java
vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3RouterFactoryImpl.java
vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterFactoryIntegrationTest.java

[vertx-web-openapi] Allow users to set body handler as null

---

vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java

Motivation:
Fixes #1691 
Closes #1693
This PR builds on the discussions on the issue. This approach is safer than the previous one as it protect against wrong mime types too.
Documentation has been added warning against the danger of unbounded parsing and where to enforce the limit.

Enforce the limit on the context

---

.travis.yml
vertx-web/src/main/asciidoc/dataobjects.adoc
vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerOptions.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSSocket.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BaseTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventSourceTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/HtmlFileTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/JsonPTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSession.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSocketBase.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/XhrTransport.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSProtocolTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSWriteHandlerTestServer.java
vertx-web/src/test/resources/webroot/sockjs/writeHandler.html
vertx-web/tests/.gitignore
vertx-web/tests/sockjs/.babelrc
vertx-web/tests/sockjs/package-lock.json
vertx-web/tests/sockjs/package.json
vertx-web/tests/sockjs/writeHandler.test.js

Closes #1221 
Also, when registered, make it local only by default.

Disable SockJSSocket writeHandler by default

---

vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/PebbleTemplateEngine.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSession.java
vertx-web/src/test/java/io/vertx/ext/web/WebTestBase.java

Motivation:
Trying to fix #1720
sockjs handler tests fail intermitently with a ISE. The ISE seems to be thrown when a connection is terminated, avoiding full synchronization on the exception handler + ensure that the test cleanly closes clients and then server, seems to not trigger the issue on a 10000 loop iteration of the test.
Before a fail would happen before the 2000th iteration would happen.

Detect race on close of sockjs tests

---

vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Motivation:
Expose the `*` as a path parameter too.

Fixes #1411

---

vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/freemarker/FreeMarkerTemplateEngine.java
vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/freemarker/impl/FreeMarkerTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/handlebars/HandlebarsTemplateEngine.java
vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/handlebars/impl/HandlebarsTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-httl/src/main/java/io/vertx/ext/web/templ/httl/HTTLTemplateEngine.java
vertx-template-engines/vertx-web-templ-httl/src/main/java/io/vertx/ext/web/templ/httl/impl/HTTLTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-jade/src/main/java/io/vertx/ext/web/templ/jade/JadeTemplateEngine.java
vertx-template-engines/vertx-web-templ-jade/src/main/java/io/vertx/ext/web/templ/jade/impl/JadeTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/PebbleTemplateEngine.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/thymeleaf/ThymeleafTemplateEngine.java
vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/thymeleaf/impl/ThymeleafTemplateEngineImpl.java
vertx-web-common/src/main/java/io/vertx/ext/web/common/template/TemplateEngine.java

Motivation:
Fix #1725 
Implement `unwrap` on all engines that have runtime config, defaults to `null` on compile time engines.

Implement unwrap on all known engines

---

vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
vertx-web/src/test/java/io/vertx/ext/web/templ/TemplateTest.java

Motivation:
Extract the rest param to build the file name, not the route path.

Fix #1730: properly extract the rest param as the desired segment

---

vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/BaseRouterFactoryTest.java
vertx-web-validation/src/test/java/io/vertx/ext/web/validation/BaseValidationHandlerTest.java

After the server is closed, the testContext must be completed

Fixed wrong usage of vertx junit5 apis

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

Before this patch WebClientBase was ignoring headers which were passed inside of RequestOptions.

Fix RequestOptions processing in WebClientBase

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java

Just a minor optimisation, if there is no host pattern to match
don't load the host header from the header map.
Motivation:
Even if no host pattern is defined the router will always call load the host header from the map. This avoids this if the host pattern is not defined.

Don't get the host header if no host pattern defined

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/predicate/PredicateInterceptor.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

Signed-off-by: pn-santos <pedro.santos@yoti.com>
**Motivation:**
See #1742 for details.
**Implementation Notes:**
I also added a test (mostly a replica of an existing one with some minor changes) that reproduces the issue (and passes with the fix).

Fixes #1742: Copy HTTP response for no body error converters

---

vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSConnectionInitEvent.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSMessage.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSMessageType.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSConnectionHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSHandlerImpl.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSMessageImpl.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloTestsServer.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloWSHandlerTest.java
vertx-web-graphql/tests/apollo/apollo.test.js

Motivation:
This pull request is enabling handling of connection params with GraphQL subscription, fix #1579
@tsegismont thanks for the review in #1721 , I closed that PR in favor of this one since implementation has substantially changed.

Added handling of connection params in GraphQL subscription

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/predicate/ResponsePredicate.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

Fixes #1583
Ignore charset / boundary on contentType predicates.

Ignore charset / boundary on contentType predicates

---

vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Motivation:
Fix #1494 
Allow parsing of query params in other character encoding than UTF8. Although UTF8 is the norm, for GET requests there is no way to specify the desired character encoding. On Tomcat for example a custom config is required to allow this.
This PR allows specifying the desired character encoding for the decode of the query string, however it will not be cached like the default one. This is to avoid behavior changes in the application or undesired side effects of calling the method with or without character set.

Allow parsing of query parameters with other content encoding than UTF-8

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

Signed-off-by: Rory Steele <rory@scoutimpact.com>
Motivation:
Fixes #1814
An issue was discovered when using vertx-config to login to Vault using the app role mechanism. The user agent header had been disabled and this led to NullPointerExceptions when performing the request.
Conformance:

Fix NPE when sending JSON data and the user agent header is disabled

---

vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/handler/XFrameHandler.java

Motivation:
Fix #1845 
This handler + the existing HSTS are required to properly secure CSRF protected requests.

Added the XFrame Handler

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/ClientPhase.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/MultipartFormUpload.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/InterceptorTest.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/MultipartFormUploadTest.java

Add a new web client _CREATE_REQUEST_ phase between _PREPARE_REQUEST_  and _SEND_REQUEST_.
- `sendRequest` takes now an `HttpClientRequest` as argument instead of `RequestOptions`
- a new `createRequest` method takes `RequestOptions` as argument, triggers the interceptor chain and call `handlePrepareRequest`
- `handleCreateRequest` is created from the portion of `handleSendRequest` that was preparing the request options and body before sending the request. This method uses the HTTP client to create the request and then calls `sendRequest`
- `handlePrepareRequest` now calls `createRequest` instead of `sendRequest`
fixes #1855
fixes #1851

Web client create request phase

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/SubRouterTest.java

When using a hierarchy of router handlers (min depth 3) with `handleContext`, routing fails because the `RoutingContextWrapper` instances end up with duplicate slashes in their `mountPoint`. The reason is that the `RoutingContextWrapper` no longer checks if the `parentMountPoint` ends with a `'/'` (like it did before Vert.x 4). This PR re-adds this check. Also see issue #1853 for details and a reproducer.

mountPoint problems with hierarchical routers

---

vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSSocket.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSession.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSocketBase.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerTest.java

Motivation:
Currently it appears to be nearly impossible to manage/bind sockjs sessions using a normal session store. This should allow accessing routing context from within a sockjs connection in addition to manually creating and restoring of sessions and their associated users from within the sockjs connection.

Expose interfaces for manual sockjs session management.

---

vertx-web/src/main/java/io/vertx/ext/web/Session.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ErrorHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FaviconHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FormLoginHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/WebAuthnHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BaseTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventSourceTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/HtmlFileTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/JsonPTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSession.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/XhrTransport.java
vertx-web/src/main/java/io/vertx/ext/web/impl/ForwardedParser.java
vertx-web/src/main/java/io/vertx/ext/web/impl/HeaderParser.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/AbstractSession.java

Motivation:
In some web handlers failures are signaled just by it's HTTP error code without context. So having an error handler in the cases is not useful as it just shows the error code.
This PR adds a context error to most of the places where handlers are just failing the responses.

Attach an error to a context failure to give better context

---

.github/workflows/ci.yml

By default github cancels matrix tests if one fails, this behavior makes debugging test failures more difficult to isolate as it is not obvious if a failure is common to other tests if they get cancelled automatically.

Disable fail-fast for tests.

---

vertx-web/src/main/java/io/vertx/ext/web/Route.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
vertx-web/src/test/java/io/vertx/ext/web/SubRouterTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/templ/TemplateTest.java
vertx-web/src/test/resources/templates/index.ftl
vertx-web/src/test/resources/templates/sub/index.ftl

Motivation:
This PR attempts to handle issues related to the use of `*` wildcards.
Fixes #1849, #1819
Currently, when calculating path offsets, the `*` param is always taken in consideration, when we should only consider it when a route "explicitly" defines it.

Try to handle star properly

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClientSession.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/CookieStoreImpl.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/spi/CookieStore.java

Motivation:
Fix #1862 
This PR although addresses the lack of the annotation, also uncovered an API design issue. The usage of `Cookie` is referring to `netty` classes, instead of the polyglot/vert.x ones.
@cescoffier @vietj are we happy with just this fix for now, or do you need to fully address the issue and make a breaking change? Note that since the annotations were missing from the beginning users of rx, mutiny, quarkus, etc... would never use the "wrong" types on a normal application. Although power users/framework developers could.

Enable vertxgen

---

vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerTest.java

Motivation:
Allows for setting and flushing a new user to the `RoutingContext` and `SessionStore`.

Add a setUser method to the SessionHandler.

---

vertx-template-engines/pom.xml
vertx-template-engines/vertx-web-templ-jte/pom.xml
vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/JteTemplateEngine.java
vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/impl/JteTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/impl/VertxDirectoryCodeResolver.java
vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/package-info.java
vertx-template-engines/vertx-web-templ-jte/src/main/resources/META-INF/MANIFEST.MF
vertx-template-engines/vertx-web-templ-jte/src/test/java/io/vertx/ext/web/templ/JteTemplateEngineTest.java
vertx-template-engines/vertx-web-templ-jte/src/test/jte/base.jte
vertx-template-engines/vertx-web-templ-jte/src/test/jte/tag/inc.jte
vertx-template-engines/vertx-web-templ-jte/src/test/jte/testTemplate2.jte

Motivation:
Hey, I'm the maintainer of [jte](https://jte.gg), a compile time checked, fast and secure template engine for Java. The main reasons to create jte were productivity, performance and security. All templates are type safe and there's a pretty smart IntelliJ plugin helping with refactorings, completions and formatting. It's also [very fast](https://github.com/casid/jte#performance), since all templates compile to Java and there's no expression language to evaluate. Finally, it provides users with [context-sensitive output escaping](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#html-escaping) and [quality of life when generating HMTL](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#html-rendering).
I've written a vert.x template module for jte and it looks …

Add module to render jte templates

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSocketBase.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSEventBusTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSTestBase.java

Since we can write strings over a sockjs connection we should handle them properly when sent over the eventbus write handler.
This is neccesary if one wants to send text(non-binary) messages using the eventbus write handler.

Sockjs: handle Strings on EventBus.

---

vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/parameter/ParameterProcessorImpl.java
vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/validator/SchemaValidator.java
vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/validator/ValueValidator.java
vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/ParameterProcessorUnitTest.java

given a yaml:
```
paths:
/tryout:
get:
operationId: tryout
parameters:
- in: query
name: namespace
required: false
schema:
$ref: '#/components/schemas/namespace'
components:
schemas:
namespace:
type: string
minLength: 1
```
using `io.vertx.ext.web.openapi.RouterBuilder` and sending `GET /tryout`  the schemaValidation will blow up with the noted exception because `namespace` is `null` and calling `getDefaultValue()` on the schema before any validation fails because its a `RefSchema` and has not been resolved yet.

Schema#getDefaultValue() throws NoSyncValidationException if it is a RefSchema

---

vertx-template-engines/vertx-web-templ-jte/pom.xml
vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/JteTemplateEngine.java
vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/impl/JteTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/impl/VertxDirectoryCodeResolver.java
vertx-template-engines/vertx-web-templ-jte/src/test/java/io/vertx/ext/web/templ/JteCompiledTemplateEngineTest.java
vertx-template-engines/vertx-web-templ-jte/src/test/templates/compiled.jte

Motivation:
`jte` templates support both runtime and compile time compilation. This PR tries to expose both use cases to the vert.x API:
The previous `create` factory work as is. A small change was made to avoid having a "custom" class path entry as with vert.x 4 we wanted to be as static as possible, so we only load code from the classpath jars. 
A new factory was added without arguments. This factory is different in the sense that instead of relying on the runtime it expects the templates to be already compiled **and** available on the current classpath.
Further the `unwrap` method was implemented to allow users to further customize the underlying engine just like on the other implementations.
@casid let me know what you think about this? …

Suggest an alternative for precompiled templates

---

vertx-template-engines/pom.xml
vertx-template-engines/vertx-web-templ-freemarker/pom.xml
vertx-template-engines/vertx-web-templ-handlebars/pom.xml
vertx-template-engines/vertx-web-templ-httl/pom.xml
vertx-template-engines/vertx-web-templ-jade/pom.xml
vertx-template-engines/vertx-web-templ-jte/pom.xml
vertx-template-engines/vertx-web-templ-mvel/pom.xml
vertx-template-engines/vertx-web-templ-pebble/pom.xml
vertx-template-engines/vertx-web-templ-rocker/pom.xml
vertx-template-engines/vertx-web-templ-rythm/pom.xml
vertx-template-engines/vertx-web-templ-thymeleaf/pom.xml

- common shade plugin setup in parent project: all shaded artifacts have the same requirements (embed all dependencies except Netty, Vert.x and Jackson core)
- pebble declares caffeine as excluded but it is not a dependency of the engine
- rocker and thymeleaf are missing a transitive dependency on slf4j
- rythm forces a version of slf4j but it is not a dependency of the engine

Template engines dependency fixes

---

vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java
vertx-web/src/test/java/io/vertx/ext/web/it/RoutingContextDatabindTest.java

Motivation:
By default vert.x `ctx.json()` returns the content type `application/json;charset=UTF-8` however IANA the standards registry states that:
> No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients.

JSON content type should follow IANA registry rules

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java

Fixes: #1919 
Motivation:
Currently, we don't log (with the right level) unhandled exceptions happening on the router. Exceptions could only be seen in `TRACE` level. This isn't really the correct level. This PR moves the level to ERROR and only logs once.

Fix #1919: Log unhandled exceptions

---

vertx-web/src/main/java/io/vertx/ext/web/handler/JWTAuthHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/JWTAuthHandlerTest.java

Motivation:
This completes the deprecation in auth, where JWT scopes are not expected to be used in that module + gets JWT Handler ready for OpenAPI 3.1

Allow scopes in JWT just like in OAuth2

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

See #1926
Troubleshooting will be simplified by creating the VertxException using the MalformedURLException cause.

WebClient: provide MalformedURLException cause when using requestAbs with invalid URL

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/InterceptorTest.java

Motivation:
Now the interceptor index is restarted only when any of the methods using `fire(ClientPhase phase)` are called from within the interceptor function `handle(X)`, but if `fire(ClientPhase phase)` is executed from outside the interceptor function `handle(X)` then the interceptors before the last executed interceptor and this interceptor itself are ignored for the new `phase`.
This change modifies the current logic to always reset the interceptor index.

Reset interceptor index always after call HttpContext `fire` function

---

vertx-web-graphql/src/main/asciidoc/index.adoc

Signed-off-by: chengen.zhao@mail.mcgill.ca <chengen.zhao@mail.mcgill.ca>
Motivation:
Remove redundant tech preview warning apparently this module is not in tech preview status anymore 
previous pr:
https://github.com/vert-x3/vertx-web/pull/1941
Conformance:

Remove redundant tech preview warning

---

vertx-web/src/main/java/examples/WebExamples.java

Signed-off-by: chengen.zhao@mail.mcgill.ca <chengen.zhao@mail.mcgill.ca>
Motivation:
The original comments may not conform to grammatical rules, I think it is because the author miswrote the word "when" to "is" so I change the word and also add in "not" to make sense the whole comments
Conformance:

Improve the comments to more clearly explain what is happening in the code

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/SparseArray.java
vertx-web/src/test/java/io/vertx/ext/web/impl/SparseArrayTest.java

Motivation:
I've noticed some easy and low risk optimisations by running Quarkus 2 previews with the Techempower benchmark;
specifically the use of an inverted sorted `TreeMap` using `Integer` as a key for the sole purpose of iterating the elements in inverse order.
`TreeMap`s aren't particularly efficient, and its internal bucket structure also comes with a cost on top of the obvious `int` wrapping; not least the used iteration required a copy (`values().forEach`)
I don't have much experience with the HTTP layer, but I'm having the impression that this code is also expecting a "dense map", which made me suspect a simple array could be used, at cost of using a sparse array in case of gaps.
Verified with the benchmark, this seems effective; I'm noticing about ~4% less memory being …

Improve memory efficiency of Handlers registration in RoutingContextImpl

---

pom.xml
vertx-web-proxy/pom.xml
vertx-web-proxy/src/main/asciidoc/index.adoc
vertx-web-proxy/src/main/java/examples/WebProxyExamples.java
vertx-web-proxy/src/main/java/examples/package-info.java
vertx-web-proxy/src/main/java/io/vertx/ext/web/proxy/handler/ProxyHandler.java
vertx-web-proxy/src/main/java/io/vertx/ext/web/proxy/handler/impl/ProxyHandlerImpl.java
vertx-web-proxy/src/main/java/io/vertx/ext/web/proxy/package-info.java
vertx-web-proxy/src/main/resources/META-INF/MANIFEST.MF
vertx-web-proxy/src/test/java/io/vertx/ext/web/proxy/WebProxyTestBase.java
vertx-web-proxy/src/test/java/io/vertx/ext/web/proxy/handler/ProxyHandlerTest.java

Signed-off-by: Emad Alblueshi <emad.albloushi@gmail.com>
Motivation:
Vert.x Web Proxy module provides a handler that handles reverse proxy logic using [Vert.x Http Proxy](https://github.com/eclipse-vertx/vertx-http-proxy).
The documentation is added and marked as _Tech Preview_

Vert.x Web Proxy Module

---

vertx-template-engines/pom.xml

Fixes #1952
- Vert.x API of template engine missing (because all io.vertx artifacts were excluded)
- SLF4J included in shaded JAR

Fix template engines shaded artifact generation

---

vertx-web/src/main/java/io/vertx/ext/web/impl/SparseArray.java
vertx-web/src/test/java/io/vertx/ext/web/impl/SparseArrayTest.java

Motivation:
And additional little fix as follow up to my previous pr #1943 - and simplified a little.
In particular it could have thrown an NPE if you attempted to `remove()` on an empty instance - not something that I think anyone would do so, but still..

Simplify SparseArray a bit

---

vertx-web-api-service/src/main/java/io/vertx/ext/web/api/service/generator/WebApiProxyHandlerGen.java
vertx-web-api-service/src/main/java/io/vertx/ext/web/api/service/generator/model/WebApiProxyMethodInfo.java
vertx-web-api-service/src/main/java/io/vertx/ext/web/api/service/generator/model/WebApiProxyModel.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/futures/FuturesService.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/futures/FuturesServiceImpl.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/futures/RouteToEBServiceFuturesHandlerTest.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/futures/package-info.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/generator/WebApiServiceHandlerTest.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/generator/models/futures/ValidWebApiProxyWithFutures.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/generator/models/futures/package-info.java

https://github.com/vert-x3/vertx-web/issues/1948
Motivation:
Add unit test for Furutre<ServiceResponse> proxy methods, fix return-type and parameter checking for same.
Conformance:

add test for @Fluent and for Future<ServiceResponse>

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java

Motivation:
As stated in issue https://github.com/vert-x3/vertx-web/issues/1966 we needed to change back to "protected" the visibility of the `processException` method.
Change method visbility for `AuthenticationHandlerImpl#processException`

[Issue-1966] : Making the method "processException" back to protected 

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java

Motivation:
During sockjs event handler the state of the socket may change. This means that even if a user validation allows the event to proceed, we can only run the `okAction` if the socket is still valid in the sockInfo table.

Fix #1380: Only run success action if socket map state is still valid

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java

Motivation:
in a recent commit logging on INFO was added to RoutingContext  ` public void fail(int statusCode, Throwable throwable)` which is also called from `public void fail(Throwable t) `
see: https://github.com/vert-x3/vertx-web/commit/1fc3000071ac5e11d52e137742324e6042211ebe
IMHO this should be debug logging only and VertX users should handle failures in FailureHandlers added to the route as they see fit. 
Conformance:

routing context fail logging to debug

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java

Motivation:
backport of [this PR](https://github.com/vert-x3/vertx-web/pull/1994) in case there is a 4.1.3
@pmlopes
Conformance:

backport routing context fail logging to debug (https://github.com/vert-x3/vertx-web/pull/1994)

---

vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderImpl.java
vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderTest.java

Create a copy of the JsonObject before making modifications/updating `$ref` values. Fixes #1996 .
Motivation:
As described in #1996, the OpenAPILoadImpl current replaces `$ref`s with absolute file paths. The resulting OpenAPI is not suitable for hosting when using the contract endpoint option (`io.vertx.ext.web.openapi.RouterBuilderOptions#setContractEndpoint`). This change retains the unmodified OpenAPI JsonObject within the `OpenAPIHolderImpl` for retrieval via `getOpenAPI`, which is the source utilized by `ContractEndpointHandler`, activated when setting a contract endpoint to a non-null path.

Retain unmodified OpenAPI JsonObject in OpenAPIHolderImpl

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/OAuth2AuthHandlerTest.java

Motivation:
While checking for simple scopes during the oauth2 handshake a else case was missed.

Generic scope check missed an else statement

---

vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderImpl.java

Signed-off-by: Deven Phillips <deven.phillips@redhat.com>
Motivation:
Resolves https://github.com/vert-x3/vertx-web/issues/1817 by adding an additional case for "https" to `io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl`

Added case for "https" in switch statement

---

vertx-web-api-service/src/main/java/io/vertx/ext/web/api/service/impl/RouteToEBServiceHandlerImpl.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/RouteToEBServiceHandlerTest.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/TestService.java
vertx-web-api-service/src/test/java/io/vertx/ext/web/api/service/TestServiceImpl.java

Motivation:
Fix #1995 
To allow further secure openapi -> eventbus messages, this PR propagates the http authentication header downstream

Fix #1995: propagate the authorization header

---

vertx-web-graphql/src/main/asciidoc/index.adoc
vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ApolloWSHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSConnectionHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSHandlerImpl.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloTestsServer.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloWSHandlerTest.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/DeprecatedLocaleTest.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/DeprecatedVertxBatchLoaderTest.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/DeprecatedVertxMappedBatchLoaderTest.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/LocaleTest.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/QueryContextTest.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/VertxBatchLoaderTest.java
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/VertxMappedBatchLoaderTest.java

Closes #2023
With GraphQL-Java 17, te GraphQLContext object becomes the standard to share contextual data between components of a GraphQL Java application (see https://github.com/graphql-java/graphql-java/releases/tag/v17.0 and graphql-java/graphql-java#2368).
This commit:
- deprecates the current context hooks in Vert.x Web GraphQL handlers
- adds a new hook that allows to manipulate the ExecutionInputBuilder
- updates the docs

Context management with GraphQLContext object

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSErrorTest.java

Motivation:
Registering multiple times the same address on the same socket causes leaks of consumers. and therefore, leaks of sockets.
This PR enforces a single address per socket as clients also agree and now returns an error if multiple registrations happen.

test the fix

---

vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSErrorTest.java

Motivation:
Improve the test based on my previous reproducer: https://github.com/vert-x3/vertx-web/pull/2056 / https://github.com/eclipse-vertx/vert.x/issues/3997

SockJSErrorTest - replace time delay with countdown latch

---

vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3RouterBuilderImpl.java
vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderIntegrationTest.java
vertx-web-openapi/src/test/resources/specs/path_matching_order.yaml

Motivation:
This PR aims at fixing path matching order issues in the OpenAPI RouterBuilder: #1751 
Let this PR be the continuation of https://github.com/vert-x3/vertx-web/pull/1787 that seem to have lost traction.
As mentioned by @slinkydeveloper in https://github.com/vert-x3/vertx-web/pull/1787#discussion_r555932885 I also think the problem can only be fixed by pre-ordering the operations: this is what I've done.
I added a unit test demonstrating the behavior. Commenting out the `.sorted()` in `OpenAPI3RouterBuilderImpl` makes the unit test fail:
```java
List<ResolvedOpenAPI3Path> resolvedPaths = operations
.values()
.stream()
.map(it -> new ResolvedOpenAPI3Path(it, openapi))
.sorted()
.collect(Collectors.toList());
```

Fix #1751: OpenAPI RouterBuilder path matching order

---

vertx-web/src/main/java/io/vertx/ext/web/handler/FileSystemAccess.java
vertx-web/src/main/java/io/vertx/ext/web/handler/StaticHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java

Replaces PR #2099
- added scope RELATIVE or ROOT in constructor
- flagged obsolete properties as deprecated
Motivation:
When creating a static handler with an absolute source path outside the working directory, the code is currently confusing:
```java
StaticHandler.create()
.setAllowRootFileSystemAccess(true)
.setWebRoot("/somedir");
```
after the change the same code will be:
```java
StaticHandler.create(FileSystemAccess.RELATIVE, "/somedir");
```
(P.S. all formatting changes were inflicted by VSCode Quarkus tooling - happy to reconfigure, if guidance can be provided)

StaticHandler root access change (replaces #2099)

---

vertx-web-client/pom.xml
vertx-web-client/src/main/asciidoc/index.adoc
vertx-web-client/src/main/generated/io/vertx/ext/web/client/WebClientOptionsConverter.java
vertx-web-client/src/main/java/examples/WebClientExamples.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClient.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClientOptions.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/ClientUri.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/SessionAwareInterceptor.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/cache/CacheInterceptor.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/cache/CacheKey.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/cache/CacheVariationsKey.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/cache/Vary.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/UriTemplateTest.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTestBase.java

Allow to create Web Client `HttpRequest` using a compiled URI Template based on [RFC 6570](https://datatracker.ietf.org/doc/html/rfc6570) and parameterise it
```java
UriTemplate requestUri = UriTemplate.of("/some-uri?{param}");
Future<HttpResponse<Buffer>> response = client.get(8080, "myserver.mycompany.com", requestUri)
.setTemplateParam("param", "param_value")
.send();
```

Web Client URI Template

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/cache/Vary.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/CachingWebClientTest.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/impl/cache/VaryTest.java

Related to https://github.com/vert-x3/vertx-web/issues/2135
BTW @vietj while using RequestOptions in the test I realised that headers field is not initialised. 
Until now, as we were using HttpReqImpl, the 'headers' field was initialised always, headers = HttpHeaders.headers();  or the like ... so I'd suggest to do the same in RequestOptions, what do you think ?

Vary to ignore content encoding

---

vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderTest.java
vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthorizationHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/XhrTransport.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSSessionContextTest.java
vertx-web/src/test/java/io/vertx/ext/web/sstore/ClusteredSessionHandlerTest.java

Motivation:
Trying to simplify the internal state and avoid over engineer the parsing of the request body when protocol upgrades are needed.

Hold request parsing, until really required

---

vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/BaseValidationHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/NoopBodyProcessorGenerator.java
vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/body/JsonBodyProcessorImpl.java
vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/body/TextPlainBodyProcessorImpl.java
vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/JsonBodyProcessorImplTest.java
vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/TextPlainBodyProcessorTest.java
vertx-web/src/main/java/io/vertx/ext/web/RequestBody.java
vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FormLoginHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/WebAuthnHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BaseTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/XhrTransport.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RequestBodyImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextInternal.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSWriteHandlerTestServer.java
vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java
vertx-web/src/test/java/io/vertx/ext/web/it/FIDO2TCK.java

Motivation:
Fix #2096 
Currently the body of a request is not cached, so if several handlers request a decoded view of the body, parsing will happen multiple times.

Fix #2096: Avoid reparsing of body

---

vertx-web/src/main/java/io/vertx/ext/web/handler/CSRFHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java

Motivation:
Adds a method to add the flag 'Secure' to the XSRF-Token cookie.
Conformance:

allow setting 'Secure' flag on XSRF Token cookie

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextInternal.java
vertx-web/src/test/java/io/vertx/ext/web/SubRouterTest.java

The current algorithm was using the wrong parent class, which leads to getting the wrong basepath.

Fixes #2185: use the right class hierarchy to compute the basePath

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClient.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java

Motivation:
Shouldn't `WebClient.close()` return a `Future<Void>` instance like the other `close()` functions in Vert.x, such as the wrapped `HttpClient.close()`?

Make `WebClient.close()` return `Future<Void>`

---

vertx-web-openapi/pom.xml
vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/ContractEndpointHandler.java
vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderImpl.java

Motivation:
databind is a source of CVEs, for all internal usages we should avoid pulling it to ensure that the library code is less prone to attacks.

Avoid depending on databind for internal usage only

---

vertx-web/src/main/java/io/vertx/ext/web/impl/HttpServerRequestWrapper.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/ClusteredSessionStoreImpl.java
vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/LocalSessionStoreImpl.java
vertx-web/src/test/java/io/vertx/ext/web/it/SessionHandlerRegression.java

Motivation:
Session stores were returing futures on the `ctor` context, not on the caller context and this is problematic as 2 event loops may be involved on fetching the data from the store and the request event loop would loose the body.

Ensure that stores are returning futures on the right context

---

vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ApolloWSHandlerImpl.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/GraphQLWSHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
vertx-web/src/test/java/io/vertx/ext/web/ForwardedTest.java

Motivation:
Properly process the the headers `Connection` and `Upgrade` to verify if a connection can be upgraded to websocket.
Fixes: #2209

Properly handle the verification of protocol upgrade

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/OAuth2AuthHandlerTest.java

Motivation:
When the oauth2 handler is shared it can trigger onmount events multiple times which would re-attempt to setup the callback handler. This PR ensures that it only mounts once.

Fix https://github.com/vert-x3/vertx-auth/issues/568

---

vertx-web/src/main/asciidoc/index.adoc

Signed-off-by: Nils Renaud <renaud.nils@gmail.com>
Motivation:
I was asked to add a word about lazy sessions in the documentation. That's actually a good idea ! So it's done now :)
Conformance:
✅ Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
✅ Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

Add a word on the lazy session mechanism in the doc + fix typos

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java

The option is already supported by `HttpClient`, `WebClient` just doesn’t pass it on.
Motivation:
This is a very useful option for tracing in telemetry. It's already supported by `HttpClient`, it's now just passed on properly by `WebClient`.
Conformance:

Pass `RequestOptions.traceOperation` from `HttpRequest` to `HttpClientRequest`

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java

This is a back port of #2233 to 4.2 series
The option is already supported by `HttpClient`, `WebClient` just doesn’t pass it on.
Motivation:
This is a very useful option for tracing in telemetry. It's already supported by HttpClient, it's now just passed on properly by WebClient.
Conformance:

Backport: Pass `RequestOptions.traceOperation` from `HttpRequest` to `HttpClientRequest`

---

vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

Motivation:
Follow up on https://github.com/vert-x3/vertx-auth/issues/573
Allows usage of empty usernames, for example in basic auth

allow empty usernames

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/SessionAwareInterceptor.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/predicate/PredicateInterceptor.java

- provide convenient getters on the HttpRequest interface allowing to retrieve relevant information
- the HttpRequest implementation now overrides ssl/host/port/uri when an absolute URI template is used, just like with an absolute URI string
fixes #2237

Various changes to web client HttpRequest

---

vertx-web-graphql/pom.xml
vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/LocaleTest.java

> This is release 19.0 of GraphQL Java. This release doesn't contain any breaking changes.
> 
> It contains one security related bugfix hardening GraphQL Java more against malicious requests: https://github.com/graphql-java/graphql-java/pull/2892
> 
> GraphQL Java now shades Antlr runtime to prevent any further dependency conflicts. Antrl is used internally for parsing and validating of GraphQL requests and SDL. https://github.com/graphql-java/graphql-java/pull/2854
> 
> It includes some performance improvements (https://github.com/graphql-java/graphql-java/pull/2786, https://github.com/graphql-java/graphql-java/pull/2769, https://github.com/graphql-java/graphql-java/pull/2839) and several bugfixes and general improvements.
> 
> Bugfixes
> …

Bump com.graphql-java:graphql-java from 18.2 to 19.0

---

vertx-web-graphql/pom.xml

Dependabot does not support this syntax. See : https://github.com/dependabot/dependabot-core/issues/5438
Release notes : https://github.com/graphql-java/graphql-java/releases/tag/v19.1
> This bug fix release was made to address a specific NullPointerException problem if consumers are explicitly setting the ExecutionInput to null
> 
> See https://github.com/graphql-java/graphql-java/pull/2908 for the code details.
> 
> The other fixes are included because they are... well... fixes and where ready at the time.
> 
> What's Changed
> Defaults Locale when calling validation by @bbakerman in https://github.com/graphql-java/graphql-java/pull/2908
> Handles isDeprecated not being present in the json by @bbakerman in https://github.com/graphql-java/graphql-java/pull/2910
> Fix typo in description …

Bump com.graphql-java:graphql-java from 19.0 to 19.1

---

vertx-web-openapi/pom.xml

Motivation:
Upgrading org.yaml:snakeyaml from 1.30 to 1.31 in vertx-config-yaml
fixes a Denial of Service (DoS) vulnerability caused by a missing
nested depth limitation for collections.
https://nvd.nist.gov/vuln/detail/CVE-2022-25857

Upgrade snakeyaml from 1.30 to 1.31 fixing CVE-2022-25857

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

fix: WebClient ignoring RequestOptions.setTimeout/setFollowRedirects/setProxyOptions (#2265)

---

vertx-web-openapi/pom.xml

Current snakeYAML 1.31 is still affected by https://github.com/advisories/GHSA-9w3m-gqgf-c4p9 which was fixed in 1.32.

Bump snakeYAML to fix CVE-2022-38752

---

vertx-web-graphql/pom.xml

Dependabot does not support this syntax. See : https://github.com/dependabot/dependabot-core/issues/5438
Release notes : https://github.com/graphql-java/graphql-java/releases/tag/v19.2

build(deps): bump com.graphql-java:graphql-java from 19.1 to 19.2

---

vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/AuthenticationHandlersStore.java
vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderSecurityScopesTest.java
vertx-web-openapi/src/test/resources/specs/security_scopes_test.yaml

When scoping a handler to a set of required scopes, the
AuthenticationHandlersStore was previously mutating the original list
keyed for the security scheme. This will result in subsequent uses of
the same security scheme to have other scopes applied.
Adding a unit test to verify failure case.
Updated the AuthenticationHandlersStore to return new
AuthenticationHandlers with the scopes applied, but not replace the
original Handler.
Motivation:
Fix for: https://github.com/vert-x3/vertx-web/issues/2253
Conformance:
Please also make sure you adhere to the code style guidelines: …

Ensure required scopes do not leak across routes

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java

Motivation:
Fixes #2282
H2 requests are framed and should not include the `Tranfer-Encoding` header (reserved for HTTP1.1) for this reasons we can always assume that requests are chunked.
Also passes for empty body:
```java
@Test
void shouldUploadHttp2NoContent(final VertxTestContext context) {
final var router = Router.router(vertx);
router.route().handler(BodyHandler.create());
router.route().handler(routingContext -> {
context.verify(
() -> Assertions.assertEquals("application/json", routingContext.parsedHeaders().contentType().value())
);
routingContext.response().end();
});
final var server = vertx.createHttpServer(new HttpServerOptions().setLogActivity(true).setActivityLogDataFormat(ByteBufFormat.HEX_DUMP))
.requestHandler(router) …
```

H2 requests are chunked due to framing

---

vertx-template-engines/pom.xml
vertx-template-engines/vertx-web-templ-pug/pom.xml
vertx-template-engines/vertx-web-templ-pug/src/main/java/io/vertx/ext/web/templ/pug/PugTemplateEngine.java
vertx-template-engines/vertx-web-templ-pug/src/main/java/io/vertx/ext/web/templ/pug/impl/PugTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-pug/src/main/java/io/vertx/ext/web/templ/pug/package-info.java
vertx-template-engines/vertx-web-templ-pug/src/main/resources/META-INF/MANIFEST.MF
vertx-template-engines/vertx-web-templ-pug/src/test/filesystemtemplates/test-pug-template3.pug
vertx-template-engines/vertx-web-templ-pug/src/test/java/io/vertx/ext/web/templ/PugTemplateNoCacheTest.java
vertx-template-engines/vertx-web-templ-pug/src/test/java/io/vertx/ext/web/templ/PugTemplateTest.java
vertx-template-engines/vertx-web-templ-pug/src/test/resources/somedir/test-pug-template-umlaut.pug
vertx-template-engines/vertx-web-templ-pug/src/test/resources/somedir/test-pug-template2.foo
vertx-template-engines/vertx-web-templ-pug/src/test/resources/somedir/test-pug-template2.made
vertx-template-engines/vertx-web-templ-pug/src/test/resources/somedir/test-pug-template2.pug

jade4j is now pug4j: https://github.com/neuland/jade4j#readme
Therefore we deprecate vertx-web-templ-jade and add vertx-web-templ-pug with jade renamed to pug.

Add vertx-web-templ-pug, deprecate vertx-web-templ-jade

---

vertx-web-validation/src/main/asciidoc/index.adoc
vertx-web-validation/src/main/java/examples/WebValidationExamples.java

Motivation:
fix https://github.com/vert-x3/vertx-web/issues/2234
The method `ValidationHandler#builder`  is marked as deprecated, update the document and example

Doc: update the demo of creating the ValidationHandler

---

vertx-web-graphql/pom.xml

Release notes : https://github.com/graphql-java/graphql-java/releases/tag/v19.3

build(deps): bump com.graphql-java:graphql-java from 19.2 to 19.3

---

vertx-web/src/main/java/io/vertx/ext/web/handler/CorsHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CORSHandlerTest.java

This PR relaxes the CORS handler to allow both lists of patterns OR lists of static origins
Fixes: https://github.com/vert-x3/vertx-web/issues/2311

Attempt to allow multiple regex'es in cors

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CORSHandlerTest.java

When allow origin * is used in conjunction with allow credentials, the allow origin response headers is set to the requested origin. Thus the Vary origin header needs to be included to ensure browsers receive the correct response.
Motivation:
Fix for: https://github.com/vert-x3/vertx-web/issues/2319
Conformance:

Fix CORS cache behavior with allow credentials

---

vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerWindowsTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSRawTransportTest.java

Fix the webroot escape to classpath on windows

Fix the webroot escape to classpath on windows

---

vertx-web-openapi-router/src/test/java/io/vertx/router/test/base/RouterBuilderTestBase.java
vertx-web-openapi-router/src/test/java/io/vertx/router/test/e2e/RouterBuilderTest.java

Motivation:
The new vertx-openapi version takes the "servers" property of the contract into account. Because of this the tests must also use the base path "v1", which is defined in the "petstore.json" which is used for the tests.

feat(openapi-router): adopt tests to new vertx-openapi version

---

vertx-web-openapi-router/src/test/java/io/vertx/router/test/e2e/RouterBuilderSecurityAndAuthZTest.java

Motivation:
Fix #2191 : The new OpenAPI properly addresses the right order of handlers.

Fix #2191: Authz handlers are not raising errors anymore

---

vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/ConnectionHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/GraphQLWSHandlerImpl.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/ws/GraphQLWSHandler.java

Similar to `ApolloWSHandler`'s `messageHandler` method behavior
implementation of the message interception mentioned in #2410

Graphqlws message interception

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java
vertx-web/src/test/java/io/vertx/ext/web/handler/SlowClusterEventbusBridgeTest.java

Fixes #2407
Otherwise, when Vert.x is clustered and registration is slow, the consumer may miss some messages.

EventBusBridge should fire REGISTERED event after registration completion

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java

A suggested fix for issue #2438 - if the `BodyHandler` was started too late,  make sure the developer knows they made a mistake by logging the problem, making a suggestion for a fix, and failing the request.

When detecting request ended, make sure processing stops with an error

---

vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/SlowClusterEventbusBridgeTest.java

See #2423
Otherwise, if the user unregisters immediately after registration, and the cluster registration is slow, there might be orphan registration.

EventBusBridge must save registration locally before completion

---

vertx-web/src/main/java/io/vertx/ext/web/impl/ForwardedParser.java
vertx-web/src/test/java/io/vertx/ext/web/ForwardedTest.java

The x-forwarded-XXX parser does not handle correctly raw IPV6 address… (not enclosed within square brackets) that some intermedaries can send, the parser will try to parse the port part of the actual IPV6 address.
This fixes the parser to handle IPV6 addresses when they are not enclosed within square brackets.

ForwardedParser improvements

---

vertx-web/src/main/java/io/vertx/ext/web/WebServerRequest.java
vertx-web/src/main/java/io/vertx/ext/web/impl/HttpServerRequestWrapper.java

Related to https://github.com/eclipse-vertx/vertx-http-proxy/issues/50
(Also https://github.com/vert-x3/vertx-web/pull/2461)

Extends HttpServerRequestWrapper to access the routing context associated with the request

---

vertx-web-graphql/src/main/asciidoc/index.adoc
vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/ConnectionHandler.java
vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/ws/GraphQLWSHandlerImpl.java

This can be useful when, e.g. the webapp is protected with authentication.
This was already possible with the GraphQL handler

GraphQLWS: store the RoutingContext in GraphQLContext

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java

Motivation:
adjust the behaviour of the CSRF handler so that users can no longer be trapped if the API handler behind the CSRF handler never responds.
Fixes: https://github.com/vert-x3/vertx-web/issues/2447
Signed-off-by: Chris Patmore <chrism.patmore@btinternet.com>

fix: stop users being trapped by unresponsive APIs

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java

Motivation:
The updated CSRF handler would attempt to set the token into the session even when a new one was
not generated, this opened a timing issue where a GET request that started during / before a POST
but ended after would revert the changed token, leaving the user stuck
Contributes To: https://github.com/vert-x3/vertx-web/issues/2447

fix: don't update session on GET with token already set

---

vertx-web-graphql/pom.xml

Summary : 
This is a release with new features and bugfixes. There are no breaking changes.
Full release notes : 
https://github.com/graphql-java/graphql-java/releases/tag/v21.2
> @oneOf directive
> We've implemented the @oneOf directive for input objects. From the https://github.com/graphql/graphql-spec/pull/825:
> 
> OneOf Input Objects are a special variant of Input Objects where the type system asserts that exactly one of the fields must be set and non-null, all others being omitted
> 
> This will soon be a new built-in directive in the GraphQL specification.
> 
> The directive is currently labelled as experimental inside graphql-java while we wait for the RFC to be formally approved. The final step before the RFC is approved is your feedback! If you're using @oneOf, please share your …

build(deps): bump com.graphql-java:graphql-java from 21.1 to 21.2

---

vertx-template-engines/vertx-web-templ-mvel/pom.xml

Motivation:
Fix issue #2484
We can also remove old @vietj comment "Stack version don't change this" and update it, because vert.x core stack don't use mvel anymore (as far as I know mvel was used by vertx-codegen, but it was refactored).
We already use vertx-web-templ-mvel with excluded and forced new version of mvel in our project on Java 21 without problems.

Fixes #2484

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/HotpAuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/TotpAuthHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/WebAuthnHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java

Related to #2486
Follows-up on #1857
ISE creates a stack trace which isn't really useful. In these cases, we only care about the message.
This change makes the application log a single line (or more if the message is long). Besides, it saves the cost of creating the ISE stack trace.
Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:

Replace ISE with VertxException when failing context with informational message

---

vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/handlebars/impl/HandlebarsTemplateEngineImpl.java

Motivation:
When developing locally on a Windows Machine while using Handlebars, it's often the use case to use partials.
The current implementation does not use Java's File Implementations/Path resolutions, and uses it's own way to handle this.
While it works on Unix based File-Systems, on Windows based ones this doesn't work, as it's checking for `/` characters explicitly, which is not the separator character for Windows.
Using Java's `File.separator` constant which is platform agnostic, this can be easily fixed.

Fix handlebars partial template resolution for windows

---

vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/handlebars/impl/HandlebarsTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateTest.java

On Windows, HandlebarsTemplateEngine should search for slash and backslash separators

---

vertx-web/src/test/java/io/vertx/ext/web/handler/OAuth2AuthHandlerTest.java

The OAuth2AuthHandlerTest#testAuthPKCECodeFlow fails because the resource owner expects the code_challenge to not be the first parameter of the redirection sent by the client.
Update the OAuth2AuthHandlerTest#testAuthPKCECodeFlow to test to parse the redirection URI and get a map of params instead.

Fix OAuth2AuthHandlerTest#testAuthPKCECodeFlow test

---

vertx-web/src/main/java/io/vertx/ext/web/Route.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Motivation: Fixes https://github.com/vert-x3/vertx-web/issues/1506
This PR tries to add a method Router getSubRouter() in Route class, so that it provides a way to get the sub router if there is and get the routes of the sub router recursively.
Users can use:
```java
List<Route> routes = router.getRoutes();
for(Route route: routes) {
Router subRouter = route.getSubRouter();
if (subRouter != null) {
// routes in sub router is subRouter.getRoutes();
}
}
```
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:
Please also make sure you adhere to the code style …

[Issue-1506] Provide a method to get sub router if current route acts as a sub router

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java

`String::equals` got a special treatment on JDK (it's an intrinsic), while `regionMatches` has only recently received such treatment, via https://bugs.openjdk.org/browse/JDK-8302163
This is introducing a fast-path using `equals` whetever possible.

Enable using String::equals fast-path intrinsics for exact matches

---

vertx-web/src/main/java/io/vertx/ext/web/impl/ForwardedParser.java
vertx-web/src/test/java/io/vertx/ext/web/ForwardedTest.java

The ForwardedParser fails when the host header is missing for HTTP/1.x with an NPE.

Fix NPE in ForwardedParser when host header is missing for HTTP/1.1

---

vertx-template-engines/vertx-web-templ-mvel/src/main/java/io/vertx/ext/web/templ/mvel/impl/MVELTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-mvel/src/test/filesystemtemplates/subfolder/include-test2.txt
vertx-template-engines/vertx-web-templ-mvel/src/test/filesystemtemplates/test-mvel-template4.templ
vertx-template-engines/vertx-web-templ-mvel/src/test/java/io/vertx/ext/web/templ/MVELTemplateTest.java

There was a regression introduced in #468. The user-supplied variables were passed to the template engine with a MapVariableResolverFactory and we switched to a context object.
For this reason, it was no longer possible to declare variables in template files.
In this PR, we invoke the template engine with a MapVariableResolverFactory again, instead of the ImmutableDefaultFactory (which prevents from declaring variables).

Support MVEL variable resolver again

---

vertx-web/src/main/asciidoc/index.adoc

You may include a template file into an MVEL template using `@include{}`, as long as the templates reside on the filesystem.
Template inclusion doesn't work if the templates are loaded from the classpath using the Vert.x file resolver.
This is a limitation of the MVEL engine: some other engines let Vert.x plug in a custom template file resolver, MVEL doesn't.

Document MVEL limitation regarding inclusions

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/MultipartFormUpload.java

Related to #2308
When creating a simple attribute, use memory storage, regardless of the value size.
Otherwise, Netty creates a temporary file when the size if above the default limit (16KB).

MultipartFormUpload: use MemoryAttribute

---

vertx-web/src/main/java/io/vertx/ext/web/impl/ForwardedParser.java
vertx-web/src/test/java/io/vertx/ext/web/ForwardedTest.java

As described on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded, the forwarded header syntax parsing should be case-insensitive. It's not a real spec, but Kong is using Proto instead of proto and For instead of for...

Make the Forwarded Parser syntax parsing case-insensitive

---

vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTestBase.java

It's already setup in the setup method of the parent test class. And when this is called by a shared client test, Vert.x counts 2 shared client instances.
Consequently, some tests which rely on closing the original http client before creating another one may not work.

WebClientTestBase#setup should not recreate the Http Client

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

Fixes #2571
Without this fix, we can't integrate the Vert.x Web Client and the Vert.x Service Resolver.

WebClient should use the Address specified in RequestOptions

---

vertx-web-openapi-router/src/main/java/io/vertx/ext/web/openapi/router/impl/RouterBuilderImpl.java
vertx-web-openapi-router/src/test/java/io/vertx/router/test/e2e/RouterBuilderTest.java

This commit wraps the ValidatorException caught in RouterBuilder inside a HTTPException.
This allows the default error handling of RoutingContext to handle the failure properly.

fix(openapi): change status code for invalid requests to 400

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ChainAuthHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/ChainAuthHandlerTest.java

See #2408
Some auth handlers have postAuthentication methods that must be invoked. For example, FormLoginHandler may have to redirect the client after authentication.
ChainAuthHandler was not able to invoke the post-authentication method of the handler that authenticated the user.

ChainAuthHandler should invoke postAuthentication

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/BodyHandlerTest.java

The `BodyHandler` does not correctly handler max form limits and does not log correctly the decoder exception, assuming incorrectly that the decoder exception always contains a cause.
Change: only unwrap the cause to log when there is actually one.

Let the body handler correctly log the decoder exception

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/cache/CacheControl.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/impl/cache/CacheControlTest.java

Netty's date parse function returns `null` on a misformatted date. This wasn't handled properly in the cache control.

fix: NPE on misformatted Date or Expires header

---

vertx-web-client/src/main/asciidoc/index.adoc
vertx-web-client/src/main/java/examples/WebClientExamples.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpResponse.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpResponseImpl.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/predicate/ErrorConverter.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/predicate/ResponsePredicate.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/predicate/ResponsePredicateResult.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/InterceptorTest.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

Documentation is updated with the HTTP response expectation API, response predicate API is deprecated.

New web client expectation API

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/HttpContextTest.java

A `WebClient` interceptor can transition the `HttpContext` to the failure state, when this happens after an client request has been allocated this request remain allocated and not cleaned.
Modify the `HttpContext` implementation to cleanup the client request after processing the cleanup phase.

The WebClient does not release always the underlying client request when failing

---

vertx-web-graphql/pom.xml

Release notes: https://github.com/graphql-java/graphql-java/releases/tag/v22.0

Upgrade graphql-java from 21.5 to 22.0

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java

Motivation:
There is a typo in the error message regarding the minium required length of the PKCE in Oauth2. Correct is `43`:
> NOTE: The code verifier SHOULD have enough entropy to make it
impractical to guess the value.  It is RECOMMENDED that the output of
a suitable random number generator be used to create a 32-octet
sequence.  The octet sequence is then base64url-encoded to produce a
43-octet URL safe string to use as the code verifier.
(Source: https://www.rfc-editor.org/rfc/inline-errata/rfc7636.html)

Fix typo in error mesage regarding the oauth2 pkce length

---

vertx-web-session-stores/vertx-web-sstore-cookie/pom.xml
vertx-web-session-stores/vertx-web-sstore-cookie/src/main/java/io/vertx/ext/web/sstore/cookie/CookieSessionStore.java
vertx-web-session-stores/vertx-web-sstore-cookie/src/main/java/io/vertx/ext/web/sstore/cookie/impl/CookieSession.java
vertx-web-session-stores/vertx-web-sstore-cookie/src/main/java/io/vertx/ext/web/sstore/cookie/impl/CookieSessionStoreImpl.java
vertx-web-session-stores/vertx-web-sstore-cookie/src/test/java/io/vertx/ext/web/sstore/cookie/CookieSessionCreateTest.java
vertx-web-session-stores/vertx-web-sstore-cookie/src/test/java/io/vertx/ext/web/sstore/cookie/CookieSessionHandlerTest.java
vertx-web/src/main/asciidoc/index.adoc

Motivation:
The Cookie store was used as a template to create other stores, given that some users are asking to use it in prod, for 5.0.0 the recommended way is to have the content, not signed, but encrypted.
Signed was proving non repudiation and tampering, encryption adds non-disclosure to the implementation.

Encrypt instead of sign: cookie store

---

vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
vertx-web/src/test/java/io/vertx/ext/web/healthchecks/HealthCheckTest.java
vertx-web/src/test/java/io/vertx/ext/web/healthchecks/HealthCheckTestBase.java

Fix #2551
In StaticHandlerTest, some tests create alternative http servers. We must make sure the original and the replacement servers are closed properly. Otherwise, the test results may be affected by the test execution order.
In HealthCheckTestBase, we make sure the client, the server and the Vert.x server are closed properly, and in this order.

Intermittent test failures in Healthcheck tests and StaticHandlerTest

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/TimeoutHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/HandlersList.java
vertx-web/src/test/java/io/vertx/ext/web/handler/TimeoutHandlerTest.java

See #2617
After reroute, the bodyEndHandler was removed, so the timer couldn't be canceled. Now we check if the bodyEndHandler is still present before failing the request.
Note: we need unique ids for the lifetime of the RoutingContext, this is why HandlersList has to be modified.

TimeoutHandler shouldn't fail the request if the router has been restarted

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java

Firstly, the CSRF token is put in the session (if there is one) as soon as it is generated. By doing so, we make sure the token is persisted and when the session is flushed (when response headers have been sent). Then, the CSRFHandler works not only with a LocalSessionStore, but with any distributed session store.
Secondly, the CSRF cookie is sent to the client in response to GET requests whenever the value is no longer synchronized with the value stored in the session (if there is one). This prevents users from being "trapped" if a new token has been generated but never makes to the client (e.g. if the response body never makes it to the client).
See #2599

CSRFHandler improvements

---

vertx-web/src/main/java/io/vertx/ext/web/WebServerRequest.java
vertx-web/src/main/java/io/vertx/ext/web/impl/HttpServerRequestWrapper.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Before this change, it was expected that a `Route` handler implementation wraps the `HttpServerRequest` (again, since it was already wrapped by the routing context).
This was confusing, because in Vert.x Web apps, the `HttpServerRequest` implemented `WebServerRequest` but invocations of its `routingContext()` method always returned `null`.

Always set the routing context in HttpServerRequestWrapper

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
vertx-web/src/test/java/io/vertx/ext/web/tests/RouterTest.java

Motivation:
Solves the bug described in #2656. Instead of returning a 400 in case of a missing content type, it now returns a 415. For further details, see the issue.
It does not add the return of an `Accept` header in case of a mismatched content type. But I would not see this as a bug but rather as an enhancement which needs its own issue.
Currently waiting for an account with the Eclipse Foundation but they currently experience issues with user sign up. I will sign the ECA as soon as possible.
EDIT: Signed the ECA.

Always return a 415 if the content type is mismatching, also if its value is empty

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/test/java/io/vertx/ext/web/tests/RouterTest.java

**Motivation:**
For certain types of bad requests, any error handlers for status code 400 will be invoked more often than desired. This means that such an error handler is invoked twice in a row, or immediately after a failure handler has already handled the bad request.
I've created a demo application that illustrates the issue and provides additional details: https://github.com/ljpengelen/vertx-errors-and-failures.
**Conformance:**
I've signed the Eclipse Contributor Agreement, and my commits are verified.

Handle routing errors once

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java

Motivation:
The implementation of routing context might fail the context within its constructor forcing the router to check the context status before routing the request.
Changes:
Create package private route method that performs the preliminary checks of the routing context and calls the routing context handler chain whenever the checks have passed

Move the routing context implementation to a separate method instead of failing the context within the constructor

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java

Motivation:
I noticed that `JSON` is getting double-encoded and wastefully converted `toString` then `toBuffer`
As per the benchmarks in [vertx-core](https://github.com/eclipse-vertx/vert.x/blob/4.x/src/test/benchmarks/io/vertx/benchmarks/JsonEncodeBenchmark.java) it shows that this is actually wasteful:
```
Benchmark                                          Mode  Cnt  Score    Error  Units
JsonEncodeBenchmark.deepBufferDatabind             avgt   10  0.974 ±  0.025  ms/op
JsonEncodeBenchmark.deepBufferJackson              avgt   10  0.935 ±  0.018  ms/op
JsonEncodeBenchmark.deepStringDatabind             avgt   10  1.258 ±  0.006  ms/op
JsonEncodeBenchmark.deepStringJackson              avgt   10  1.270 ±  0.006  ms/op
JsonEncodeBenchmark.deepStringThenBufferDatabind   avgt   10  1.471 ± …
```

fix(HttpContext): unnecesery string to buffer json encoding

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java

Motivation:
Backport of https://github.com/vert-x3/vertx-web/pull/2662 and https://github.com/vert-x3/vertx-web/pull/2666.

Prevent duplicate invocation of error handler

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClient.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClientOptions.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java

This commit adds the ability to update the SSLOptions on the WebClient, similar to the methods in `io.vertx.core.http.HttpClient`. Internally, we delegate the calls to the underlying client.
Motivation:
We don't have a way to directly update the SSLOptions in WebClient. We need to keep a reference
to the wrapped HttpClient in able to update SSLOptions.
Conformance:

Adds methods to update SSL Options to WebClient

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java

Motivation:
Porting #2669 to `5.x`

fix(HttpContext): unnecessary string to buffer json encoding

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/OAuth2WebClient.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClient.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClientSession.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/Oauth2WebClientAware.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientInternal.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientSessionAware.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/VerticleUndeployTest.java

Motivation:
WebClient interceptor API is still internal and has proven to be stable
Changes:
Move WebClient interceptor to public API.

Promote WebClient interceptor to public API

---

vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java

Motivation:
On Quarkus side we have the following issue https://github.com/quarkusio/quarkus/issues/43936, the idea here is to improve the message error.

Add a better message error on RoutingContextImpl

---

vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
vertx-web/src/main/java/io/vertx/ext/web/UserContext.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
vertx-web/src/main/java/io/vertx/ext/web/impl/UserContextImpl.java
vertx-web/src/test/java/io/vertx/ext/web/handler/BasicAuthImpersonationTest.java
vertx-web/src/test/resources/login/loginusers.properties

Motivation:
Vert.x 5 has a new `UserContext` API that encapsulate the API present on `Routingcontext` in addition of new identity related operations. This API can be back-ported to 4.5.x to ease migration to Vert.x 5 .
Changes:
Partial part of the `UserContext` API and documentation, as well as a couple of deprecations in favour of this new API.

Port to 4.5.x the UserContext API

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/MultipartFormUpload.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/MultipartFormUploadTest.java

Fixes #2696 
`MultipartFormUpload` is created on the Vert.x context that is bound to the request promise.
We should create the queue using the context executor for both the producer and consumer sides.
Otherwise, if there is a large upload and the queue needs to be paused/resumed, the `pump` method will be invoked on the EventLoop executor bound to this context. And then the IllegalArgumentException is thrown.

WebClient failure when sending multipart formdata from a virtual thread

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java

This guarantees that request promise callbacks will always be invoked on the right context.

Web Client: use request promise bound to the creating context

---

vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
vertx-web-client/src/test/java/io/vertx/ext/web/client/tests/WebClientTest.java

Only one header value of several is sent with MultipartForm body

---

vertx-web-proxy/src/test/java/io/vertx/ext/web/proxy/tests/handler/ProxyHandlerTest.java
vertx-web-proxy/src/test/java/module-info.java
vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java

See #2676
`ProtocolUpgradeHandler` (GraphQLWS, Proxy) instances must not be installed after the `BodyHandler`. However, they are often used with authentication handlers (e.g. Basic auth handler), because authentication can be required before allowing the connection upgrade. The problem is that, currently, authn/authz handlers have higher priorities than body handlers (for good reasons, we may need to inspect the body to perform form login). So, if a user tries to install a `ProtocolUpgradeHandler` after an auth handler, an ISE is thrown.
With this change, the order of priorities is not changed. Instead, there's a special check for `ProtocolUpgradeHandler` instances: the `BodyHandler` must not be found in the already installed handlers.
Also, the warning about `ProtocolUpgradeHandler` …

Improve ProtocolUpgradeHandler priority checking

---

vertx-web/src/main/java/io/vertx/ext/web/handler/LoggerFormat.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java
vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
vertx-web/src/test/java/io/vertx/ext/web/tests/handler/LoggerHandlerTest.java

Motivation:
Vert.x Web Log handler uses a custom format similar to apache.
This PR adds a valid NSCA Combined log format that allows users to consume the log in web log analysis tools without fidling with the format.

Adding support for combined log format

---

vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/freemarker/FreeMarkerTemplateEngine.java
vertx-template-engines/vertx-web-templ-freemarker/src/main/java/io/vertx/ext/web/templ/freemarker/impl/FreeMarkerTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/handlebars/HandlebarsTemplateEngine.java
vertx-template-engines/vertx-web-templ-handlebars/src/main/java/io/vertx/ext/web/templ/handlebars/impl/HandlebarsTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-httl/src/main/java/io/vertx/ext/web/templ/httl/HTTLTemplateEngine.java
vertx-template-engines/vertx-web-templ-httl/src/main/java/io/vertx/ext/web/templ/httl/impl/HTTLTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/JteTemplateEngine.java
vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/impl/JteTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/PebbleTemplateEngine.java
vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-pug/src/main/java/io/vertx/ext/web/templ/pug/PugTemplateEngine.java
vertx-template-engines/vertx-web-templ-pug/src/main/java/io/vertx/ext/web/templ/pug/impl/PugTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-rocker/src/main/java/io/vertx/ext/web/templ/rocker/RockerTemplateEngine.java
vertx-template-engines/vertx-web-templ-rythm/src/main/java/io/vertx/ext/web/templ/rythm/RythmTemplateEngine.java
vertx-template-engines/vertx-web-templ-rythm/src/main/java/io/vertx/ext/web/templ/rythm/impl/RythmTemplateEngineImpl.java
vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/thymeleaf/ThymeleafTemplateEngine.java
vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/thymeleaf/impl/ThymeleafTemplateEngineImpl.java
vertx-web-common/src/main/java/io/vertx/ext/web/common/template/TemplateEngine.java

Motivation:
The `TemplateEngine#unwrap` uses a free downcast pattern (`<T> T`) that does not indicate the actual engine type and force the developer to know about the actual type to cast to.
This can be replaced by covariant return type that carries the exact type of the unwrapped engine.
Changes:
- remove generic <T> declaration in unwrap
- template engine supporting it, overrides this method with the actual engine type

Replace free cast in TemplateEngine#unwrap with covariant return type.

---

vertx-web/src/main/java/io/vertx/ext/web/handler/LoggerHandler.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java

`user.subject` may be null and it would break the log format. Also vert.x auth imposes no restrictions on the use of ` ` (spaces) so we need to quote the username if spaces are present.

fix: subject may be null which renders the log incorrectly

---

vertx-web/src/main/java/io/vertx/ext/web/handler/impl/TimeoutHandlerImpl.java
vertx-web/src/test/java/io/vertx/ext/web/tests/handler/TimeoutHandlerTest.java

See #2727
This allows the timeout to be cancelled in all circumstances, including loss of the connection.

Implement TimeoutHandler with an endHandler

---

vertx-web/src/main/asciidoc/index.adoc
vertx-web/src/main/java/examples/WebExamples.java
vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java

Instructions were missing for CSRF, SockJS and FormLogin handlers.
Backported from https://github.com/vert-x3/vertx-web/pull/2759

Documentation must indicate when a BodyHandler is required

---

vertx-web/src/test/java/io/vertx/ext/web/tests/RouterTest.java

This test fails repeatedly on Windows (gets 400 BAD Request).
Fix it by sending CRLF (as mandated by the spec).
Latest Netty version applies a strict policy regarding line endings for security reasons.

Fix testPauseResumeOnPipeline on Windows
